// ===========================================================
// HLS sources generated by ActiveCore framework
// Date: 2020-10-25
// Copyright Alexander Antonov <antonov.alex.alex@gmail.com>
// ===========================================================

#include "riscv_2stage.hpp"
#include <ap_int.h>
#include <hls_stream.h>

	ap_uint<32> genpsticky_glbl_pc;
	ap_uint<32> genpsticky_glbl_regfile [32];
	ap_uint<1> genpsticky_glbl_jump_req_cmd;
	ap_uint<32> genpsticky_glbl_jump_vector_cmd;
	ap_uint<8> genpsticky_glbl_CSR_MCAUSE;
	ap_uint<1> genpsticky_glbl_MIRQEN;
	ap_uint<32> genpsticky_glbl_MRETADDR;
	ap_uint<1> genmcopipe_instr_mem_wr_done;
	ap_uint<1> genmcopipe_instr_mem_rd_done;
	ap_uint<1> genmcopipe_instr_mem_full_flag;
	ap_uint<1> genmcopipe_instr_mem_empty_flag;
	ap_uint<1> genmcopipe_instr_mem_wr_ptr;
	ap_uint<1> genmcopipe_instr_mem_rd_ptr;
	ap_uint<1> genmcopipe_data_mem_wr_done;
	ap_uint<1> genmcopipe_data_mem_rd_done;
	ap_uint<1> genmcopipe_data_mem_full_flag;
	ap_uint<1> genmcopipe_data_mem_empty_flag;
	ap_uint<1> genmcopipe_data_mem_wr_ptr;
	ap_uint<1> genmcopipe_data_mem_rd_ptr;
	ap_uint<1> genpstage_IFETCH_genpctrl_active_glbl;
	ap_uint<1> genpstage_IFETCH_genpctrl_stalled_glbl;
	ap_uint<1> genpstage_IFETCH_genpctrl_killed_glbl;
	ap_uint<1> genpstage_EXEC_genpctrl_active_glbl;
	ap_uint<1> genpstage_EXEC_genpctrl_stalled_glbl;
	ap_uint<1> genpstage_EXEC_genpctrl_killed_glbl;
	ap_uint<1> genpstage_IFETCH_instr_req_done;
	ap_uint<1> genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_if_id;
	ap_uint<1> genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_rdreq_pending;
	ap_uint<1> genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_tid;
	ap_uint<1> genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_resp_done;
	ap_uint<32> genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_rdata;
	ap_uint<32> genpstage_EXEC_rs1_rdata;
	ap_uint<32> genpstage_EXEC_rs2_rdata;
	ap_uint<8> genpstage_EXEC_irq_mcause;
	ap_uint<1> genpstage_EXEC_irq_recv;
	ap_uint<1> genpstage_EXEC_data_req_done;
	ap_uint<1> genpstage_EXEC_genmcopipe_handle_data_mem_genvar_if_id;
	ap_uint<1> genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdreq_pending;
	ap_uint<1> genpstage_EXEC_genmcopipe_handle_data_mem_genvar_tid;
	ap_uint<1> genpstage_EXEC_genmcopipe_handle_data_mem_genvar_resp_done;
	ap_uint<32> genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdata;
	ap_uint<1> genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_if_id;
	ap_uint<1> genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdreq_pending;
	ap_uint<1> genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_tid;
	ap_uint<1> genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_resp_done;
	ap_uint<32> genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdata;
	ap_uint<32> genpstage_EXEC_curinstr_addr_genglbl;
	ap_uint<32> genpstage_EXEC_nextinstr_addr_genglbl;

void riscv_2stage(ap_uint<1> geninit, hls::stream<ap_uint<8> >& irq_fifo, hls::stream<ap_uint<32> >& genmcopipe_instr_mem_resp, hls::stream<ap_uint<32> >& genmcopipe_data_mem_resp, hls::stream<genpmodule_riscv_2stage_genmcopipe_instr_mem_genstruct_fifo_wdata>& genmcopipe_instr_mem_req, hls::stream<genpmodule_riscv_2stage_genmcopipe_data_mem_genstruct_fifo_wdata>& genmcopipe_data_mem_req) {

	ap_uint<32> genpsticky_glbl_pc_buf;
	ap_uint<32> genpsticky_glbl_regfile_buf [32];
	ap_uint<1> genpsticky_glbl_jump_req_cmd_buf;
	ap_uint<32> genpsticky_glbl_jump_vector_cmd_buf;
	ap_uint<8> genpsticky_glbl_CSR_MCAUSE_buf;
	ap_uint<1> genpsticky_glbl_MIRQEN_buf;
	ap_uint<32> genpsticky_glbl_MRETADDR_buf;
	ap_uint<1> genmcopipe_instr_mem_wr_ptr_next;
	ap_uint<1> genmcopipe_instr_mem_rd_ptr_next;
	ap_uint<1> genmcopipe_data_mem_wr_ptr_next;
	ap_uint<1> genmcopipe_data_mem_rd_ptr_next;
	ap_uint<1> genpstage_IFETCH_genpctrl_new;
	ap_uint<1> genpstage_IFETCH_genpctrl_working;
	ap_uint<1> genpstage_IFETCH_genpctrl_succ;
	ap_uint<1> genpstage_IFETCH_genpctrl_occupied;
	ap_uint<1> genpstage_IFETCH_genpctrl_finish;
	ap_uint<1> genpstage_IFETCH_genpctrl_flushreq;
	ap_uint<1> genpstage_IFETCH_genpctrl_nevictable;
	ap_uint<1> genpstage_IFETCH_genpctrl_rdy;
	ap_uint<1> gen162_pipex_syncreq;
	ap_uint<1> gen163_pipex_syncbuf;
	ap_uint<1> gen164_pipex_syncreq;
	ap_uint<32> gen165_pipex_syncbuf;
	ap_uint<1> genpstage_EXEC_genpctrl_new;
	ap_uint<1> genpstage_EXEC_genpctrl_working;
	ap_uint<1> genpstage_EXEC_genpctrl_succ;
	ap_uint<1> genpstage_EXEC_genpctrl_occupied;
	ap_uint<1> genpstage_EXEC_genpctrl_finish;
	ap_uint<1> genpstage_EXEC_genpctrl_flushreq;
	ap_uint<1> genpstage_EXEC_genpctrl_nevictable;
	ap_uint<1> genpstage_EXEC_genpctrl_rdy;
	ap_uint<1> gen166_pipex_syncreq;
	ap_uint<1> gen167_pipex_syncbuf;
	ap_uint<1> gen168_pipex_syncreq;
	ap_uint<32> gen169_pipex_syncbuf;
	ap_uint<1> gen170_pipex_syncreq;
	ap_uint<32> gen171_pipex_syncbuf [32];
	ap_uint<1> gen172_pipex_var;
	ap_uint<33> gen173_pipex_var;
	ap_uint<1> gen174_pipex_var;
	ap_uint<1> gen175_pipex_var;
	ap_uint<1> gen176_pipex_var;
	ap_uint<1> gen177_pipex_var;
	ap_uint<1> gen178_pipex_var;
	ap_uint<1> gen179_pipex_var;
	ap_uint<1> gen180_pipex_var;
	ap_uint<1> gen181_pipex_var;
	ap_uint<7> gen182_pipex_var;
	ap_uint<20> gen183_pipex_var;
	ap_uint<25> gen184_pipex_var;
	ap_uint<12> gen185_pipex_var;
	ap_uint<15> gen186_pipex_var;
	ap_uint<32> gen187_pipex_var;
	ap_uint<25> gen188_pipex_var;
	ap_uint<28> gen189_pipex_var;
	ap_uint<24> gen190_pipex_var;
	ap_uint<32> gen191_pipex_var;
	ap_uint<20> gen192_pipex_var;
	ap_uint<32> gen193_pipex_var;
	ap_uint<1> gen194_pipex_var;
	ap_uint<32> gen195_pipex_var;
	ap_uint<32> gen196_pipex_var;
	ap_uint<12> gen197_pipex_var;
	ap_uint<12> gen198_pipex_var;
	ap_uint<1> gen199_pipex_var;
	ap_uint<32> gen200_pipex_var;
	ap_uint<1> gen201_pipex_var;
	ap_uint<1> gen202_pipex_var;
	ap_uint<31> gen203_pipex_var;
	ap_uint<12> gen204_pipex_var;
	ap_uint<13> gen205_pipex_var;
	ap_uint<1> gen206_pipex_var;
	ap_uint<32> gen207_pipex_var;
	ap_uint<32> gen208_pipex_var;
	ap_uint<32> gen209_pipex_var;
	ap_uint<1> gen210_pipex_var;
	ap_uint<20> gen211_pipex_var;
	ap_uint<1> gen212_pipex_var;
	ap_uint<31> gen213_pipex_var;
	ap_uint<21> gen214_pipex_var;
	ap_uint<1> gen215_pipex_var;
	ap_uint<32> gen216_pipex_var;
	ap_uint<1> gen217_pipex_var;
	ap_uint<1> gen218_pipex_var;
	ap_uint<1> gen219_pipex_var;
	ap_uint<1> gen220_pipex_var;
	ap_uint<25> gen221_pipex_var;
	ap_uint<32> gen222_pipex_var;
	ap_uint<1> gen223_pipex_var;
	ap_uint<1> gen224_pipex_var;
	ap_uint<1> gen225_pipex_var;
	ap_uint<25> gen226_pipex_var;
	ap_uint<32> gen227_pipex_var;
	ap_uint<1> gen228_pipex_var;
	ap_uint<1> gen229_pipex_var;
	ap_uint<1> gen230_pipex_var;
	ap_uint<1> gen231_pipex_var;
	ap_uint<1> gen232_pipex_var;
	ap_uint<1> gen233_pipex_var;
	ap_uint<1> gen234_pipex_var;
	ap_uint<1> gen235_pipex_var;
	ap_uint<1> gen236_pipex_var;
	ap_uint<32> gen237_pipex_var;
	ap_uint<32> gen238_pipex_var;
	ap_uint<32> gen239_pipex_var;
	ap_uint<1> gen240_pipex_var;
	ap_uint<1> gen241_pipex_var;
	ap_uint<1> gen242_pipex_var;
	ap_uint<1> gen243_pipex_var;
	ap_uint<1> gen244_pipex_var;
	ap_uint<32> gen245_pipex_var [32];
	ap_uint<32> gen246_pipex_var;
	ap_uint<32> gen247_pipex_var [32];
	ap_uint<32> gen248_pipex_var;
	ap_uint<1> gen249_pipex_var;
	ap_uint<1> gen250_pipex_var;
	ap_uint<1> gen251_pipex_var;
	ap_uint<1> gen252_pipex_var;
	ap_uint<1> gen253_pipex_var;
	ap_uint<1> gen254_pipex_var;
	ap_uint<33> gen255_pipex_var;
	ap_uint<33> gen256_pipex_var;
	ap_uint<1> gen257_pipex_var;
	ap_uint<1> gen258_pipex_var;
	ap_uint<33> gen259_pipex_var;
	ap_uint<1> gen260_pipex_var;
	ap_uint<33> gen261_pipex_var;
	ap_uint<1> gen262_pipex_var;
	ap_uint<1> gen263_pipex_var;
	ap_uint<1> gen264_pipex_var;
	ap_uint<1> gen265_pipex_var;
	ap_uint<1> gen266_pipex_var;
	ap_uint<1> gen267_pipex_var;
	ap_uint<1> gen268_pipex_var;
	ap_uint<34> gen269_pipex_var;
	ap_uint<34> gen270_pipex_var;
	ap_uint<33> gen271_pipex_var;
	ap_uint<33> gen272_pipex_var;
	ap_uint<33> gen273_pipex_var;
	ap_uint<32> gen274_pipex_var;
	ap_uint<64> gen275_pipex_var;
	ap_uint<5> gen276_pipex_var;
	ap_uint<64> gen277_pipex_var;
	ap_uint<32> gen278_pipex_var;
	ap_uint<1> gen279_pipex_var;
	ap_uint<64> gen280_pipex_var;
	ap_uint<5> gen281_pipex_var;
	ap_uint<64> gen282_pipex_var;
	ap_uint<33> gen283_pipex_var;
	ap_uint<33> gen284_pipex_var;
	ap_uint<33> gen285_pipex_var;
	ap_uint<32> gen286_pipex_var;
	ap_uint<1> gen287_pipex_var;
	ap_uint<1> gen288_pipex_var;
	ap_uint<1> gen289_pipex_var;
	ap_uint<1> gen290_pipex_var;
	ap_uint<1> gen291_pipex_var;
	ap_uint<1> gen292_pipex_var;
	ap_uint<1> gen293_pipex_var;
	ap_uint<1> gen294_pipex_var;
	ap_uint<1> gen295_pipex_var;
	ap_uint<1> gen296_pipex_var;
	ap_uint<1> gen297_pipex_var;
	ap_uint<1> gen298_pipex_var;
	ap_uint<1> gen299_pipex_var;
	ap_uint<1> gen300_pipex_var;
	ap_uint<1> gen301_pipex_var;
	ap_uint<1> gen302_pipex_var;
	ap_uint<1> gen303_pipex_var;
	ap_uint<1> gen304_pipex_var;
	ap_uint<1> gen305_pipex_var;
	ap_uint<1> gen306_pipex_var;
	ap_uint<33> gen307_pipex_var;
	ap_uint<1> gen308_pipex_var;
	ap_uint<1> gen309_pipex_var;
	ap_uint<1> gen310_pipex_var;
	ap_uint<1> gen311_pipex_var;
	ap_uint<1> gen312_pipex_var;
	ap_uint<1> gen313_pipex_var;
	ap_uint<1> gen314_pipex_var;
	ap_uint<1> gen315_pipex_var;
	ap_uint<1> gen316_pipex_var;
	ap_uint<1> gen317_pipex_var;
	ap_uint<1> gen318_pipex_var;
	ap_uint<1> gen319_pipex_var;
	ap_uint<1> gen320_pipex_var;
	ap_uint<1> gen321_pipex_var;
	ap_uint<1> gen322_pipex_var;
	ap_uint<1> gen323_pipex_var;
	ap_uint<1> gen324_pipex_var;
	ap_uint<1> gen325_pipex_var;
	ap_uint<1> gen326_pipex_var;
	ap_uint<1> gen327_pipex_var;
	ap_uint<1> gen328_pipex_var;
	ap_uint<1> gen329_pipex_var;
	ap_uint<1> gen330_pipex_var;
	ap_uint<1> gen331_pipex_var;
	ap_uint<1> gen332_pipex_var;
	ap_uint<1> gen333_pipex_var;
	ap_uint<32> genpstage_IFETCH_curinstr_addr;
	ap_uint<32> genpstage_IFETCH_nextinstr_addr;
	riscv_2stage_busreq_mem_struct genpstage_IFETCH_instr_busreq;
	ap_uint<32> genpstage_EXEC_instr_code;
	ap_uint<7> genpstage_EXEC_opcode;
	ap_uint<1> genpstage_EXEC_alu_unsigned;
	ap_uint<5> genpstage_EXEC_rs1_addr;
	ap_uint<5> genpstage_EXEC_rs2_addr;
	ap_uint<5> genpstage_EXEC_rd_addr;
	ap_uint<3> genpstage_EXEC_funct3;
	ap_uint<7> genpstage_EXEC_funct7;
	ap_uint<5> genpstage_EXEC_shamt;
	ap_uint<4> genpstage_EXEC_pred;
	ap_uint<4> genpstage_EXEC_succ;
	ap_uint<12> genpstage_EXEC_csrnum;
	ap_uint<5> genpstage_EXEC_zimm;
	ap_uint<32> genpstage_EXEC_immediate_I;
	ap_uint<32> genpstage_EXEC_immediate_S;
	ap_uint<32> genpstage_EXEC_immediate_B;
	ap_uint<32> genpstage_EXEC_immediate_U;
	ap_uint<32> genpstage_EXEC_immediate_J;
	ap_uint<2> genpstage_EXEC_op1_source;
	ap_uint<1> genpstage_EXEC_rd_req;
	ap_uint<3> genpstage_EXEC_rd_source;
	ap_uint<32> genpstage_EXEC_immediate;
	ap_uint<2> genpstage_EXEC_op2_source;
	ap_uint<1> genpstage_EXEC_alu_req;
	ap_uint<4> genpstage_EXEC_alu_opcode;
	ap_uint<1> genpstage_EXEC_jump_req;
	ap_uint<1> genpstage_EXEC_jump_src;
	ap_uint<1> genpstage_EXEC_rs1_req;
	ap_uint<1> genpstage_EXEC_rs2_req;
	ap_uint<1> genpstage_EXEC_jump_req_cond;
	ap_uint<1> genpstage_EXEC_mem_req;
	ap_uint<1> genpstage_EXEC_mem_cmd;
	ap_uint<1> genpstage_EXEC_fencereq;
	ap_uint<1> genpstage_EXEC_ebreakreq;
	ap_uint<1> genpstage_EXEC_ecallreq;
	ap_uint<1> genpstage_EXEC_csrreq;
	ap_uint<4> genpstage_EXEC_mem_be;
	ap_uint<1> genpstage_EXEC_mret_req;
	ap_uint<32> genpstage_EXEC_csr_rdata;
	ap_uint<32> genpstage_EXEC_alu_op1;
	ap_uint<32> genpstage_EXEC_alu_op2;
	ap_uint<33> genpstage_EXEC_alu_op1_wide;
	ap_uint<33> genpstage_EXEC_alu_op2_wide;
	ap_uint<33> genpstage_EXEC_alu_result_wide;
	ap_uint<32> genpstage_EXEC_alu_result;
	ap_uint<1> genpstage_EXEC_alu_CF;
	ap_uint<1> genpstage_EXEC_alu_SF;
	ap_uint<1> genpstage_EXEC_alu_ZF;
	ap_uint<1> genpstage_EXEC_alu_OF;
	ap_uint<1> genpstage_EXEC_alu_overflow;
	ap_uint<32> genpstage_EXEC_rd_wdata;
	ap_uint<1> genpstage_EXEC_rd_rdy;
	ap_uint<32> genpstage_EXEC_curinstraddr_imm;
	ap_uint<32> genpstage_EXEC_jump_vector;
	ap_uint<32> genpstage_EXEC_mem_addr;
	ap_uint<32> genpstage_EXEC_mem_wdata;
	riscv_2stage_busreq_mem_struct genpstage_EXEC_data_busreq;
	ap_uint<32> genpstage_EXEC_mem_rdata;
	ap_uint<32> genpstage_EXEC_curinstr_addr;
	ap_uint<32> genpstage_EXEC_nextinstr_addr;
	ap_uint<32> gen334_pipex_mcopipe_rdata;
	ap_uint<32> gen335_pipex_mcopipe_rdata;
	ap_uint<1> gen336_pipex_genpstage_EXEC_mcopipe_rdreq_inprogress;
	genpmodule_riscv_2stage_genmcopipe_data_mem_genstruct_fifo_wdata gen337_pipex_req_struct;
	ap_uint<32> gen338_pipex_mcopipe_rdata;
	ap_uint<1> gen339_pipex_genpstage_IFETCH_mcopipe_rdreq_inprogress;
	genpmodule_riscv_2stage_genmcopipe_instr_mem_genstruct_fifo_wdata gen340_pipex_req_struct;
	ap_uint<32> gen303_cyclix_var;
	ap_uint<32> gen304_cyclix_var;
	ap_uint<32> gen305_cyclix_var;
	ap_uint<32> gen306_cyclix_var;
	ap_uint<32> gen307_cyclix_var;
	ap_uint<32> gen308_cyclix_var;
	ap_uint<32> gen309_cyclix_var;
	ap_uint<32> gen310_cyclix_var;
	ap_uint<32> gen311_cyclix_var;
	ap_uint<32> gen312_cyclix_var;
	ap_uint<32> gen313_cyclix_var;
	ap_uint<32> gen314_cyclix_var;
	ap_uint<32> gen315_cyclix_var;
	ap_uint<32> gen316_cyclix_var;
	ap_uint<32> gen317_cyclix_var;
	ap_uint<32> gen318_cyclix_var;
	ap_uint<32> gen319_cyclix_var;
	ap_uint<32> gen320_cyclix_var;
	ap_uint<32> gen321_cyclix_var;
	ap_uint<32> gen322_cyclix_var;
	ap_uint<32> gen323_cyclix_var;
	ap_uint<32> gen324_cyclix_var;
	ap_uint<32> gen325_cyclix_var;
	ap_uint<32> gen326_cyclix_var;
	ap_uint<32> gen327_cyclix_var;
	ap_uint<32> gen328_cyclix_var;
	ap_uint<32> gen329_cyclix_var;
	ap_uint<32> gen330_cyclix_var;
	ap_uint<32> gen331_cyclix_var;
	ap_uint<32> gen332_cyclix_var;
	ap_uint<32> gen333_cyclix_var;
	ap_uint<1> gen334_cyclix_var;
	ap_uint<1> gen335_cyclix_var;
	ap_uint<1> gen336_cyclix_var;
	ap_uint<1> gen337_cyclix_var;
	ap_uint<1> gen338_cyclix_var;
	ap_uint<1> gen339_cyclix_var;
	ap_uint<1> gen340_cyclix_var;
	ap_uint<1> gen341_cyclix_var;
	ap_uint<1> gen342_cyclix_var;
	ap_uint<1> gen343_cyclix_var;
	ap_uint<1> gen344_cyclix_var;
	ap_uint<1> gen345_cyclix_var;
	ap_uint<1> gen346_cyclix_var;
	ap_uint<1> gen347_cyclix_var;
	ap_uint<1> gen348_cyclix_var;
	ap_uint<1> gen349_cyclix_var;
	ap_uint<1> gen350_cyclix_var;
	ap_uint<1> gen351_cyclix_var;
	ap_uint<1> gen352_cyclix_var;
	ap_uint<1> gen353_cyclix_var;
	ap_uint<1> gen354_cyclix_var;
	ap_uint<1> gen355_cyclix_var;
	ap_uint<32> gen356_cyclix_var;
	ap_uint<32> gen357_cyclix_var;
	ap_uint<32> gen358_cyclix_var;
	ap_uint<32> gen359_cyclix_var;
	ap_uint<32> gen360_cyclix_var;
	ap_uint<32> gen361_cyclix_var;
	ap_uint<32> gen362_cyclix_var;
	ap_uint<32> gen363_cyclix_var;
	ap_uint<32> gen364_cyclix_var;
	ap_uint<32> gen365_cyclix_var;
	ap_uint<32> gen366_cyclix_var;
	ap_uint<32> gen367_cyclix_var;
	ap_uint<32> gen368_cyclix_var;
	ap_uint<32> gen369_cyclix_var;
	ap_uint<32> gen370_cyclix_var;
	ap_uint<32> gen371_cyclix_var;
	ap_uint<32> gen372_cyclix_var;
	ap_uint<32> gen373_cyclix_var;
	ap_uint<32> gen374_cyclix_var;
	ap_uint<32> gen375_cyclix_var;
	ap_uint<32> gen376_cyclix_var;
	ap_uint<32> gen377_cyclix_var;
	ap_uint<32> gen378_cyclix_var;
	ap_uint<32> gen379_cyclix_var;
	ap_uint<32> gen380_cyclix_var;
	ap_uint<32> gen381_cyclix_var;
	ap_uint<32> gen382_cyclix_var;
	ap_uint<32> gen383_cyclix_var;
	ap_uint<32> gen384_cyclix_var;
	ap_uint<32> gen385_cyclix_var;
	ap_uint<32> gen386_cyclix_var;
	ap_uint<1> gen387_cyclix_var;
	ap_uint<1> gen388_cyclix_var;
	ap_uint<1> gen389_cyclix_var;
	ap_uint<1> gen390_cyclix_var;
	ap_uint<1> gen391_cyclix_var;
	ap_uint<1> gen392_cyclix_var;
	ap_uint<1> gen393_cyclix_var;
	ap_uint<1> gen394_cyclix_var;
	ap_uint<1> gen395_cyclix_var;
	ap_uint<1> gen396_cyclix_var;
	ap_uint<1> gen397_cyclix_var;
	ap_uint<1> gen398_cyclix_var;
	ap_uint<1> gen399_cyclix_var;
	ap_uint<1> gen400_cyclix_var;
	ap_uint<32> gen401_cyclix_var;
	ap_uint<32> gen402_cyclix_var;
	ap_uint<32> gen403_cyclix_var;
	ap_uint<32> gen404_cyclix_var;
	ap_uint<32> gen405_cyclix_var;
	ap_uint<32> gen406_cyclix_var;
	ap_uint<32> gen407_cyclix_var;
	ap_uint<32> gen408_cyclix_var;
	ap_uint<32> gen409_cyclix_var;
	ap_uint<32> gen410_cyclix_var;
	ap_uint<32> gen411_cyclix_var;
	ap_uint<32> gen412_cyclix_var;
	ap_uint<32> gen413_cyclix_var;
	ap_uint<32> gen414_cyclix_var;
	ap_uint<32> gen415_cyclix_var;
	ap_uint<32> gen416_cyclix_var;
	ap_uint<32> gen417_cyclix_var;
	ap_uint<32> gen418_cyclix_var;
	ap_uint<32> gen419_cyclix_var;
	ap_uint<32> gen420_cyclix_var;
	ap_uint<32> gen421_cyclix_var;
	ap_uint<32> gen422_cyclix_var;
	ap_uint<32> gen423_cyclix_var;
	ap_uint<32> gen424_cyclix_var;
	ap_uint<32> gen425_cyclix_var;
	ap_uint<32> gen426_cyclix_var;
	ap_uint<32> gen427_cyclix_var;
	ap_uint<32> gen428_cyclix_var;
	ap_uint<32> gen429_cyclix_var;
	ap_uint<32> gen430_cyclix_var;
	ap_uint<32> gen431_cyclix_var;
	ap_uint<32> gen432_cyclix_var;
	ap_uint<32> gen433_cyclix_var;
	ap_uint<32> gen434_cyclix_var;
	ap_uint<32> gen435_cyclix_var;
	ap_uint<32> gen436_cyclix_var;
	ap_uint<32> gen437_cyclix_var;
	ap_uint<32> gen438_cyclix_var;
	ap_uint<32> gen439_cyclix_var;
	ap_uint<32> gen440_cyclix_var;
	ap_uint<32> gen441_cyclix_var;
	ap_uint<32> gen442_cyclix_var;
	ap_uint<32> gen443_cyclix_var;
	ap_uint<32> gen444_cyclix_var;
	ap_uint<32> gen445_cyclix_var;
	ap_uint<32> gen446_cyclix_var;
	ap_uint<32> gen447_cyclix_var;
	ap_uint<32> gen448_cyclix_var;
	ap_uint<32> gen449_cyclix_var;
	ap_uint<32> gen450_cyclix_var;
	ap_uint<32> gen451_cyclix_var;
	ap_uint<32> gen452_cyclix_var;
	ap_uint<32> gen453_cyclix_var;
	ap_uint<32> gen454_cyclix_var;
	ap_uint<32> gen455_cyclix_var;
	ap_uint<32> gen456_cyclix_var;
	ap_uint<32> gen457_cyclix_var;
	ap_uint<32> gen458_cyclix_var;
	ap_uint<32> gen459_cyclix_var;
	ap_uint<32> gen460_cyclix_var;
	ap_uint<32> gen461_cyclix_var;
	ap_uint<32> gen462_cyclix_var;
	ap_uint<1> gen463_cyclix_var;
	ap_uint<1> gen464_cyclix_var;
	ap_uint<1> gen465_cyclix_var;
	ap_uint<1> gen466_cyclix_var;
	ap_uint<1> gen467_cyclix_var;
	ap_uint<1> gen468_cyclix_var;
	ap_uint<1> gen469_cyclix_var;
	ap_uint<1> gen470_cyclix_var;
	ap_uint<1> gen471_cyclix_var;
	ap_uint<1> gen472_cyclix_var;
	ap_uint<1> gen473_cyclix_var;
	ap_uint<1> gen474_cyclix_var;
	ap_uint<1> gen475_cyclix_var;
	ap_uint<1> gen476_cyclix_var;
	ap_uint<1> gen477_cyclix_var;
	ap_uint<1> gen478_cyclix_var;
	ap_uint<1> gen479_cyclix_var;
	ap_uint<1> gen480_cyclix_var;
	ap_uint<1> gen481_cyclix_var;
	ap_uint<1> gen482_cyclix_var;
	ap_uint<1> gen483_cyclix_var;
	ap_uint<1> gen484_cyclix_var;
	ap_uint<1> gen485_cyclix_var;
	ap_uint<1> gen486_cyclix_var;
	ap_uint<1> gen487_cyclix_var;
	ap_uint<1> gen488_cyclix_var;
	ap_uint<1> gen489_cyclix_var;
	ap_uint<1> gen490_cyclix_var;
	ap_uint<1> gen491_cyclix_var;
	ap_uint<1> gen492_cyclix_var;
	ap_uint<1> gen493_cyclix_var;
	ap_uint<1> gen494_cyclix_var;
	ap_uint<1> gen495_cyclix_var;
	ap_uint<1> gen496_cyclix_var;
	ap_uint<1> gen497_cyclix_var;
	ap_uint<1> gen498_cyclix_var;
	ap_uint<1> gen499_cyclix_var;
	ap_uint<1> gen500_cyclix_var;
	ap_uint<1> gen501_cyclix_var;
	ap_uint<1> gen502_cyclix_var;
	ap_uint<1> gen503_cyclix_var;
	ap_uint<1> gen504_cyclix_var;
	ap_uint<1> gen505_cyclix_var;
	ap_uint<1> gen506_cyclix_var;
	ap_uint<1> gen507_cyclix_var;
	ap_uint<1> gen508_cyclix_var;
	ap_uint<1> gen509_cyclix_var;
	ap_uint<1> gen510_cyclix_var;
	ap_uint<1> gen511_cyclix_var;
	ap_uint<1> gen512_cyclix_var;
	ap_uint<1> gen513_cyclix_var;
	ap_uint<1> gen514_cyclix_var;
	ap_uint<1> gen515_cyclix_var;
	ap_uint<1> gen516_cyclix_var;
	ap_uint<1> gen517_cyclix_var;
	ap_uint<1> gen518_cyclix_var;
	ap_uint<1> gen519_cyclix_var;
	ap_uint<32> gen520_cyclix_var;
	ap_uint<32> gen521_cyclix_var;
	ap_uint<32> gen522_cyclix_var;
	ap_uint<32> gen523_cyclix_var;
	ap_uint<32> gen524_cyclix_var;
	ap_uint<32> gen525_cyclix_var;
	ap_uint<32> gen526_cyclix_var;
	ap_uint<32> gen527_cyclix_var;
	ap_uint<32> gen528_cyclix_var;
	ap_uint<32> gen529_cyclix_var;
	ap_uint<32> gen530_cyclix_var;
	ap_uint<32> gen531_cyclix_var;
	ap_uint<32> gen532_cyclix_var;
	ap_uint<32> gen533_cyclix_var;
	ap_uint<32> gen534_cyclix_var;
	ap_uint<32> gen535_cyclix_var;
	ap_uint<32> gen536_cyclix_var;
	ap_uint<32> gen537_cyclix_var;
	ap_uint<32> gen538_cyclix_var;
	ap_uint<32> gen539_cyclix_var;
	ap_uint<32> gen540_cyclix_var;
	ap_uint<32> gen541_cyclix_var;
	ap_uint<32> gen542_cyclix_var;
	ap_uint<32> gen543_cyclix_var;
	ap_uint<32> gen544_cyclix_var;
	ap_uint<32> gen545_cyclix_var;
	ap_uint<32> gen546_cyclix_var;
	ap_uint<32> gen547_cyclix_var;
	ap_uint<32> gen548_cyclix_var;
	ap_uint<32> gen549_cyclix_var;
	ap_uint<32> gen550_cyclix_var;
	ap_uint<1> gen551_cyclix_var;
	ap_uint<1> gen552_cyclix_var;
	ap_uint<1> gen553_cyclix_var;
	ap_uint<1> gen554_cyclix_var;
	ap_uint<1> gen555_cyclix_var;
	ap_uint<1> gen556_cyclix_var;
	ap_uint<1> gen557_cyclix_var;
	ap_uint<1> gen558_cyclix_var;
	ap_uint<1> gen559_cyclix_var;
	ap_uint<1> gen560_cyclix_var;
	ap_uint<1> gen561_cyclix_var;
	ap_uint<1> gen562_cyclix_var;
	ap_uint<1> gen563_cyclix_var;
	ap_uint<1> gen564_cyclix_var;
	ap_uint<1> gen565_cyclix_var;
	ap_uint<1> gen566_cyclix_var;
	ap_uint<1> gen567_cyclix_var;
	ap_uint<1> gen568_cyclix_var;
	ap_uint<1> gen569_cyclix_var;
	ap_uint<1> gen570_cyclix_var;
	ap_uint<1> gen571_cyclix_var;
	ap_uint<1> gen572_cyclix_var;
	ap_uint<1> gen573_cyclix_var;
	ap_uint<1> gen574_cyclix_var;
	ap_uint<1> gen575_cyclix_var;
	ap_uint<1> gen576_cyclix_var;
	ap_uint<1> gen577_cyclix_var;
	ap_uint<1> gen578_cyclix_var;
	ap_uint<1> gen579_cyclix_var;
	ap_uint<1> gen580_cyclix_var;
	ap_uint<1> gen581_cyclix_var;
	ap_uint<1> gen582_cyclix_var;
	ap_uint<1> gen583_cyclix_var;
	ap_uint<1> gen584_cyclix_var;
	ap_uint<1> gen585_cyclix_var;
	ap_uint<1> gen586_cyclix_var;
	ap_uint<1> gen587_cyclix_var;
	ap_uint<1> gen588_cyclix_var;
	ap_uint<1> gen589_cyclix_var;
	ap_uint<1> gen590_cyclix_var;
	ap_uint<1> gen591_cyclix_var;
	ap_uint<1> gen592_cyclix_var;
	ap_uint<1> gen593_cyclix_var;
	ap_uint<1> gen594_cyclix_var;
	ap_uint<1> gen595_cyclix_var;
	ap_uint<1> gen596_cyclix_var;
	ap_uint<1> gen597_cyclix_var;
	ap_uint<1> gen598_cyclix_var;
	ap_uint<1> gen599_cyclix_var;
	ap_uint<1> gen600_cyclix_var;
	ap_uint<1> gen601_cyclix_var;
	ap_uint<1> gen602_cyclix_var;
	ap_uint<1> gen603_cyclix_var;
	ap_uint<1> gen604_cyclix_var;
	ap_uint<1> gen605_cyclix_var;

	if (geninit) {
		genpsticky_glbl_pc = 512;
		genpsticky_glbl_regfile[1] = 0;
		genpsticky_glbl_regfile[2] = 0;
		genpsticky_glbl_regfile[3] = 0;
		genpsticky_glbl_regfile[4] = 0;
		genpsticky_glbl_regfile[5] = 0;
		genpsticky_glbl_regfile[6] = 0;
		genpsticky_glbl_regfile[7] = 0;
		genpsticky_glbl_regfile[8] = 0;
		genpsticky_glbl_regfile[9] = 0;
		genpsticky_glbl_regfile[10] = 0;
		genpsticky_glbl_regfile[11] = 0;
		genpsticky_glbl_regfile[12] = 0;
		genpsticky_glbl_regfile[13] = 0;
		genpsticky_glbl_regfile[14] = 0;
		genpsticky_glbl_regfile[15] = 0;
		genpsticky_glbl_regfile[16] = 0;
		genpsticky_glbl_regfile[17] = 0;
		genpsticky_glbl_regfile[18] = 0;
		genpsticky_glbl_regfile[19] = 0;
		genpsticky_glbl_regfile[20] = 0;
		genpsticky_glbl_regfile[21] = 0;
		genpsticky_glbl_regfile[22] = 0;
		genpsticky_glbl_regfile[23] = 0;
		genpsticky_glbl_regfile[24] = 0;
		genpsticky_glbl_regfile[25] = 0;
		genpsticky_glbl_regfile[26] = 0;
		genpsticky_glbl_regfile[27] = 0;
		genpsticky_glbl_regfile[28] = 0;
		genpsticky_glbl_regfile[29] = 0;
		genpsticky_glbl_regfile[30] = 0;
		genpsticky_glbl_regfile[31] = 0;
		genpsticky_glbl_jump_req_cmd = 0;
		genpsticky_glbl_jump_vector_cmd = 0;
		genpsticky_glbl_CSR_MCAUSE = 0;
		genpsticky_glbl_MIRQEN = 1;
		genpsticky_glbl_MRETADDR = 0;
		genmcopipe_instr_mem_wr_done = 0;
		genmcopipe_instr_mem_rd_done = 0;
		genmcopipe_instr_mem_full_flag = 0;
		genmcopipe_instr_mem_empty_flag = 1;
		genmcopipe_instr_mem_wr_ptr = 0;
		genmcopipe_instr_mem_rd_ptr = 0;
		genmcopipe_data_mem_wr_done = 0;
		genmcopipe_data_mem_rd_done = 0;
		genmcopipe_data_mem_full_flag = 0;
		genmcopipe_data_mem_empty_flag = 1;
		genmcopipe_data_mem_wr_ptr = 0;
		genmcopipe_data_mem_rd_ptr = 0;
		genpstage_IFETCH_genpctrl_active_glbl = 0;
		genpstage_IFETCH_genpctrl_stalled_glbl = 0;
		genpstage_IFETCH_genpctrl_killed_glbl = 0;
		genpstage_EXEC_genpctrl_active_glbl = 0;
		genpstage_EXEC_genpctrl_stalled_glbl = 0;
		genpstage_EXEC_genpctrl_killed_glbl = 0;
		genpstage_IFETCH_instr_req_done = 0;
		genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_if_id = 0;
		genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_rdreq_pending = 0;
		genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_tid = 0;
		genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_resp_done = 0;
		genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_rdata = 0;
		genpstage_EXEC_rs1_rdata = 0;
		genpstage_EXEC_rs2_rdata = 0;
		genpstage_EXEC_irq_mcause = 0;
		genpstage_EXEC_irq_recv = 0;
		genpstage_EXEC_data_req_done = 0;
		genpstage_EXEC_genmcopipe_handle_data_mem_genvar_if_id = 0;
		genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdreq_pending = 0;
		genpstage_EXEC_genmcopipe_handle_data_mem_genvar_tid = 0;
		genpstage_EXEC_genmcopipe_handle_data_mem_genvar_resp_done = 0;
		genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdata = 0;
		genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_if_id = 0;
		genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdreq_pending = 0;
		genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_tid = 0;
		genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_resp_done = 0;
		genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdata = 0;
		genpstage_EXEC_curinstr_addr_genglbl = 0;
		genpstage_EXEC_nextinstr_addr_genglbl = 0;

	} else {
		genmcopipe_instr_mem_wr_done = ap_uint<32>(0);
		genmcopipe_instr_mem_rd_done = ap_uint<32>(0);
		genmcopipe_instr_mem_wr_ptr_next = (genmcopipe_instr_mem_wr_ptr + ap_uint<32>(1));
		genmcopipe_instr_mem_rd_ptr_next = (genmcopipe_instr_mem_rd_ptr + ap_uint<32>(1));
		genmcopipe_data_mem_wr_done = ap_uint<32>(0);
		genmcopipe_data_mem_rd_done = ap_uint<32>(0);
		genmcopipe_data_mem_wr_ptr_next = (genmcopipe_data_mem_wr_ptr + ap_uint<32>(1));
		genmcopipe_data_mem_rd_ptr_next = (genmcopipe_data_mem_rd_ptr + ap_uint<32>(1));
		genpsticky_glbl_pc_buf = genpsticky_glbl_pc;
		gen303_cyclix_var = genpsticky_glbl_regfile[1];
		genpsticky_glbl_regfile_buf[1] = gen303_cyclix_var;
		gen304_cyclix_var = genpsticky_glbl_regfile[2];
		genpsticky_glbl_regfile_buf[2] = gen304_cyclix_var;
		gen305_cyclix_var = genpsticky_glbl_regfile[3];
		genpsticky_glbl_regfile_buf[3] = gen305_cyclix_var;
		gen306_cyclix_var = genpsticky_glbl_regfile[4];
		genpsticky_glbl_regfile_buf[4] = gen306_cyclix_var;
		gen307_cyclix_var = genpsticky_glbl_regfile[5];
		genpsticky_glbl_regfile_buf[5] = gen307_cyclix_var;
		gen308_cyclix_var = genpsticky_glbl_regfile[6];
		genpsticky_glbl_regfile_buf[6] = gen308_cyclix_var;
		gen309_cyclix_var = genpsticky_glbl_regfile[7];
		genpsticky_glbl_regfile_buf[7] = gen309_cyclix_var;
		gen310_cyclix_var = genpsticky_glbl_regfile[8];
		genpsticky_glbl_regfile_buf[8] = gen310_cyclix_var;
		gen311_cyclix_var = genpsticky_glbl_regfile[9];
		genpsticky_glbl_regfile_buf[9] = gen311_cyclix_var;
		gen312_cyclix_var = genpsticky_glbl_regfile[10];
		genpsticky_glbl_regfile_buf[10] = gen312_cyclix_var;
		gen313_cyclix_var = genpsticky_glbl_regfile[11];
		genpsticky_glbl_regfile_buf[11] = gen313_cyclix_var;
		gen314_cyclix_var = genpsticky_glbl_regfile[12];
		genpsticky_glbl_regfile_buf[12] = gen314_cyclix_var;
		gen315_cyclix_var = genpsticky_glbl_regfile[13];
		genpsticky_glbl_regfile_buf[13] = gen315_cyclix_var;
		gen316_cyclix_var = genpsticky_glbl_regfile[14];
		genpsticky_glbl_regfile_buf[14] = gen316_cyclix_var;
		gen317_cyclix_var = genpsticky_glbl_regfile[15];
		genpsticky_glbl_regfile_buf[15] = gen317_cyclix_var;
		gen318_cyclix_var = genpsticky_glbl_regfile[16];
		genpsticky_glbl_regfile_buf[16] = gen318_cyclix_var;
		gen319_cyclix_var = genpsticky_glbl_regfile[17];
		genpsticky_glbl_regfile_buf[17] = gen319_cyclix_var;
		gen320_cyclix_var = genpsticky_glbl_regfile[18];
		genpsticky_glbl_regfile_buf[18] = gen320_cyclix_var;
		gen321_cyclix_var = genpsticky_glbl_regfile[19];
		genpsticky_glbl_regfile_buf[19] = gen321_cyclix_var;
		gen322_cyclix_var = genpsticky_glbl_regfile[20];
		genpsticky_glbl_regfile_buf[20] = gen322_cyclix_var;
		gen323_cyclix_var = genpsticky_glbl_regfile[21];
		genpsticky_glbl_regfile_buf[21] = gen323_cyclix_var;
		gen324_cyclix_var = genpsticky_glbl_regfile[22];
		genpsticky_glbl_regfile_buf[22] = gen324_cyclix_var;
		gen325_cyclix_var = genpsticky_glbl_regfile[23];
		genpsticky_glbl_regfile_buf[23] = gen325_cyclix_var;
		gen326_cyclix_var = genpsticky_glbl_regfile[24];
		genpsticky_glbl_regfile_buf[24] = gen326_cyclix_var;
		gen327_cyclix_var = genpsticky_glbl_regfile[25];
		genpsticky_glbl_regfile_buf[25] = gen327_cyclix_var;
		gen328_cyclix_var = genpsticky_glbl_regfile[26];
		genpsticky_glbl_regfile_buf[26] = gen328_cyclix_var;
		gen329_cyclix_var = genpsticky_glbl_regfile[27];
		genpsticky_glbl_regfile_buf[27] = gen329_cyclix_var;
		gen330_cyclix_var = genpsticky_glbl_regfile[28];
		genpsticky_glbl_regfile_buf[28] = gen330_cyclix_var;
		gen331_cyclix_var = genpsticky_glbl_regfile[29];
		genpsticky_glbl_regfile_buf[29] = gen331_cyclix_var;
		gen332_cyclix_var = genpsticky_glbl_regfile[30];
		genpsticky_glbl_regfile_buf[30] = gen332_cyclix_var;
		gen333_cyclix_var = genpsticky_glbl_regfile[31];
		genpsticky_glbl_regfile_buf[31] = gen333_cyclix_var;
		genpsticky_glbl_jump_req_cmd_buf = genpsticky_glbl_jump_req_cmd;
		genpsticky_glbl_jump_vector_cmd_buf = genpsticky_glbl_jump_vector_cmd;
		genpsticky_glbl_CSR_MCAUSE_buf = genpsticky_glbl_CSR_MCAUSE;
		genpsticky_glbl_MIRQEN_buf = genpsticky_glbl_MIRQEN;
		genpsticky_glbl_MRETADDR_buf = genpsticky_glbl_MRETADDR;
		genpstage_EXEC_genpctrl_succ = ap_uint<32>(0);
		genpstage_EXEC_genpctrl_working = ap_uint<32>(0);
		gen334_cyclix_var = genpstage_EXEC_genpctrl_stalled_glbl;
		if (gen334_cyclix_var) {
			genpstage_EXEC_genpctrl_new = ap_uint<32>(0);
			genpstage_EXEC_genpctrl_stalled_glbl = ap_uint<32>(0);
			gen335_cyclix_var = !genpstage_EXEC_genpctrl_killed_glbl;
			genpstage_EXEC_genpctrl_active_glbl = gen335_cyclix_var;
		}
		gen336_cyclix_var = ap_uint<1>(0);
		gen336_cyclix_var = (gen336_cyclix_var || gen334_cyclix_var);
		gen336_cyclix_var = !gen336_cyclix_var;
		if (gen336_cyclix_var) {
			genpstage_EXEC_genpctrl_new = (genpstage_EXEC_genpctrl_active_glbl || genpstage_EXEC_genpctrl_killed_glbl);
		}
		genpstage_EXEC_genpctrl_finish = ap_uint<32>(0);
		genpstage_EXEC_genpctrl_flushreq = ap_uint<32>(0);
		genpstage_EXEC_genpctrl_nevictable = ap_uint<32>(0);
		genpstage_EXEC_genpctrl_occupied = (genpstage_EXEC_genpctrl_active_glbl | genpstage_EXEC_genpctrl_killed_glbl);
		genpstage_EXEC_curinstr_addr = genpstage_EXEC_curinstr_addr_genglbl;
		genpstage_EXEC_nextinstr_addr = genpstage_EXEC_nextinstr_addr_genglbl;
		gen337_cyclix_var = genpstage_EXEC_genpctrl_occupied;
		if (gen337_cyclix_var) {
			gen338_cyclix_var = genpstage_EXEC_genpctrl_new;
			if (gen338_cyclix_var) {
				genpstage_EXEC_rs1_rdata = ap_uint<32>(0);
				genpstage_EXEC_rs2_rdata = ap_uint<32>(0);
				genpstage_EXEC_irq_mcause = ap_uint<32>(0);
				genpstage_EXEC_irq_recv = ap_uint<32>(0);
				genpstage_EXEC_data_req_done = ap_uint<32>(0);
				genpstage_EXEC_genmcopipe_handle_data_mem_genvar_if_id = ap_uint<32>(0);
				genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdreq_pending = ap_uint<32>(0);
				genpstage_EXEC_genmcopipe_handle_data_mem_genvar_tid = ap_uint<32>(0);
				genpstage_EXEC_genmcopipe_handle_data_mem_genvar_resp_done = ap_uint<32>(0);
				genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdata = ap_uint<32>(0);
			}
			gen339_cyclix_var = genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdreq_pending;
			if (gen339_cyclix_var) {
				gen340_cyclix_var = (genpstage_EXEC_genmcopipe_handle_data_mem_genvar_if_id == ap_uint<1>(0));
				gen341_cyclix_var = gen340_cyclix_var;
				if (gen341_cyclix_var) {
					gen342_cyclix_var = (genpstage_EXEC_genmcopipe_handle_data_mem_genvar_tid == genmcopipe_data_mem_rd_ptr);
					gen343_cyclix_var = gen342_cyclix_var;
					if (gen343_cyclix_var) {
						gen344_cyclix_var = genmcopipe_data_mem_resp.read_nb(gen334_pipex_mcopipe_rdata);
						gen345_cyclix_var = gen344_cyclix_var;
						if (gen345_cyclix_var) {
							genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdreq_pending = ap_uint<32>(0);
							genpstage_EXEC_genmcopipe_handle_data_mem_genvar_resp_done = ap_uint<32>(1);
							genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdata = gen334_pipex_mcopipe_rdata;
							genmcopipe_data_mem_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			gen346_cyclix_var = genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdreq_pending;
			if (gen346_cyclix_var) {
				gen347_cyclix_var = (genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_if_id == ap_uint<1>(0));
				gen348_cyclix_var = gen347_cyclix_var;
				if (gen348_cyclix_var) {
					gen349_cyclix_var = (genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_tid == genmcopipe_instr_mem_rd_ptr);
					gen350_cyclix_var = gen349_cyclix_var;
					if (gen350_cyclix_var) {
						gen351_cyclix_var = genmcopipe_instr_mem_resp.read_nb(gen335_pipex_mcopipe_rdata);
						gen352_cyclix_var = gen351_cyclix_var;
						if (gen352_cyclix_var) {
							genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdreq_pending = ap_uint<32>(0);
							genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_resp_done = ap_uint<32>(1);
							genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdata = gen335_pipex_mcopipe_rdata;
							genmcopipe_instr_mem_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			gen336_pipex_genpstage_EXEC_mcopipe_rdreq_inprogress = ap_uint<32>(0);
			gen336_pipex_genpstage_EXEC_mcopipe_rdreq_inprogress = (gen336_pipex_genpstage_EXEC_mcopipe_rdreq_inprogress || genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdreq_pending);
			gen336_pipex_genpstage_EXEC_mcopipe_rdreq_inprogress = (gen336_pipex_genpstage_EXEC_mcopipe_rdreq_inprogress || genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdreq_pending);
			gen353_cyclix_var = genpstage_EXEC_genpctrl_flushreq;
			if (gen353_cyclix_var) {
				gen354_cyclix_var = genpstage_EXEC_genpctrl_active_glbl;
				if (gen354_cyclix_var) {
					genpstage_EXEC_genpctrl_active_glbl = ap_uint<32>(0);
					genpstage_EXEC_genpctrl_killed_glbl = ap_uint<32>(1);
				}
			}
		}
		gen355_cyclix_var = ap_uint<1>(0);
		gen355_cyclix_var = (gen355_cyclix_var || gen337_cyclix_var);
		gen355_cyclix_var = !gen355_cyclix_var;
		if (gen355_cyclix_var) {
			genpstage_EXEC_genmcopipe_handle_data_mem_genvar_resp_done = ap_uint<32>(0);
			genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdreq_pending = ap_uint<32>(0);
			genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_resp_done = ap_uint<32>(0);
			genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdreq_pending = ap_uint<32>(0);
		}
		gen167_pipex_syncbuf = genpsticky_glbl_jump_req_cmd;
		gen169_pipex_syncbuf = genpsticky_glbl_jump_vector_cmd;
		gen356_cyclix_var = genpsticky_glbl_regfile[1];
		gen171_pipex_syncbuf[1] = gen356_cyclix_var;
		gen357_cyclix_var = genpsticky_glbl_regfile[2];
		gen171_pipex_syncbuf[2] = gen357_cyclix_var;
		gen358_cyclix_var = genpsticky_glbl_regfile[3];
		gen171_pipex_syncbuf[3] = gen358_cyclix_var;
		gen359_cyclix_var = genpsticky_glbl_regfile[4];
		gen171_pipex_syncbuf[4] = gen359_cyclix_var;
		gen360_cyclix_var = genpsticky_glbl_regfile[5];
		gen171_pipex_syncbuf[5] = gen360_cyclix_var;
		gen361_cyclix_var = genpsticky_glbl_regfile[6];
		gen171_pipex_syncbuf[6] = gen361_cyclix_var;
		gen362_cyclix_var = genpsticky_glbl_regfile[7];
		gen171_pipex_syncbuf[7] = gen362_cyclix_var;
		gen363_cyclix_var = genpsticky_glbl_regfile[8];
		gen171_pipex_syncbuf[8] = gen363_cyclix_var;
		gen364_cyclix_var = genpsticky_glbl_regfile[9];
		gen171_pipex_syncbuf[9] = gen364_cyclix_var;
		gen365_cyclix_var = genpsticky_glbl_regfile[10];
		gen171_pipex_syncbuf[10] = gen365_cyclix_var;
		gen366_cyclix_var = genpsticky_glbl_regfile[11];
		gen171_pipex_syncbuf[11] = gen366_cyclix_var;
		gen367_cyclix_var = genpsticky_glbl_regfile[12];
		gen171_pipex_syncbuf[12] = gen367_cyclix_var;
		gen368_cyclix_var = genpsticky_glbl_regfile[13];
		gen171_pipex_syncbuf[13] = gen368_cyclix_var;
		gen369_cyclix_var = genpsticky_glbl_regfile[14];
		gen171_pipex_syncbuf[14] = gen369_cyclix_var;
		gen370_cyclix_var = genpsticky_glbl_regfile[15];
		gen171_pipex_syncbuf[15] = gen370_cyclix_var;
		gen371_cyclix_var = genpsticky_glbl_regfile[16];
		gen171_pipex_syncbuf[16] = gen371_cyclix_var;
		gen372_cyclix_var = genpsticky_glbl_regfile[17];
		gen171_pipex_syncbuf[17] = gen372_cyclix_var;
		gen373_cyclix_var = genpsticky_glbl_regfile[18];
		gen171_pipex_syncbuf[18] = gen373_cyclix_var;
		gen374_cyclix_var = genpsticky_glbl_regfile[19];
		gen171_pipex_syncbuf[19] = gen374_cyclix_var;
		gen375_cyclix_var = genpsticky_glbl_regfile[20];
		gen171_pipex_syncbuf[20] = gen375_cyclix_var;
		gen376_cyclix_var = genpsticky_glbl_regfile[21];
		gen171_pipex_syncbuf[21] = gen376_cyclix_var;
		gen377_cyclix_var = genpsticky_glbl_regfile[22];
		gen171_pipex_syncbuf[22] = gen377_cyclix_var;
		gen378_cyclix_var = genpsticky_glbl_regfile[23];
		gen171_pipex_syncbuf[23] = gen378_cyclix_var;
		gen379_cyclix_var = genpsticky_glbl_regfile[24];
		gen171_pipex_syncbuf[24] = gen379_cyclix_var;
		gen380_cyclix_var = genpsticky_glbl_regfile[25];
		gen171_pipex_syncbuf[25] = gen380_cyclix_var;
		gen381_cyclix_var = genpsticky_glbl_regfile[26];
		gen171_pipex_syncbuf[26] = gen381_cyclix_var;
		gen382_cyclix_var = genpsticky_glbl_regfile[27];
		gen171_pipex_syncbuf[27] = gen382_cyclix_var;
		gen383_cyclix_var = genpsticky_glbl_regfile[28];
		gen171_pipex_syncbuf[28] = gen383_cyclix_var;
		gen384_cyclix_var = genpsticky_glbl_regfile[29];
		gen171_pipex_syncbuf[29] = gen384_cyclix_var;
		gen385_cyclix_var = genpsticky_glbl_regfile[30];
		gen171_pipex_syncbuf[30] = gen385_cyclix_var;
		gen386_cyclix_var = genpsticky_glbl_regfile[31];
		gen171_pipex_syncbuf[31] = gen386_cyclix_var;
		gen387_cyclix_var = genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_resp_done;
		if (gen387_cyclix_var) {
			genpstage_EXEC_instr_code = genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdata;
		}
		gen179_pipex_var = genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_resp_done;
		gen180_pipex_var = ~gen179_pipex_var;
		gen181_pipex_var = gen180_pipex_var;
		gen388_cyclix_var = gen181_pipex_var;
		if (gen388_cyclix_var) {
			genpstage_EXEC_genpctrl_stalled_glbl = (genpstage_EXEC_genpctrl_stalled_glbl | genpstage_EXEC_genpctrl_active_glbl);
			genpstage_EXEC_genpctrl_active_glbl = ap_uint<32>(0);
		}
		gen182_pipex_var = genpstage_EXEC_instr_code.range(6, 0);
		genpstage_EXEC_opcode = gen182_pipex_var;
		genpstage_EXEC_alu_unsigned = ap_uint<32>(0);
		gen183_pipex_var = genpstage_EXEC_instr_code.range(19, 15);
		genpstage_EXEC_rs1_addr = gen183_pipex_var;
		gen184_pipex_var = genpstage_EXEC_instr_code.range(24, 20);
		genpstage_EXEC_rs2_addr = gen184_pipex_var;
		gen185_pipex_var = genpstage_EXEC_instr_code.range(11, 7);
		genpstage_EXEC_rd_addr = gen185_pipex_var;
		gen186_pipex_var = genpstage_EXEC_instr_code.range(14, 12);
		genpstage_EXEC_funct3 = gen186_pipex_var;
		gen187_pipex_var = genpstage_EXEC_instr_code.range(31, 25);
		genpstage_EXEC_funct7 = gen187_pipex_var;
		gen188_pipex_var = genpstage_EXEC_instr_code.range(24, 20);
		genpstage_EXEC_shamt = gen188_pipex_var;
		gen189_pipex_var = genpstage_EXEC_instr_code.range(27, 24);
		genpstage_EXEC_pred = gen189_pipex_var;
		gen190_pipex_var = genpstage_EXEC_instr_code.range(23, 20);
		genpstage_EXEC_succ = gen190_pipex_var;
		gen191_pipex_var = genpstage_EXEC_instr_code.range(31, 20);
		genpstage_EXEC_csrnum = gen191_pipex_var;
		gen192_pipex_var = genpstage_EXEC_instr_code.range(19, 15);
		genpstage_EXEC_zimm = gen192_pipex_var;
		gen193_pipex_var = genpstage_EXEC_instr_code.range(31, 20);
		gen194_pipex_var = gen193_pipex_var[31];
		gen195_pipex_var = gen194_pipex_var.concat((ap_uint<31>)gen194_pipex_var.concat((ap_uint<30>)gen194_pipex_var.concat((ap_uint<29>)gen194_pipex_var.concat((ap_uint<28>)gen194_pipex_var.concat((ap_uint<27>)gen194_pipex_var.concat((ap_uint<26>)gen194_pipex_var.concat((ap_uint<25>)gen194_pipex_var.concat((ap_uint<24>)gen194_pipex_var.concat((ap_uint<23>)gen194_pipex_var.concat((ap_uint<22>)gen194_pipex_var.concat((ap_uint<21>)gen194_pipex_var.concat((ap_uint<20>)gen194_pipex_var.concat((ap_uint<19>)gen194_pipex_var.concat((ap_uint<18>)gen194_pipex_var.concat((ap_uint<17>)gen194_pipex_var.concat((ap_uint<16>)gen194_pipex_var.concat((ap_uint<15>)gen194_pipex_var.concat((ap_uint<14>)gen194_pipex_var.concat((ap_uint<13>)gen194_pipex_var.concat((ap_uint<12>)gen193_pipex_var))))))))))))))))))));
		genpstage_EXEC_immediate_I = gen195_pipex_var;
		gen196_pipex_var = genpstage_EXEC_instr_code.range(31, 25);
		gen197_pipex_var = genpstage_EXEC_instr_code.range(11, 7);
		gen198_pipex_var = gen196_pipex_var.concat((ap_uint<5>)gen197_pipex_var);
		gen199_pipex_var = gen198_pipex_var[11];
		gen200_pipex_var = gen199_pipex_var.concat((ap_uint<31>)gen199_pipex_var.concat((ap_uint<30>)gen199_pipex_var.concat((ap_uint<29>)gen199_pipex_var.concat((ap_uint<28>)gen199_pipex_var.concat((ap_uint<27>)gen199_pipex_var.concat((ap_uint<26>)gen199_pipex_var.concat((ap_uint<25>)gen199_pipex_var.concat((ap_uint<24>)gen199_pipex_var.concat((ap_uint<23>)gen199_pipex_var.concat((ap_uint<22>)gen199_pipex_var.concat((ap_uint<21>)gen199_pipex_var.concat((ap_uint<20>)gen199_pipex_var.concat((ap_uint<19>)gen199_pipex_var.concat((ap_uint<18>)gen199_pipex_var.concat((ap_uint<17>)gen199_pipex_var.concat((ap_uint<16>)gen199_pipex_var.concat((ap_uint<15>)gen199_pipex_var.concat((ap_uint<14>)gen199_pipex_var.concat((ap_uint<13>)gen199_pipex_var.concat((ap_uint<12>)gen198_pipex_var))))))))))))))))))));
		genpstage_EXEC_immediate_S = gen200_pipex_var;
		gen201_pipex_var = genpstage_EXEC_instr_code[31];
		gen202_pipex_var = genpstage_EXEC_instr_code[7];
		gen203_pipex_var = genpstage_EXEC_instr_code.range(30, 25);
		gen204_pipex_var = genpstage_EXEC_instr_code.range(11, 8);
		gen205_pipex_var = gen201_pipex_var.concat((ap_uint<12>)gen202_pipex_var.concat((ap_uint<11>)gen203_pipex_var.concat((ap_uint<5>)gen204_pipex_var.concat((ap_uint<1>)ap_uint<1>(0)))));
		gen206_pipex_var = gen205_pipex_var[12];
		gen207_pipex_var = gen206_pipex_var.concat((ap_uint<31>)gen206_pipex_var.concat((ap_uint<30>)gen206_pipex_var.concat((ap_uint<29>)gen206_pipex_var.concat((ap_uint<28>)gen206_pipex_var.concat((ap_uint<27>)gen206_pipex_var.concat((ap_uint<26>)gen206_pipex_var.concat((ap_uint<25>)gen206_pipex_var.concat((ap_uint<24>)gen206_pipex_var.concat((ap_uint<23>)gen206_pipex_var.concat((ap_uint<22>)gen206_pipex_var.concat((ap_uint<21>)gen206_pipex_var.concat((ap_uint<20>)gen206_pipex_var.concat((ap_uint<19>)gen206_pipex_var.concat((ap_uint<18>)gen206_pipex_var.concat((ap_uint<17>)gen206_pipex_var.concat((ap_uint<16>)gen206_pipex_var.concat((ap_uint<15>)gen206_pipex_var.concat((ap_uint<14>)gen206_pipex_var.concat((ap_uint<13>)gen205_pipex_var)))))))))))))))))));
		genpstage_EXEC_immediate_B = gen207_pipex_var;
		gen208_pipex_var = genpstage_EXEC_instr_code.range(31, 12);
		gen209_pipex_var = gen208_pipex_var.concat((ap_uint<12>)ap_uint<12>(0));
		genpstage_EXEC_immediate_U = gen209_pipex_var;
		gen210_pipex_var = genpstage_EXEC_instr_code[31];
		gen211_pipex_var = genpstage_EXEC_instr_code.range(19, 12);
		gen212_pipex_var = genpstage_EXEC_instr_code[20];
		gen213_pipex_var = genpstage_EXEC_instr_code.range(30, 21);
		gen214_pipex_var = gen210_pipex_var.concat((ap_uint<20>)gen211_pipex_var.concat((ap_uint<12>)gen212_pipex_var.concat((ap_uint<11>)gen213_pipex_var.concat((ap_uint<1>)ap_uint<1>(0)))));
		gen215_pipex_var = gen214_pipex_var[20];
		gen216_pipex_var = gen215_pipex_var.concat((ap_uint<31>)gen215_pipex_var.concat((ap_uint<30>)gen215_pipex_var.concat((ap_uint<29>)gen215_pipex_var.concat((ap_uint<28>)gen215_pipex_var.concat((ap_uint<27>)gen215_pipex_var.concat((ap_uint<26>)gen215_pipex_var.concat((ap_uint<25>)gen215_pipex_var.concat((ap_uint<24>)gen215_pipex_var.concat((ap_uint<23>)gen215_pipex_var.concat((ap_uint<22>)gen215_pipex_var.concat((ap_uint<21>)gen214_pipex_var)))))))))));
		genpstage_EXEC_immediate_J = gen216_pipex_var;
		switch (genpstage_EXEC_opcode) {
			case 55:
				genpstage_EXEC_op1_source = ap_uint<32>(1);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(0);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_U;
				break;
			case 23:
				genpstage_EXEC_op1_source = ap_uint<32>(2);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_alu_opcode = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_U;
				break;
			case 111:
				genpstage_EXEC_op1_source = ap_uint<32>(2);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_alu_opcode = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(4);
				genpstage_EXEC_jump_req = ap_uint<32>(1);
				genpstage_EXEC_jump_src = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_J;
				break;
			case 103:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_alu_opcode = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(4);
				genpstage_EXEC_jump_req = ap_uint<32>(1);
				genpstage_EXEC_jump_src = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_I;
				break;
			case 99:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_rs2_req = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_alu_opcode = ap_uint<32>(1);
				genpstage_EXEC_jump_req_cond = ap_uint<32>(1);
				genpstage_EXEC_jump_src = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_B;
				gen217_pipex_var = (genpstage_EXEC_funct3 == ap_uint<32>(6));
				gen218_pipex_var = (genpstage_EXEC_funct3 == ap_uint<32>(7));
				gen219_pipex_var = (gen217_pipex_var | gen218_pipex_var);
				gen220_pipex_var = gen219_pipex_var;
				gen389_cyclix_var = gen220_pipex_var;
				if (gen389_cyclix_var) {
					genpstage_EXEC_alu_unsigned = ap_uint<32>(1);
				}
				break;
			case 3:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(5);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_mem_req = ap_uint<32>(1);
				genpstage_EXEC_mem_cmd = ap_uint<32>(0);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_I;
				break;
			case 35:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_rs2_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_mem_req = ap_uint<32>(1);
				genpstage_EXEC_mem_cmd = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_S;
				break;
			case 19:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_I;
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				switch (genpstage_EXEC_funct3) {
					case 0:
						genpstage_EXEC_alu_opcode = ap_uint<32>(0);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 1:
						genpstage_EXEC_alu_opcode = ap_uint<32>(4);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						gen221_pipex_var = genpstage_EXEC_instr_code.range(24, 20);
						gen222_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)gen221_pipex_var);
						genpstage_EXEC_immediate = gen222_pipex_var;
						break;
					case 2:
						genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						genpstage_EXEC_alu_unsigned = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(2);
						break;
					case 4:
						genpstage_EXEC_alu_opcode = ap_uint<32>(7);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 5:
						gen223_pipex_var = genpstage_EXEC_instr_code[30];
						gen224_pipex_var = gen223_pipex_var;
						gen390_cyclix_var = gen224_pipex_var;
						if (gen390_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(6);
						}
						gen225_pipex_var = ap_uint<1>(0);
						gen225_pipex_var = (gen225_pipex_var || gen224_pipex_var);
						gen225_pipex_var = !gen225_pipex_var;
						gen391_cyclix_var = gen225_pipex_var;
						if (gen391_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(5);
						}
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						gen226_pipex_var = genpstage_EXEC_instr_code.range(24, 20);
						gen227_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)gen226_pipex_var);
						genpstage_EXEC_immediate = gen227_pipex_var;
						break;
					case 6:
						genpstage_EXEC_alu_opcode = ap_uint<32>(3);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 7:
						genpstage_EXEC_alu_opcode = ap_uint<32>(2);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
				}
				break;
			case 51:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_rs2_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				switch (genpstage_EXEC_funct3) {
					case 0:
						gen228_pipex_var = genpstage_EXEC_instr_code[30];
						gen229_pipex_var = gen228_pipex_var;
						gen392_cyclix_var = gen229_pipex_var;
						if (gen392_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						}
						gen230_pipex_var = ap_uint<1>(0);
						gen230_pipex_var = (gen230_pipex_var || gen229_pipex_var);
						gen230_pipex_var = !gen230_pipex_var;
						gen393_cyclix_var = gen230_pipex_var;
						if (gen393_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(0);
						}
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 1:
						genpstage_EXEC_alu_opcode = ap_uint<32>(4);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 2:
						genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						genpstage_EXEC_alu_unsigned = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(2);
						break;
					case 4:
						genpstage_EXEC_alu_opcode = ap_uint<32>(7);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 5:
						gen231_pipex_var = genpstage_EXEC_instr_code[30];
						gen232_pipex_var = gen231_pipex_var;
						gen394_cyclix_var = gen232_pipex_var;
						if (gen394_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(6);
						}
						gen233_pipex_var = ap_uint<1>(0);
						gen233_pipex_var = (gen233_pipex_var || gen232_pipex_var);
						gen233_pipex_var = !gen233_pipex_var;
						gen395_cyclix_var = gen233_pipex_var;
						if (gen395_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(5);
						}
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 6:
						genpstage_EXEC_alu_opcode = ap_uint<32>(3);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 7:
						genpstage_EXEC_alu_opcode = ap_uint<32>(2);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
				}
				break;
			case 15:
				genpstage_EXEC_fencereq = ap_uint<32>(1);
				break;
			case 115:
				switch (genpstage_EXEC_funct3) {
					case 0:
						gen234_pipex_var = genpstage_EXEC_instr_code[20];
						gen235_pipex_var = gen234_pipex_var;
						gen396_cyclix_var = gen235_pipex_var;
						if (gen396_cyclix_var) {
							genpstage_EXEC_ebreakreq = ap_uint<32>(1);
						}
						gen236_pipex_var = ap_uint<1>(0);
						gen236_pipex_var = (gen236_pipex_var || gen235_pipex_var);
						gen236_pipex_var = !gen236_pipex_var;
						gen397_cyclix_var = gen236_pipex_var;
						if (gen397_cyclix_var) {
							genpstage_EXEC_ecallreq = ap_uint<32>(1);
						}
						break;
					case 1:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rs1_req = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_op1_source = ap_uint<32>(0);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						break;
					case 2:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rs1_req = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_alu_req = ap_uint<32>(1);
						genpstage_EXEC_alu_opcode = ap_uint<32>(3);
						genpstage_EXEC_op1_source = ap_uint<32>(0);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rs1_req = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_alu_req = ap_uint<32>(1);
						genpstage_EXEC_alu_opcode = ap_uint<32>(8);
						genpstage_EXEC_op1_source = ap_uint<32>(0);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						break;
					case 5:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_op1_source = ap_uint<32>(1);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						gen237_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_zimm);
						genpstage_EXEC_immediate = gen237_pipex_var;
						break;
					case 6:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_alu_req = ap_uint<32>(1);
						genpstage_EXEC_alu_opcode = ap_uint<32>(8);
						genpstage_EXEC_op1_source = ap_uint<32>(1);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						gen238_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_zimm);
						genpstage_EXEC_immediate = gen238_pipex_var;
						break;
					case 7:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_alu_req = ap_uint<32>(1);
						genpstage_EXEC_alu_opcode = ap_uint<32>(8);
						genpstage_EXEC_op1_source = ap_uint<32>(1);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						gen239_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_zimm);
						genpstage_EXEC_immediate = gen239_pipex_var;
						break;
				}
				break;
		}
		gen240_pipex_var = genpstage_EXEC_mem_req;
		gen398_cyclix_var = gen240_pipex_var;
		if (gen398_cyclix_var) {
			switch (genpstage_EXEC_funct3) {
				case 0:
					genpstage_EXEC_mem_be = ap_uint<32>(1);
					break;
				case 1:
					genpstage_EXEC_mem_be = ap_uint<32>(3);
					break;
				case 2:
					genpstage_EXEC_mem_be = ap_uint<32>(15);
					break;
				case 4:
					genpstage_EXEC_mem_be = ap_uint<32>(1);
					break;
				case 5:
					genpstage_EXEC_mem_be = ap_uint<32>(3);
					break;
			}
		}
		gen241_pipex_var = (genpstage_EXEC_instr_code == ap_uint<32>(807403635));
		gen242_pipex_var = gen241_pipex_var;
		gen399_cyclix_var = gen242_pipex_var;
		if (gen399_cyclix_var) {
			genpstage_EXEC_mret_req = ap_uint<32>(1);
			genpstage_EXEC_jump_req = ap_uint<32>(1);
			genpstage_EXEC_jump_req_cond = ap_uint<32>(0);
			genpstage_EXEC_jump_src = ap_uint<32>(0);
			genpstage_EXEC_immediate = genpsticky_glbl_MRETADDR;
		}
		gen243_pipex_var = (genpstage_EXEC_rd_addr == ap_uint<32>(0));
		gen244_pipex_var = gen243_pipex_var;
		gen400_cyclix_var = gen244_pipex_var;
		if (gen400_cyclix_var) {
			genpstage_EXEC_rd_req = ap_uint<32>(0);
		}
		gen401_cyclix_var = genpsticky_glbl_regfile_buf[1];
		gen245_pipex_var[1] = gen401_cyclix_var;
		gen402_cyclix_var = genpsticky_glbl_regfile_buf[2];
		gen245_pipex_var[2] = gen402_cyclix_var;
		gen403_cyclix_var = genpsticky_glbl_regfile_buf[3];
		gen245_pipex_var[3] = gen403_cyclix_var;
		gen404_cyclix_var = genpsticky_glbl_regfile_buf[4];
		gen245_pipex_var[4] = gen404_cyclix_var;
		gen405_cyclix_var = genpsticky_glbl_regfile_buf[5];
		gen245_pipex_var[5] = gen405_cyclix_var;
		gen406_cyclix_var = genpsticky_glbl_regfile_buf[6];
		gen245_pipex_var[6] = gen406_cyclix_var;
		gen407_cyclix_var = genpsticky_glbl_regfile_buf[7];
		gen245_pipex_var[7] = gen407_cyclix_var;
		gen408_cyclix_var = genpsticky_glbl_regfile_buf[8];
		gen245_pipex_var[8] = gen408_cyclix_var;
		gen409_cyclix_var = genpsticky_glbl_regfile_buf[9];
		gen245_pipex_var[9] = gen409_cyclix_var;
		gen410_cyclix_var = genpsticky_glbl_regfile_buf[10];
		gen245_pipex_var[10] = gen410_cyclix_var;
		gen411_cyclix_var = genpsticky_glbl_regfile_buf[11];
		gen245_pipex_var[11] = gen411_cyclix_var;
		gen412_cyclix_var = genpsticky_glbl_regfile_buf[12];
		gen245_pipex_var[12] = gen412_cyclix_var;
		gen413_cyclix_var = genpsticky_glbl_regfile_buf[13];
		gen245_pipex_var[13] = gen413_cyclix_var;
		gen414_cyclix_var = genpsticky_glbl_regfile_buf[14];
		gen245_pipex_var[14] = gen414_cyclix_var;
		gen415_cyclix_var = genpsticky_glbl_regfile_buf[15];
		gen245_pipex_var[15] = gen415_cyclix_var;
		gen416_cyclix_var = genpsticky_glbl_regfile_buf[16];
		gen245_pipex_var[16] = gen416_cyclix_var;
		gen417_cyclix_var = genpsticky_glbl_regfile_buf[17];
		gen245_pipex_var[17] = gen417_cyclix_var;
		gen418_cyclix_var = genpsticky_glbl_regfile_buf[18];
		gen245_pipex_var[18] = gen418_cyclix_var;
		gen419_cyclix_var = genpsticky_glbl_regfile_buf[19];
		gen245_pipex_var[19] = gen419_cyclix_var;
		gen420_cyclix_var = genpsticky_glbl_regfile_buf[20];
		gen245_pipex_var[20] = gen420_cyclix_var;
		gen421_cyclix_var = genpsticky_glbl_regfile_buf[21];
		gen245_pipex_var[21] = gen421_cyclix_var;
		gen422_cyclix_var = genpsticky_glbl_regfile_buf[22];
		gen245_pipex_var[22] = gen422_cyclix_var;
		gen423_cyclix_var = genpsticky_glbl_regfile_buf[23];
		gen245_pipex_var[23] = gen423_cyclix_var;
		gen424_cyclix_var = genpsticky_glbl_regfile_buf[24];
		gen245_pipex_var[24] = gen424_cyclix_var;
		gen425_cyclix_var = genpsticky_glbl_regfile_buf[25];
		gen245_pipex_var[25] = gen425_cyclix_var;
		gen426_cyclix_var = genpsticky_glbl_regfile_buf[26];
		gen245_pipex_var[26] = gen426_cyclix_var;
		gen427_cyclix_var = genpsticky_glbl_regfile_buf[27];
		gen245_pipex_var[27] = gen427_cyclix_var;
		gen428_cyclix_var = genpsticky_glbl_regfile_buf[28];
		gen245_pipex_var[28] = gen428_cyclix_var;
		gen429_cyclix_var = genpsticky_glbl_regfile_buf[29];
		gen245_pipex_var[29] = gen429_cyclix_var;
		gen430_cyclix_var = genpsticky_glbl_regfile_buf[30];
		gen245_pipex_var[30] = gen430_cyclix_var;
		gen431_cyclix_var = genpsticky_glbl_regfile_buf[31];
		gen245_pipex_var[31] = gen431_cyclix_var;
		gen246_pipex_var = gen245_pipex_var[genpstage_EXEC_rs1_addr];
		genpstage_EXEC_rs1_rdata = gen246_pipex_var;
		gen432_cyclix_var = genpsticky_glbl_regfile_buf[1];
		gen247_pipex_var[1] = gen432_cyclix_var;
		gen433_cyclix_var = genpsticky_glbl_regfile_buf[2];
		gen247_pipex_var[2] = gen433_cyclix_var;
		gen434_cyclix_var = genpsticky_glbl_regfile_buf[3];
		gen247_pipex_var[3] = gen434_cyclix_var;
		gen435_cyclix_var = genpsticky_glbl_regfile_buf[4];
		gen247_pipex_var[4] = gen435_cyclix_var;
		gen436_cyclix_var = genpsticky_glbl_regfile_buf[5];
		gen247_pipex_var[5] = gen436_cyclix_var;
		gen437_cyclix_var = genpsticky_glbl_regfile_buf[6];
		gen247_pipex_var[6] = gen437_cyclix_var;
		gen438_cyclix_var = genpsticky_glbl_regfile_buf[7];
		gen247_pipex_var[7] = gen438_cyclix_var;
		gen439_cyclix_var = genpsticky_glbl_regfile_buf[8];
		gen247_pipex_var[8] = gen439_cyclix_var;
		gen440_cyclix_var = genpsticky_glbl_regfile_buf[9];
		gen247_pipex_var[9] = gen440_cyclix_var;
		gen441_cyclix_var = genpsticky_glbl_regfile_buf[10];
		gen247_pipex_var[10] = gen441_cyclix_var;
		gen442_cyclix_var = genpsticky_glbl_regfile_buf[11];
		gen247_pipex_var[11] = gen442_cyclix_var;
		gen443_cyclix_var = genpsticky_glbl_regfile_buf[12];
		gen247_pipex_var[12] = gen443_cyclix_var;
		gen444_cyclix_var = genpsticky_glbl_regfile_buf[13];
		gen247_pipex_var[13] = gen444_cyclix_var;
		gen445_cyclix_var = genpsticky_glbl_regfile_buf[14];
		gen247_pipex_var[14] = gen445_cyclix_var;
		gen446_cyclix_var = genpsticky_glbl_regfile_buf[15];
		gen247_pipex_var[15] = gen446_cyclix_var;
		gen447_cyclix_var = genpsticky_glbl_regfile_buf[16];
		gen247_pipex_var[16] = gen447_cyclix_var;
		gen448_cyclix_var = genpsticky_glbl_regfile_buf[17];
		gen247_pipex_var[17] = gen448_cyclix_var;
		gen449_cyclix_var = genpsticky_glbl_regfile_buf[18];
		gen247_pipex_var[18] = gen449_cyclix_var;
		gen450_cyclix_var = genpsticky_glbl_regfile_buf[19];
		gen247_pipex_var[19] = gen450_cyclix_var;
		gen451_cyclix_var = genpsticky_glbl_regfile_buf[20];
		gen247_pipex_var[20] = gen451_cyclix_var;
		gen452_cyclix_var = genpsticky_glbl_regfile_buf[21];
		gen247_pipex_var[21] = gen452_cyclix_var;
		gen453_cyclix_var = genpsticky_glbl_regfile_buf[22];
		gen247_pipex_var[22] = gen453_cyclix_var;
		gen454_cyclix_var = genpsticky_glbl_regfile_buf[23];
		gen247_pipex_var[23] = gen454_cyclix_var;
		gen455_cyclix_var = genpsticky_glbl_regfile_buf[24];
		gen247_pipex_var[24] = gen455_cyclix_var;
		gen456_cyclix_var = genpsticky_glbl_regfile_buf[25];
		gen247_pipex_var[25] = gen456_cyclix_var;
		gen457_cyclix_var = genpsticky_glbl_regfile_buf[26];
		gen247_pipex_var[26] = gen457_cyclix_var;
		gen458_cyclix_var = genpsticky_glbl_regfile_buf[27];
		gen247_pipex_var[27] = gen458_cyclix_var;
		gen459_cyclix_var = genpsticky_glbl_regfile_buf[28];
		gen247_pipex_var[28] = gen459_cyclix_var;
		gen460_cyclix_var = genpsticky_glbl_regfile_buf[29];
		gen247_pipex_var[29] = gen460_cyclix_var;
		gen461_cyclix_var = genpsticky_glbl_regfile_buf[30];
		gen247_pipex_var[30] = gen461_cyclix_var;
		gen462_cyclix_var = genpsticky_glbl_regfile_buf[31];
		gen247_pipex_var[31] = gen462_cyclix_var;
		gen248_pipex_var = gen247_pipex_var[genpstage_EXEC_rs2_addr];
		genpstage_EXEC_rs2_rdata = gen248_pipex_var;
		gen249_pipex_var = (genpstage_EXEC_rs1_addr == ap_uint<32>(0));
		gen250_pipex_var = gen249_pipex_var;
		gen463_cyclix_var = gen250_pipex_var;
		if (gen463_cyclix_var) {
			genpstage_EXEC_rs1_rdata = ap_uint<32>(0);
		}
		gen251_pipex_var = (genpstage_EXEC_rs2_addr == ap_uint<32>(0));
		gen252_pipex_var = gen251_pipex_var;
		gen464_cyclix_var = gen252_pipex_var;
		if (gen464_cyclix_var) {
			genpstage_EXEC_rs2_rdata = ap_uint<32>(0);
		}
		gen253_pipex_var = genpstage_EXEC_csrreq;
		gen465_cyclix_var = gen253_pipex_var;
		if (gen465_cyclix_var) {
			genpstage_EXEC_csr_rdata = genpsticky_glbl_CSR_MCAUSE;
		}
		genpstage_EXEC_alu_op1 = genpstage_EXEC_rs1_rdata;
		switch (genpstage_EXEC_op1_source) {
			case 1:
				genpstage_EXEC_alu_op1 = genpstage_EXEC_immediate;
				break;
			case 2:
				genpstage_EXEC_alu_op1 = genpstage_EXEC_curinstr_addr;
				break;
		}
		genpstage_EXEC_alu_op2 = genpstage_EXEC_rs2_rdata;
		switch (genpstage_EXEC_op2_source) {
			case 1:
				genpstage_EXEC_alu_op2 = genpstage_EXEC_immediate;
				break;
			case 2:
				genpstage_EXEC_alu_op2 = genpstage_EXEC_csr_rdata;
				break;
		}
		gen254_pipex_var = genpstage_EXEC_alu_unsigned;
		gen466_cyclix_var = gen254_pipex_var;
		if (gen466_cyclix_var) {
			gen255_pipex_var = ap_uint<1>(0).concat((ap_uint<32>)genpstage_EXEC_alu_op1);
			genpstage_EXEC_alu_op1_wide = gen255_pipex_var;
			gen256_pipex_var = ap_uint<1>(0).concat((ap_uint<32>)genpstage_EXEC_alu_op2);
			genpstage_EXEC_alu_op2_wide = gen256_pipex_var;
		}
		gen257_pipex_var = ap_uint<1>(0);
		gen257_pipex_var = (gen257_pipex_var || gen254_pipex_var);
		gen257_pipex_var = !gen257_pipex_var;
		gen467_cyclix_var = gen257_pipex_var;
		if (gen467_cyclix_var) {
			gen258_pipex_var = genpstage_EXEC_alu_op1[31];
			gen259_pipex_var = gen258_pipex_var.concat((ap_uint<32>)genpstage_EXEC_alu_op1);
			genpstage_EXEC_alu_op1_wide = gen259_pipex_var;
			gen260_pipex_var = genpstage_EXEC_alu_op2[31];
			gen261_pipex_var = gen260_pipex_var.concat((ap_uint<32>)genpstage_EXEC_alu_op2);
			genpstage_EXEC_alu_op2_wide = gen261_pipex_var;
		}
		gen262_pipex_var = genpsticky_glbl_MIRQEN;
		gen468_cyclix_var = gen262_pipex_var;
		if (gen468_cyclix_var) {
			gen263_pipex_var = ~genpstage_EXEC_irq_recv;
			gen264_pipex_var = gen263_pipex_var;
			gen469_cyclix_var = gen264_pipex_var;
			if (gen469_cyclix_var) {
				gen470_cyclix_var = genpstage_EXEC_genpctrl_active_glbl;
				if (gen470_cyclix_var) {
					gen471_cyclix_var = irq_fifo.read_nb(genpstage_EXEC_irq_mcause);
					gen265_pipex_var = gen471_cyclix_var;
				}
				genpstage_EXEC_irq_recv = gen265_pipex_var;
			}
			gen266_pipex_var = genpstage_EXEC_irq_recv;
			gen472_cyclix_var = gen266_pipex_var;
			if (gen472_cyclix_var) {
				genpstage_EXEC_jump_req = ap_uint<32>(1);
				genpstage_EXEC_jump_req_cond = ap_uint<32>(0);
				genpstage_EXEC_jump_src = ap_uint<32>(0);
				genpstage_EXEC_rs1_req = ap_uint<32>(0);
				genpstage_EXEC_rs2_req = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(0);
				genpstage_EXEC_immediate = ap_uint<32>(128);
				genpstage_EXEC_fencereq = ap_uint<32>(0);
				genpstage_EXEC_ecallreq = ap_uint<32>(0);
				genpstage_EXEC_ebreakreq = ap_uint<32>(0);
				genpstage_EXEC_csrreq = ap_uint<32>(0);
				genpstage_EXEC_alu_req = ap_uint<32>(0);
				genpstage_EXEC_mem_req = ap_uint<32>(0);
				gen473_cyclix_var = ~genpstage_EXEC_genpctrl_stalled_glbl;
				gen474_cyclix_var = gen473_cyclix_var;
				if (gen474_cyclix_var) {
					gen475_cyclix_var = genpstage_EXEC_genpctrl_active_glbl;
					if (gen475_cyclix_var) {
						genpsticky_glbl_MIRQEN = ap_uint<32>(0);
					}
				}
				gen476_cyclix_var = ~genpstage_EXEC_genpctrl_stalled_glbl;
				gen477_cyclix_var = gen476_cyclix_var;
				if (gen477_cyclix_var) {
					gen478_cyclix_var = genpstage_EXEC_genpctrl_active_glbl;
					if (gen478_cyclix_var) {
						genpsticky_glbl_CSR_MCAUSE = genpstage_EXEC_irq_mcause;
					}
				}
				gen479_cyclix_var = ~genpstage_EXEC_genpctrl_stalled_glbl;
				gen480_cyclix_var = gen479_cyclix_var;
				if (gen480_cyclix_var) {
					gen481_cyclix_var = genpstage_EXEC_genpctrl_active_glbl;
					if (gen481_cyclix_var) {
						genpsticky_glbl_MRETADDR = genpstage_EXEC_curinstr_addr;
					}
				}
			}
		}
		gen267_pipex_var = genpstage_EXEC_mret_req;
		gen482_cyclix_var = gen267_pipex_var;
		if (gen482_cyclix_var) {
			gen483_cyclix_var = ~genpstage_EXEC_genpctrl_stalled_glbl;
			gen484_cyclix_var = gen483_cyclix_var;
			if (gen484_cyclix_var) {
				gen485_cyclix_var = genpstage_EXEC_genpctrl_active_glbl;
				if (gen485_cyclix_var) {
					genpsticky_glbl_MIRQEN = ap_uint<32>(1);
				}
			}
		}
		genpstage_EXEC_alu_result_wide = genpstage_EXEC_alu_op1_wide;
		gen268_pipex_var = genpstage_EXEC_alu_req;
		gen486_cyclix_var = gen268_pipex_var;
		if (gen486_cyclix_var) {
			switch (genpstage_EXEC_alu_opcode) {
				case 0:
					gen269_pipex_var = (genpstage_EXEC_alu_op1_wide + genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen269_pipex_var;
					break;
				case 1:
					gen270_pipex_var = (genpstage_EXEC_alu_op1_wide - genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen270_pipex_var;
					break;
				case 2:
					gen271_pipex_var = (genpstage_EXEC_alu_op1_wide & genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen271_pipex_var;
					break;
				case 3:
					gen272_pipex_var = (genpstage_EXEC_alu_op1_wide | genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen272_pipex_var;
					break;
				case 4:
					gen273_pipex_var = (genpstage_EXEC_alu_op1_wide << genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen273_pipex_var;
					break;
				case 5:
					gen274_pipex_var = genpstage_EXEC_alu_op1_wide.range(31, 0);
					gen275_pipex_var = ap_uint<32>(0).concat((ap_uint<32>)gen274_pipex_var);
					gen276_pipex_var = genpstage_EXEC_alu_op2_wide.range(4, 0);
					gen277_pipex_var = (gen275_pipex_var >> gen276_pipex_var);
					genpstage_EXEC_alu_result_wide = gen277_pipex_var;
					break;
				case 6:
					gen278_pipex_var = genpstage_EXEC_alu_op1_wide.range(31, 0);
					gen279_pipex_var = gen278_pipex_var[31];
					gen280_pipex_var = gen279_pipex_var.concat((ap_uint<63>)gen279_pipex_var.concat((ap_uint<62>)gen279_pipex_var.concat((ap_uint<61>)gen279_pipex_var.concat((ap_uint<60>)gen279_pipex_var.concat((ap_uint<59>)gen279_pipex_var.concat((ap_uint<58>)gen279_pipex_var.concat((ap_uint<57>)gen279_pipex_var.concat((ap_uint<56>)gen279_pipex_var.concat((ap_uint<55>)gen279_pipex_var.concat((ap_uint<54>)gen279_pipex_var.concat((ap_uint<53>)gen279_pipex_var.concat((ap_uint<52>)gen279_pipex_var.concat((ap_uint<51>)gen279_pipex_var.concat((ap_uint<50>)gen279_pipex_var.concat((ap_uint<49>)gen279_pipex_var.concat((ap_uint<48>)gen279_pipex_var.concat((ap_uint<47>)gen279_pipex_var.concat((ap_uint<46>)gen279_pipex_var.concat((ap_uint<45>)gen279_pipex_var.concat((ap_uint<44>)gen279_pipex_var.concat((ap_uint<43>)gen279_pipex_var.concat((ap_uint<42>)gen279_pipex_var.concat((ap_uint<41>)gen279_pipex_var.concat((ap_uint<40>)gen279_pipex_var.concat((ap_uint<39>)gen279_pipex_var.concat((ap_uint<38>)gen279_pipex_var.concat((ap_uint<37>)gen279_pipex_var.concat((ap_uint<36>)gen279_pipex_var.concat((ap_uint<35>)gen279_pipex_var.concat((ap_uint<34>)gen279_pipex_var.concat((ap_uint<33>)gen279_pipex_var.concat((ap_uint<32>)gen278_pipex_var))))))))))))))))))))))))))))))));
					gen281_pipex_var = genpstage_EXEC_alu_op2_wide.range(4, 0);
					gen282_pipex_var = (gen280_pipex_var >> gen281_pipex_var);
					genpstage_EXEC_alu_result_wide = gen282_pipex_var;
					break;
				case 7:
					gen283_pipex_var = (genpstage_EXEC_alu_op1_wide ^ genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen283_pipex_var;
					break;
				case 8:
					gen284_pipex_var = ~genpstage_EXEC_alu_op2_wide;
					gen285_pipex_var = (genpstage_EXEC_alu_op1_wide & gen284_pipex_var);
					genpstage_EXEC_alu_result_wide = gen285_pipex_var;
					break;
			}
			gen286_pipex_var = genpstage_EXEC_alu_result_wide.range(31, 0);
			genpstage_EXEC_alu_result = gen286_pipex_var;
			gen287_pipex_var = genpstage_EXEC_alu_result_wide[32];
			genpstage_EXEC_alu_CF = gen287_pipex_var;
			gen288_pipex_var = genpstage_EXEC_alu_result_wide[31];
			genpstage_EXEC_alu_SF = gen288_pipex_var;
			gen289_pipex_var = |genpstage_EXEC_alu_result;
			gen290_pipex_var = ~gen289_pipex_var;
			genpstage_EXEC_alu_ZF = gen290_pipex_var;
			gen291_pipex_var = genpstage_EXEC_alu_op1[31];
			gen292_pipex_var = ~gen291_pipex_var;
			gen293_pipex_var = genpstage_EXEC_alu_op2[31];
			gen294_pipex_var = ~gen293_pipex_var;
			gen295_pipex_var = genpstage_EXEC_alu_result[31];
			gen296_pipex_var = (gen294_pipex_var & gen295_pipex_var);
			gen297_pipex_var = (gen292_pipex_var & gen296_pipex_var);
			gen298_pipex_var = genpstage_EXEC_alu_op1[31];
			gen299_pipex_var = genpstage_EXEC_alu_op2[31];
			gen300_pipex_var = genpstage_EXEC_alu_result[31];
			gen301_pipex_var = ~gen300_pipex_var;
			gen302_pipex_var = (gen299_pipex_var & gen301_pipex_var);
			gen303_pipex_var = (gen298_pipex_var & gen302_pipex_var);
			gen304_pipex_var = (gen297_pipex_var | gen303_pipex_var);
			genpstage_EXEC_alu_OF = gen304_pipex_var;
			gen305_pipex_var = genpstage_EXEC_alu_unsigned;
			gen487_cyclix_var = gen305_pipex_var;
			if (gen487_cyclix_var) {
				genpstage_EXEC_alu_overflow = genpstage_EXEC_alu_CF;
			}
			gen306_pipex_var = ap_uint<1>(0);
			gen306_pipex_var = (gen306_pipex_var || gen305_pipex_var);
			gen306_pipex_var = !gen306_pipex_var;
			gen488_cyclix_var = gen306_pipex_var;
			if (gen488_cyclix_var) {
				genpstage_EXEC_alu_overflow = genpstage_EXEC_alu_OF;
			}
		}
		switch (genpstage_EXEC_rd_source) {
			case 0:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_immediate;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 1:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_alu_result;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 2:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_alu_CF;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 3:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_alu_OF;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 4:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_nextinstr_addr;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 6:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_csr_rdata;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
		}
		gen307_pipex_var = (genpstage_EXEC_curinstr_addr + genpstage_EXEC_immediate);
		genpstage_EXEC_curinstraddr_imm = gen307_pipex_var;
		switch (genpstage_EXEC_jump_src) {
			case 0:
				genpstage_EXEC_jump_vector = genpstage_EXEC_immediate;
				break;
			case 1:
				genpstage_EXEC_jump_vector = genpstage_EXEC_alu_result;
				break;
		}
		gen308_pipex_var = genpstage_EXEC_jump_req_cond;
		gen489_cyclix_var = gen308_pipex_var;
		if (gen489_cyclix_var) {
			switch (genpstage_EXEC_funct3) {
				case 0:
					gen309_pipex_var = genpstage_EXEC_alu_ZF;
					gen490_cyclix_var = gen309_pipex_var;
					if (gen490_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 1:
					gen310_pipex_var = ~genpstage_EXEC_alu_ZF;
					gen311_pipex_var = gen310_pipex_var;
					gen491_cyclix_var = gen311_pipex_var;
					if (gen491_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 4:
					gen312_pipex_var = genpstage_EXEC_alu_CF;
					gen492_cyclix_var = gen312_pipex_var;
					if (gen492_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 5:
					gen313_pipex_var = ~genpstage_EXEC_alu_CF;
					gen314_pipex_var = gen313_pipex_var;
					gen493_cyclix_var = gen314_pipex_var;
					if (gen493_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 6:
					gen315_pipex_var = genpstage_EXEC_alu_CF;
					gen494_cyclix_var = gen315_pipex_var;
					if (gen494_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 7:
					gen316_pipex_var = ~genpstage_EXEC_alu_CF;
					gen317_pipex_var = gen316_pipex_var;
					gen495_cyclix_var = gen317_pipex_var;
					if (gen495_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
			}
		}
		genpstage_EXEC_mem_addr = genpstage_EXEC_alu_result;
		genpstage_EXEC_mem_wdata = genpstage_EXEC_rs2_rdata;
		gen166_pipex_syncreq = ap_uint<32>(1);
		gen167_pipex_syncbuf = genpstage_EXEC_jump_req;
		gen168_pipex_syncreq = ap_uint<32>(1);
		gen169_pipex_syncbuf = genpstage_EXEC_jump_vector;
		gen318_pipex_var = genpstage_EXEC_jump_req;
		gen496_cyclix_var = gen318_pipex_var;
		if (gen496_cyclix_var) {
			genpstage_EXEC_genpctrl_flushreq = (genpstage_EXEC_genpctrl_flushreq | genpstage_EXEC_genpctrl_active_glbl);
		}
		gen319_pipex_var = genpstage_EXEC_mem_req;
		gen497_cyclix_var = gen319_pipex_var;
		if (gen497_cyclix_var) {
			gen320_pipex_var = ~genpstage_EXEC_data_req_done;
			gen321_pipex_var = gen320_pipex_var;
			gen498_cyclix_var = gen321_pipex_var;
			if (gen498_cyclix_var) {
				genpstage_EXEC_data_busreq.addr = genpstage_EXEC_mem_addr;
				genpstage_EXEC_data_busreq.be = ap_uint<32>(15);
				genpstage_EXEC_data_busreq.wdata = genpstage_EXEC_mem_wdata;
				gen499_cyclix_var = genpstage_EXEC_genpctrl_active_glbl;
				if (gen499_cyclix_var) {
					gen500_cyclix_var = ~genmcopipe_data_mem_full_flag;
					gen501_cyclix_var = gen500_cyclix_var;
					if (gen501_cyclix_var) {
						gen337_pipex_req_struct.we = genpstage_EXEC_mem_cmd;
						gen337_pipex_req_struct.wdata = genpstage_EXEC_data_busreq;
						gen502_cyclix_var = genmcopipe_data_mem_req.write_nb(gen337_pipex_req_struct);
						gen503_cyclix_var = gen502_cyclix_var;
						if (gen503_cyclix_var) {
							gen322_pipex_var = ap_uint<32>(1);
							gen504_cyclix_var = !genpstage_EXEC_mem_cmd;
							genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdreq_pending = gen504_cyclix_var;
							genpstage_EXEC_genmcopipe_handle_data_mem_genvar_tid = genmcopipe_data_mem_wr_ptr;
							genpstage_EXEC_genmcopipe_handle_data_mem_genvar_if_id = ap_uint<1>(0);
							gen505_cyclix_var = genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdreq_pending;
							if (gen505_cyclix_var) {
								genmcopipe_data_mem_wr_done = ap_uint<32>(1);
							}
						}
					}
				}
				genpstage_EXEC_data_req_done = gen322_pipex_var;
			}
			gen323_pipex_var = ~genpstage_EXEC_data_req_done;
			gen324_pipex_var = gen323_pipex_var;
			gen506_cyclix_var = gen324_pipex_var;
			if (gen506_cyclix_var) {
				genpstage_EXEC_genpctrl_stalled_glbl = (genpstage_EXEC_genpctrl_stalled_glbl | genpstage_EXEC_genpctrl_active_glbl);
				genpstage_EXEC_genpctrl_active_glbl = ap_uint<32>(0);
			}
		}
		gen325_pipex_var = genpstage_EXEC_mem_req;
		gen507_cyclix_var = gen325_pipex_var;
		if (gen507_cyclix_var) {
			gen326_pipex_var = ~genpstage_EXEC_mem_cmd;
			gen327_pipex_var = gen326_pipex_var;
			gen508_cyclix_var = gen327_pipex_var;
			if (gen508_cyclix_var) {
				gen509_cyclix_var = genpstage_EXEC_genmcopipe_handle_data_mem_genvar_resp_done;
				if (gen509_cyclix_var) {
					genpstage_EXEC_mem_rdata = genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdata;
				}
				gen328_pipex_var = genpstage_EXEC_genmcopipe_handle_data_mem_genvar_resp_done;
				gen329_pipex_var = gen328_pipex_var;
				gen510_cyclix_var = gen329_pipex_var;
				if (gen510_cyclix_var) {
					genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				}
				gen330_pipex_var = ap_uint<1>(0);
				gen330_pipex_var = (gen330_pipex_var || gen329_pipex_var);
				gen330_pipex_var = !gen330_pipex_var;
				gen511_cyclix_var = gen330_pipex_var;
				if (gen511_cyclix_var) {
					genpstage_EXEC_genpctrl_stalled_glbl = (genpstage_EXEC_genpctrl_stalled_glbl | genpstage_EXEC_genpctrl_active_glbl);
					genpstage_EXEC_genpctrl_active_glbl = ap_uint<32>(0);
				}
			}
		}
		gen331_pipex_var = (genpstage_EXEC_rd_source == ap_uint<32>(5));
		gen332_pipex_var = gen331_pipex_var;
		gen512_cyclix_var = gen332_pipex_var;
		if (gen512_cyclix_var) {
			genpstage_EXEC_rd_wdata = genpstage_EXEC_mem_rdata;
		}
		gen333_pipex_var = genpstage_EXEC_rd_req;
		gen513_cyclix_var = gen333_pipex_var;
		if (gen513_cyclix_var) {
			gen170_pipex_syncreq = ap_uint<32>(1);
			gen171_pipex_syncbuf[genpstage_EXEC_rd_addr] = genpstage_EXEC_rd_wdata;
		}
		genpstage_EXEC_genpctrl_nevictable = (genpstage_EXEC_genpctrl_nevictable || genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdreq_pending);
		genpstage_EXEC_genpctrl_nevictable = (genpstage_EXEC_genpctrl_nevictable || genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdreq_pending);
		gen514_cyclix_var = genpstage_EXEC_genpctrl_stalled_glbl;
		if (gen514_cyclix_var) {
			genpstage_EXEC_genpctrl_finish = ap_uint<32>(0);
			genpstage_EXEC_genpctrl_succ = ap_uint<32>(0);
		}
		gen515_cyclix_var = ap_uint<1>(0);
		gen515_cyclix_var = (gen515_cyclix_var || gen514_cyclix_var);
		gen515_cyclix_var = !gen515_cyclix_var;
		if (gen515_cyclix_var) {
			genpstage_EXEC_genpctrl_finish = genpstage_EXEC_genpctrl_occupied;
			genpstage_EXEC_genpctrl_succ = genpstage_EXEC_genpctrl_active_glbl;
		}
		gen516_cyclix_var = genpstage_EXEC_genpctrl_succ;
		if (gen516_cyclix_var) {
			gen517_cyclix_var = gen166_pipex_syncreq;
			if (gen517_cyclix_var) {
				genpsticky_glbl_jump_req_cmd = gen167_pipex_syncbuf;
			}
			gen518_cyclix_var = gen168_pipex_syncreq;
			if (gen518_cyclix_var) {
				genpsticky_glbl_jump_vector_cmd = gen169_pipex_syncbuf;
			}
			gen519_cyclix_var = gen170_pipex_syncreq;
			if (gen519_cyclix_var) {
				gen520_cyclix_var = gen171_pipex_syncbuf[1];
				genpsticky_glbl_regfile[1] = gen520_cyclix_var;
				gen521_cyclix_var = gen171_pipex_syncbuf[2];
				genpsticky_glbl_regfile[2] = gen521_cyclix_var;
				gen522_cyclix_var = gen171_pipex_syncbuf[3];
				genpsticky_glbl_regfile[3] = gen522_cyclix_var;
				gen523_cyclix_var = gen171_pipex_syncbuf[4];
				genpsticky_glbl_regfile[4] = gen523_cyclix_var;
				gen524_cyclix_var = gen171_pipex_syncbuf[5];
				genpsticky_glbl_regfile[5] = gen524_cyclix_var;
				gen525_cyclix_var = gen171_pipex_syncbuf[6];
				genpsticky_glbl_regfile[6] = gen525_cyclix_var;
				gen526_cyclix_var = gen171_pipex_syncbuf[7];
				genpsticky_glbl_regfile[7] = gen526_cyclix_var;
				gen527_cyclix_var = gen171_pipex_syncbuf[8];
				genpsticky_glbl_regfile[8] = gen527_cyclix_var;
				gen528_cyclix_var = gen171_pipex_syncbuf[9];
				genpsticky_glbl_regfile[9] = gen528_cyclix_var;
				gen529_cyclix_var = gen171_pipex_syncbuf[10];
				genpsticky_glbl_regfile[10] = gen529_cyclix_var;
				gen530_cyclix_var = gen171_pipex_syncbuf[11];
				genpsticky_glbl_regfile[11] = gen530_cyclix_var;
				gen531_cyclix_var = gen171_pipex_syncbuf[12];
				genpsticky_glbl_regfile[12] = gen531_cyclix_var;
				gen532_cyclix_var = gen171_pipex_syncbuf[13];
				genpsticky_glbl_regfile[13] = gen532_cyclix_var;
				gen533_cyclix_var = gen171_pipex_syncbuf[14];
				genpsticky_glbl_regfile[14] = gen533_cyclix_var;
				gen534_cyclix_var = gen171_pipex_syncbuf[15];
				genpsticky_glbl_regfile[15] = gen534_cyclix_var;
				gen535_cyclix_var = gen171_pipex_syncbuf[16];
				genpsticky_glbl_regfile[16] = gen535_cyclix_var;
				gen536_cyclix_var = gen171_pipex_syncbuf[17];
				genpsticky_glbl_regfile[17] = gen536_cyclix_var;
				gen537_cyclix_var = gen171_pipex_syncbuf[18];
				genpsticky_glbl_regfile[18] = gen537_cyclix_var;
				gen538_cyclix_var = gen171_pipex_syncbuf[19];
				genpsticky_glbl_regfile[19] = gen538_cyclix_var;
				gen539_cyclix_var = gen171_pipex_syncbuf[20];
				genpsticky_glbl_regfile[20] = gen539_cyclix_var;
				gen540_cyclix_var = gen171_pipex_syncbuf[21];
				genpsticky_glbl_regfile[21] = gen540_cyclix_var;
				gen541_cyclix_var = gen171_pipex_syncbuf[22];
				genpsticky_glbl_regfile[22] = gen541_cyclix_var;
				gen542_cyclix_var = gen171_pipex_syncbuf[23];
				genpsticky_glbl_regfile[23] = gen542_cyclix_var;
				gen543_cyclix_var = gen171_pipex_syncbuf[24];
				genpsticky_glbl_regfile[24] = gen543_cyclix_var;
				gen544_cyclix_var = gen171_pipex_syncbuf[25];
				genpsticky_glbl_regfile[25] = gen544_cyclix_var;
				gen545_cyclix_var = gen171_pipex_syncbuf[26];
				genpsticky_glbl_regfile[26] = gen545_cyclix_var;
				gen546_cyclix_var = gen171_pipex_syncbuf[27];
				genpsticky_glbl_regfile[27] = gen546_cyclix_var;
				gen547_cyclix_var = gen171_pipex_syncbuf[28];
				genpsticky_glbl_regfile[28] = gen547_cyclix_var;
				gen548_cyclix_var = gen171_pipex_syncbuf[29];
				genpsticky_glbl_regfile[29] = gen548_cyclix_var;
				gen549_cyclix_var = gen171_pipex_syncbuf[30];
				genpsticky_glbl_regfile[30] = gen549_cyclix_var;
				gen550_cyclix_var = gen171_pipex_syncbuf[31];
				genpsticky_glbl_regfile[31] = gen550_cyclix_var;
			}
		}
		gen551_cyclix_var = genpstage_EXEC_genpctrl_finish;
		if (gen551_cyclix_var) {
			genpstage_EXEC_genpctrl_active_glbl = ap_uint<32>(0);
			genpstage_EXEC_genpctrl_killed_glbl = ap_uint<32>(0);
			genpstage_EXEC_genpctrl_stalled_glbl = ap_uint<32>(0);
		}
		gen552_cyclix_var = ~genpstage_EXEC_genpctrl_stalled_glbl;
		genpstage_EXEC_genpctrl_rdy = gen552_cyclix_var;
		genpstage_EXEC_genpctrl_working = (genpstage_EXEC_genpctrl_succ | genpstage_EXEC_genpctrl_stalled_glbl);
		genpstage_IFETCH_genpctrl_succ = ap_uint<32>(0);
		genpstage_IFETCH_genpctrl_working = ap_uint<32>(0);
		gen553_cyclix_var = genpstage_IFETCH_genpctrl_stalled_glbl;
		if (gen553_cyclix_var) {
			genpstage_IFETCH_genpctrl_new = ap_uint<32>(0);
			genpstage_IFETCH_genpctrl_stalled_glbl = ap_uint<32>(0);
			gen554_cyclix_var = !genpstage_IFETCH_genpctrl_killed_glbl;
			genpstage_IFETCH_genpctrl_active_glbl = gen554_cyclix_var;
		}
		gen555_cyclix_var = ap_uint<1>(0);
		gen555_cyclix_var = (gen555_cyclix_var || gen553_cyclix_var);
		gen555_cyclix_var = !gen555_cyclix_var;
		if (gen555_cyclix_var) {
			genpstage_IFETCH_genpctrl_active_glbl = ap_uint<32>(1);
			genpstage_IFETCH_genpctrl_killed_glbl = ap_uint<32>(0);
			genpstage_IFETCH_genpctrl_new = (genpstage_IFETCH_genpctrl_active_glbl || genpstage_IFETCH_genpctrl_killed_glbl);
		}
		genpstage_IFETCH_genpctrl_finish = ap_uint<32>(0);
		genpstage_IFETCH_genpctrl_flushreq = ap_uint<32>(0);
		genpstage_IFETCH_genpctrl_nevictable = ap_uint<32>(0);
		genpstage_IFETCH_genpctrl_occupied = (genpstage_IFETCH_genpctrl_active_glbl | genpstage_IFETCH_genpctrl_killed_glbl);
		genpstage_IFETCH_genpctrl_flushreq = (genpstage_IFETCH_genpctrl_flushreq | genpstage_EXEC_genpctrl_flushreq);
		gen556_cyclix_var = genpstage_IFETCH_genpctrl_occupied;
		if (gen556_cyclix_var) {
			gen557_cyclix_var = genpstage_IFETCH_genpctrl_new;
			if (gen557_cyclix_var) {
				genpstage_IFETCH_instr_req_done = ap_uint<32>(0);
				genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_if_id = ap_uint<32>(0);
				genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_rdreq_pending = ap_uint<32>(0);
				genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_tid = ap_uint<32>(0);
				genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_resp_done = ap_uint<32>(0);
				genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_rdata = ap_uint<32>(0);
			}
			gen558_cyclix_var = genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_rdreq_pending;
			if (gen558_cyclix_var) {
				gen559_cyclix_var = (genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_if_id == ap_uint<1>(0));
				gen560_cyclix_var = gen559_cyclix_var;
				if (gen560_cyclix_var) {
					gen561_cyclix_var = (genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_tid == genmcopipe_instr_mem_rd_ptr);
					gen562_cyclix_var = gen561_cyclix_var;
					if (gen562_cyclix_var) {
						gen563_cyclix_var = genmcopipe_instr_mem_resp.read_nb(gen338_pipex_mcopipe_rdata);
						gen564_cyclix_var = gen563_cyclix_var;
						if (gen564_cyclix_var) {
							genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_rdreq_pending = ap_uint<32>(0);
							genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_resp_done = ap_uint<32>(1);
							genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_rdata = gen338_pipex_mcopipe_rdata;
							genmcopipe_instr_mem_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			gen339_pipex_genpstage_IFETCH_mcopipe_rdreq_inprogress = ap_uint<32>(0);
			gen339_pipex_genpstage_IFETCH_mcopipe_rdreq_inprogress = (gen339_pipex_genpstage_IFETCH_mcopipe_rdreq_inprogress || genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_rdreq_pending);
			gen565_cyclix_var = genpstage_IFETCH_genpctrl_flushreq;
			if (gen565_cyclix_var) {
				gen566_cyclix_var = gen339_pipex_genpstage_IFETCH_mcopipe_rdreq_inprogress;
				if (gen566_cyclix_var) {
					gen567_cyclix_var = genpstage_IFETCH_genpctrl_active_glbl;
					if (gen567_cyclix_var) {
						genpstage_IFETCH_genpctrl_active_glbl = ap_uint<32>(0);
						genpstage_IFETCH_genpctrl_killed_glbl = ap_uint<32>(1);
					}
				}
				gen568_cyclix_var = ap_uint<1>(0);
				gen568_cyclix_var = (gen568_cyclix_var || gen566_cyclix_var);
				gen568_cyclix_var = !gen568_cyclix_var;
				if (gen568_cyclix_var) {
					genpstage_IFETCH_instr_req_done = ap_uint<32>(0);
					genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_if_id = ap_uint<32>(0);
					genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_rdreq_pending = ap_uint<32>(0);
					genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_tid = ap_uint<32>(0);
					genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_resp_done = ap_uint<32>(0);
					genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_rdata = ap_uint<32>(0);
				}
			}
		}
		gen569_cyclix_var = ap_uint<1>(0);
		gen569_cyclix_var = (gen569_cyclix_var || gen556_cyclix_var);
		gen569_cyclix_var = !gen569_cyclix_var;
		if (gen569_cyclix_var) {
			genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_resp_done = ap_uint<32>(0);
			genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_rdreq_pending = ap_uint<32>(0);
		}
		gen163_pipex_syncbuf = genpsticky_glbl_jump_req_cmd;
		gen165_pipex_syncbuf = genpsticky_glbl_pc;
		genpstage_IFETCH_curinstr_addr = genpsticky_glbl_pc;
		gen172_pipex_var = genpsticky_glbl_jump_req_cmd;
		gen570_cyclix_var = gen172_pipex_var;
		if (gen570_cyclix_var) {
			genpstage_IFETCH_curinstr_addr = genpsticky_glbl_jump_vector_cmd;
		}
		gen162_pipex_syncreq = ap_uint<32>(1);
		gen163_pipex_syncbuf = ap_uint<32>(0);
		gen173_pipex_var = (genpstage_IFETCH_curinstr_addr + ap_uint<32>(4));
		genpstage_IFETCH_nextinstr_addr = gen173_pipex_var;
		gen164_pipex_syncreq = ap_uint<32>(1);
		gen165_pipex_syncbuf = genpstage_IFETCH_nextinstr_addr;
		genpstage_IFETCH_instr_busreq.addr = genpstage_IFETCH_curinstr_addr;
		genpstage_IFETCH_instr_busreq.be = ap_uint<32>(15);
		genpstage_IFETCH_instr_busreq.wdata = ap_uint<32>(0);
		gen174_pipex_var = ~genpstage_IFETCH_instr_req_done;
		gen175_pipex_var = gen174_pipex_var;
		gen571_cyclix_var = gen175_pipex_var;
		if (gen571_cyclix_var) {
			gen572_cyclix_var = genpstage_IFETCH_genpctrl_active_glbl;
			if (gen572_cyclix_var) {
				gen573_cyclix_var = ~genmcopipe_instr_mem_full_flag;
				gen574_cyclix_var = gen573_cyclix_var;
				if (gen574_cyclix_var) {
					gen340_pipex_req_struct.we = ap_uint<1>(0);
					gen340_pipex_req_struct.wdata = genpstage_IFETCH_instr_busreq;
					gen575_cyclix_var = genmcopipe_instr_mem_req.write_nb(gen340_pipex_req_struct);
					gen576_cyclix_var = gen575_cyclix_var;
					if (gen576_cyclix_var) {
						gen176_pipex_var = ap_uint<32>(1);
						gen577_cyclix_var = !ap_uint<1>(0);
						genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_rdreq_pending = gen577_cyclix_var;
						genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_tid = genmcopipe_instr_mem_wr_ptr;
						genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_if_id = ap_uint<1>(0);
						gen578_cyclix_var = genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_rdreq_pending;
						if (gen578_cyclix_var) {
							genmcopipe_instr_mem_wr_done = ap_uint<32>(1);
						}
					}
				}
			}
			genpstage_IFETCH_instr_req_done = gen176_pipex_var;
		}
		gen177_pipex_var = ~genpstage_IFETCH_instr_req_done;
		gen178_pipex_var = gen177_pipex_var;
		gen579_cyclix_var = gen178_pipex_var;
		if (gen579_cyclix_var) {
			genpstage_IFETCH_genpctrl_stalled_glbl = (genpstage_IFETCH_genpctrl_stalled_glbl | genpstage_IFETCH_genpctrl_active_glbl);
			genpstage_IFETCH_genpctrl_active_glbl = ap_uint<32>(0);
		}
		genpstage_IFETCH_genpctrl_nevictable = (genpstage_IFETCH_genpctrl_nevictable || genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_rdreq_pending);
		gen580_cyclix_var = ~genpstage_EXEC_genpctrl_rdy;
		gen581_cyclix_var = gen580_cyclix_var;
		if (gen581_cyclix_var) {
			genpstage_IFETCH_genpctrl_stalled_glbl = (genpstage_IFETCH_genpctrl_stalled_glbl | genpstage_IFETCH_genpctrl_active_glbl);
			genpstage_IFETCH_genpctrl_active_glbl = ap_uint<32>(0);
			gen582_cyclix_var = genpstage_IFETCH_genpctrl_nevictable;
			if (gen582_cyclix_var) {
				genpstage_IFETCH_genpctrl_occupied = (genpstage_IFETCH_genpctrl_active_glbl | genpstage_IFETCH_genpctrl_killed_glbl);
				gen583_cyclix_var = genpstage_IFETCH_genpctrl_occupied;
				if (gen583_cyclix_var) {
					genpstage_IFETCH_genpctrl_stalled_glbl = (genpstage_IFETCH_genpctrl_stalled_glbl | ap_uint<32>(1));
				}
			}
		}
		gen584_cyclix_var = genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_rdreq_pending;
		if (gen584_cyclix_var) {
			genpstage_IFETCH_genpctrl_occupied = (genpstage_IFETCH_genpctrl_active_glbl | genpstage_IFETCH_genpctrl_killed_glbl);
			gen585_cyclix_var = genpstage_IFETCH_genpctrl_occupied;
			if (gen585_cyclix_var) {
				genpstage_IFETCH_genpctrl_stalled_glbl = (genpstage_IFETCH_genpctrl_stalled_glbl | ap_uint<32>(1));
			}
		}
		gen586_cyclix_var = genpstage_IFETCH_genpctrl_stalled_glbl;
		if (gen586_cyclix_var) {
			genpstage_IFETCH_genpctrl_finish = ap_uint<32>(0);
			genpstage_IFETCH_genpctrl_succ = ap_uint<32>(0);
		}
		gen587_cyclix_var = ap_uint<1>(0);
		gen587_cyclix_var = (gen587_cyclix_var || gen586_cyclix_var);
		gen587_cyclix_var = !gen587_cyclix_var;
		if (gen587_cyclix_var) {
			genpstage_IFETCH_genpctrl_finish = genpstage_IFETCH_genpctrl_occupied;
			genpstage_IFETCH_genpctrl_succ = genpstage_IFETCH_genpctrl_active_glbl;
		}
		gen588_cyclix_var = genpstage_IFETCH_genpctrl_succ;
		if (gen588_cyclix_var) {
			gen589_cyclix_var = gen162_pipex_syncreq;
			if (gen589_cyclix_var) {
				genpsticky_glbl_jump_req_cmd = gen163_pipex_syncbuf;
			}
			gen590_cyclix_var = gen164_pipex_syncreq;
			if (gen590_cyclix_var) {
				genpsticky_glbl_pc = gen165_pipex_syncbuf;
			}
		}
		gen591_cyclix_var = genpstage_IFETCH_genpctrl_finish;
		if (gen591_cyclix_var) {
			gen592_cyclix_var = genpstage_EXEC_genpctrl_rdy;
			if (gen592_cyclix_var) {
				genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_if_id = genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_if_id;
				genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdreq_pending = genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_rdreq_pending;
				genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_tid = genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_tid;
				genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_resp_done = genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_resp_done;
				genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdata = genpstage_IFETCH_genmcopipe_handle_instr_mem_genvar_rdata;
				genpstage_EXEC_curinstr_addr_genglbl = genpstage_IFETCH_curinstr_addr;
				genpstage_EXEC_nextinstr_addr_genglbl = genpstage_IFETCH_nextinstr_addr;
				genpstage_EXEC_genpctrl_active_glbl = genpstage_IFETCH_genpctrl_active_glbl;
				genpstage_EXEC_genpctrl_killed_glbl = genpstage_IFETCH_genpctrl_killed_glbl;
				genpstage_EXEC_genpctrl_stalled_glbl = ap_uint<32>(0);
			}
			genpstage_IFETCH_genpctrl_active_glbl = ap_uint<32>(0);
			genpstage_IFETCH_genpctrl_killed_glbl = ap_uint<32>(0);
			genpstage_IFETCH_genpctrl_stalled_glbl = ap_uint<32>(0);
		}
		gen593_cyclix_var = ~genpstage_IFETCH_genpctrl_stalled_glbl;
		genpstage_IFETCH_genpctrl_rdy = gen593_cyclix_var;
		genpstage_IFETCH_genpctrl_working = (genpstage_IFETCH_genpctrl_succ | genpstage_IFETCH_genpctrl_stalled_glbl);
		gen594_cyclix_var = genmcopipe_instr_mem_rd_done;
		if (gen594_cyclix_var) {
			genmcopipe_instr_mem_rd_ptr = genmcopipe_instr_mem_rd_ptr_next;
			genmcopipe_instr_mem_full_flag = ap_uint<32>(0);
			gen595_cyclix_var = (genmcopipe_instr_mem_rd_ptr == genmcopipe_instr_mem_wr_ptr);
			gen596_cyclix_var = gen595_cyclix_var;
			if (gen596_cyclix_var) {
				genmcopipe_instr_mem_empty_flag = ap_uint<32>(1);
			}
		}
		gen597_cyclix_var = genmcopipe_instr_mem_wr_done;
		if (gen597_cyclix_var) {
			genmcopipe_instr_mem_wr_ptr = genmcopipe_instr_mem_wr_ptr_next;
			genmcopipe_instr_mem_empty_flag = ap_uint<32>(0);
			gen598_cyclix_var = (genmcopipe_instr_mem_rd_ptr == genmcopipe_instr_mem_wr_ptr);
			gen599_cyclix_var = gen598_cyclix_var;
			if (gen599_cyclix_var) {
				genmcopipe_instr_mem_full_flag = ap_uint<32>(1);
			}
		}
		gen600_cyclix_var = genmcopipe_data_mem_rd_done;
		if (gen600_cyclix_var) {
			genmcopipe_data_mem_rd_ptr = genmcopipe_data_mem_rd_ptr_next;
			genmcopipe_data_mem_full_flag = ap_uint<32>(0);
			gen601_cyclix_var = (genmcopipe_data_mem_rd_ptr == genmcopipe_data_mem_wr_ptr);
			gen602_cyclix_var = gen601_cyclix_var;
			if (gen602_cyclix_var) {
				genmcopipe_data_mem_empty_flag = ap_uint<32>(1);
			}
		}
		gen603_cyclix_var = genmcopipe_data_mem_wr_done;
		if (gen603_cyclix_var) {
			genmcopipe_data_mem_wr_ptr = genmcopipe_data_mem_wr_ptr_next;
			genmcopipe_data_mem_empty_flag = ap_uint<32>(0);
			gen604_cyclix_var = (genmcopipe_data_mem_rd_ptr == genmcopipe_data_mem_wr_ptr);
			gen605_cyclix_var = gen604_cyclix_var;
			if (gen605_cyclix_var) {
				genmcopipe_data_mem_full_flag = ap_uint<32>(1);
			}
		}
	}
}
