// ===========================================================
// HLS sources generated by ActiveCore framework
// Date: 2020-10-25
// Copyright Alexander Antonov <antonov.alex.alex@gmail.com>
// ===========================================================

#include "riscv_1stage.hpp"
#include <ap_int.h>
#include <hls_stream.h>

	ap_uint<32> genpsticky_glbl_pc;
	ap_uint<32> genpsticky_glbl_regfile [32];
	ap_uint<1> genpsticky_glbl_jump_req_cmd;
	ap_uint<32> genpsticky_glbl_jump_vector_cmd;
	ap_uint<8> genpsticky_glbl_CSR_MCAUSE;
	ap_uint<1> genpsticky_glbl_MIRQEN;
	ap_uint<32> genpsticky_glbl_MRETADDR;
	ap_uint<1> genmcopipe_instr_mem_wr_done;
	ap_uint<1> genmcopipe_instr_mem_rd_done;
	ap_uint<1> genmcopipe_instr_mem_full_flag;
	ap_uint<1> genmcopipe_instr_mem_empty_flag;
	ap_uint<1> genmcopipe_instr_mem_wr_ptr;
	ap_uint<1> genmcopipe_instr_mem_rd_ptr;
	ap_uint<1> genmcopipe_data_mem_wr_done;
	ap_uint<1> genmcopipe_data_mem_rd_done;
	ap_uint<1> genmcopipe_data_mem_full_flag;
	ap_uint<1> genmcopipe_data_mem_empty_flag;
	ap_uint<1> genmcopipe_data_mem_wr_ptr;
	ap_uint<1> genmcopipe_data_mem_rd_ptr;
	ap_uint<1> genpstage_EXEC_genpctrl_active_glbl;
	ap_uint<1> genpstage_EXEC_genpctrl_stalled_glbl;
	ap_uint<1> genpstage_EXEC_genpctrl_killed_glbl;
	ap_uint<1> genpstage_EXEC_instr_req_done;
	ap_uint<32> genpstage_EXEC_rs1_rdata;
	ap_uint<32> genpstage_EXEC_rs2_rdata;
	ap_uint<8> genpstage_EXEC_irq_mcause;
	ap_uint<1> genpstage_EXEC_irq_recv;
	ap_uint<1> genpstage_EXEC_data_req_done;
	ap_uint<1> genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_if_id;
	ap_uint<1> genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdreq_pending;
	ap_uint<1> genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_tid;
	ap_uint<1> genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_resp_done;
	ap_uint<32> genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdata;
	ap_uint<1> genpstage_EXEC_genmcopipe_handle_data_mem_genvar_if_id;
	ap_uint<1> genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdreq_pending;
	ap_uint<1> genpstage_EXEC_genmcopipe_handle_data_mem_genvar_tid;
	ap_uint<1> genpstage_EXEC_genmcopipe_handle_data_mem_genvar_resp_done;
	ap_uint<32> genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdata;

void riscv_1stage(ap_uint<1> geninit, hls::stream<ap_uint<8> >& irq_fifo, hls::stream<ap_uint<32> >& genmcopipe_instr_mem_resp, hls::stream<ap_uint<32> >& genmcopipe_data_mem_resp, hls::stream<genpmodule_riscv_1stage_genmcopipe_instr_mem_genstruct_fifo_wdata>& genmcopipe_instr_mem_req, hls::stream<genpmodule_riscv_1stage_genmcopipe_data_mem_genstruct_fifo_wdata>& genmcopipe_data_mem_req) {

	ap_uint<32> genpsticky_glbl_pc_buf;
	ap_uint<32> genpsticky_glbl_regfile_buf [32];
	ap_uint<1> genpsticky_glbl_jump_req_cmd_buf;
	ap_uint<32> genpsticky_glbl_jump_vector_cmd_buf;
	ap_uint<8> genpsticky_glbl_CSR_MCAUSE_buf;
	ap_uint<1> genpsticky_glbl_MIRQEN_buf;
	ap_uint<32> genpsticky_glbl_MRETADDR_buf;
	ap_uint<1> genmcopipe_instr_mem_wr_ptr_next;
	ap_uint<1> genmcopipe_instr_mem_rd_ptr_next;
	ap_uint<1> genmcopipe_data_mem_wr_ptr_next;
	ap_uint<1> genmcopipe_data_mem_rd_ptr_next;
	ap_uint<1> genpstage_EXEC_genpctrl_new;
	ap_uint<1> genpstage_EXEC_genpctrl_working;
	ap_uint<1> genpstage_EXEC_genpctrl_succ;
	ap_uint<1> genpstage_EXEC_genpctrl_occupied;
	ap_uint<1> genpstage_EXEC_genpctrl_finish;
	ap_uint<1> genpstage_EXEC_genpctrl_flushreq;
	ap_uint<1> genpstage_EXEC_genpctrl_nevictable;
	ap_uint<1> genpstage_EXEC_genpctrl_rdy;
	ap_uint<1> gen162_pipex_syncreq;
	ap_uint<1> gen163_pipex_syncbuf;
	ap_uint<1> gen164_pipex_syncreq;
	ap_uint<32> gen165_pipex_syncbuf;
	ap_uint<1> gen166_pipex_syncreq;
	ap_uint<32> gen167_pipex_syncbuf;
	ap_uint<1> gen168_pipex_syncreq;
	ap_uint<32> gen169_pipex_syncbuf [32];
	ap_uint<1> gen170_pipex_var;
	ap_uint<33> gen171_pipex_var;
	ap_uint<1> gen172_pipex_var;
	ap_uint<1> gen173_pipex_var;
	ap_uint<1> gen174_pipex_var;
	ap_uint<1> gen175_pipex_var;
	ap_uint<1> gen176_pipex_var;
	ap_uint<1> gen177_pipex_var;
	ap_uint<1> gen178_pipex_var;
	ap_uint<1> gen179_pipex_var;
	ap_uint<7> gen180_pipex_var;
	ap_uint<20> gen181_pipex_var;
	ap_uint<25> gen182_pipex_var;
	ap_uint<12> gen183_pipex_var;
	ap_uint<15> gen184_pipex_var;
	ap_uint<32> gen185_pipex_var;
	ap_uint<25> gen186_pipex_var;
	ap_uint<28> gen187_pipex_var;
	ap_uint<24> gen188_pipex_var;
	ap_uint<32> gen189_pipex_var;
	ap_uint<20> gen190_pipex_var;
	ap_uint<32> gen191_pipex_var;
	ap_uint<1> gen192_pipex_var;
	ap_uint<32> gen193_pipex_var;
	ap_uint<32> gen194_pipex_var;
	ap_uint<12> gen195_pipex_var;
	ap_uint<12> gen196_pipex_var;
	ap_uint<1> gen197_pipex_var;
	ap_uint<32> gen198_pipex_var;
	ap_uint<1> gen199_pipex_var;
	ap_uint<1> gen200_pipex_var;
	ap_uint<31> gen201_pipex_var;
	ap_uint<12> gen202_pipex_var;
	ap_uint<13> gen203_pipex_var;
	ap_uint<1> gen204_pipex_var;
	ap_uint<32> gen205_pipex_var;
	ap_uint<32> gen206_pipex_var;
	ap_uint<32> gen207_pipex_var;
	ap_uint<1> gen208_pipex_var;
	ap_uint<20> gen209_pipex_var;
	ap_uint<1> gen210_pipex_var;
	ap_uint<31> gen211_pipex_var;
	ap_uint<21> gen212_pipex_var;
	ap_uint<1> gen213_pipex_var;
	ap_uint<32> gen214_pipex_var;
	ap_uint<1> gen215_pipex_var;
	ap_uint<1> gen216_pipex_var;
	ap_uint<1> gen217_pipex_var;
	ap_uint<1> gen218_pipex_var;
	ap_uint<25> gen219_pipex_var;
	ap_uint<32> gen220_pipex_var;
	ap_uint<1> gen221_pipex_var;
	ap_uint<1> gen222_pipex_var;
	ap_uint<1> gen223_pipex_var;
	ap_uint<25> gen224_pipex_var;
	ap_uint<32> gen225_pipex_var;
	ap_uint<1> gen226_pipex_var;
	ap_uint<1> gen227_pipex_var;
	ap_uint<1> gen228_pipex_var;
	ap_uint<1> gen229_pipex_var;
	ap_uint<1> gen230_pipex_var;
	ap_uint<1> gen231_pipex_var;
	ap_uint<1> gen232_pipex_var;
	ap_uint<1> gen233_pipex_var;
	ap_uint<1> gen234_pipex_var;
	ap_uint<32> gen235_pipex_var;
	ap_uint<32> gen236_pipex_var;
	ap_uint<32> gen237_pipex_var;
	ap_uint<1> gen238_pipex_var;
	ap_uint<1> gen239_pipex_var;
	ap_uint<1> gen240_pipex_var;
	ap_uint<1> gen241_pipex_var;
	ap_uint<1> gen242_pipex_var;
	ap_uint<32> gen243_pipex_var [32];
	ap_uint<32> gen244_pipex_var;
	ap_uint<32> gen245_pipex_var [32];
	ap_uint<32> gen246_pipex_var;
	ap_uint<1> gen247_pipex_var;
	ap_uint<1> gen248_pipex_var;
	ap_uint<1> gen249_pipex_var;
	ap_uint<1> gen250_pipex_var;
	ap_uint<1> gen251_pipex_var;
	ap_uint<1> gen252_pipex_var;
	ap_uint<33> gen253_pipex_var;
	ap_uint<33> gen254_pipex_var;
	ap_uint<1> gen255_pipex_var;
	ap_uint<1> gen256_pipex_var;
	ap_uint<33> gen257_pipex_var;
	ap_uint<1> gen258_pipex_var;
	ap_uint<33> gen259_pipex_var;
	ap_uint<1> gen260_pipex_var;
	ap_uint<1> gen261_pipex_var;
	ap_uint<1> gen262_pipex_var;
	ap_uint<1> gen263_pipex_var;
	ap_uint<1> gen264_pipex_var;
	ap_uint<1> gen265_pipex_var;
	ap_uint<1> gen266_pipex_var;
	ap_uint<34> gen267_pipex_var;
	ap_uint<34> gen268_pipex_var;
	ap_uint<33> gen269_pipex_var;
	ap_uint<33> gen270_pipex_var;
	ap_uint<33> gen271_pipex_var;
	ap_uint<32> gen272_pipex_var;
	ap_uint<64> gen273_pipex_var;
	ap_uint<5> gen274_pipex_var;
	ap_uint<64> gen275_pipex_var;
	ap_uint<32> gen276_pipex_var;
	ap_uint<1> gen277_pipex_var;
	ap_uint<64> gen278_pipex_var;
	ap_uint<5> gen279_pipex_var;
	ap_uint<64> gen280_pipex_var;
	ap_uint<33> gen281_pipex_var;
	ap_uint<33> gen282_pipex_var;
	ap_uint<33> gen283_pipex_var;
	ap_uint<32> gen284_pipex_var;
	ap_uint<1> gen285_pipex_var;
	ap_uint<1> gen286_pipex_var;
	ap_uint<1> gen287_pipex_var;
	ap_uint<1> gen288_pipex_var;
	ap_uint<1> gen289_pipex_var;
	ap_uint<1> gen290_pipex_var;
	ap_uint<1> gen291_pipex_var;
	ap_uint<1> gen292_pipex_var;
	ap_uint<1> gen293_pipex_var;
	ap_uint<1> gen294_pipex_var;
	ap_uint<1> gen295_pipex_var;
	ap_uint<1> gen296_pipex_var;
	ap_uint<1> gen297_pipex_var;
	ap_uint<1> gen298_pipex_var;
	ap_uint<1> gen299_pipex_var;
	ap_uint<1> gen300_pipex_var;
	ap_uint<1> gen301_pipex_var;
	ap_uint<1> gen302_pipex_var;
	ap_uint<1> gen303_pipex_var;
	ap_uint<1> gen304_pipex_var;
	ap_uint<33> gen305_pipex_var;
	ap_uint<1> gen306_pipex_var;
	ap_uint<1> gen307_pipex_var;
	ap_uint<1> gen308_pipex_var;
	ap_uint<1> gen309_pipex_var;
	ap_uint<1> gen310_pipex_var;
	ap_uint<1> gen311_pipex_var;
	ap_uint<1> gen312_pipex_var;
	ap_uint<1> gen313_pipex_var;
	ap_uint<1> gen314_pipex_var;
	ap_uint<1> gen315_pipex_var;
	ap_uint<1> gen316_pipex_var;
	ap_uint<1> gen317_pipex_var;
	ap_uint<1> gen318_pipex_var;
	ap_uint<1> gen319_pipex_var;
	ap_uint<1> gen320_pipex_var;
	ap_uint<1> gen321_pipex_var;
	ap_uint<1> gen322_pipex_var;
	ap_uint<1> gen323_pipex_var;
	ap_uint<1> gen324_pipex_var;
	ap_uint<1> gen325_pipex_var;
	ap_uint<1> gen326_pipex_var;
	ap_uint<1> gen327_pipex_var;
	ap_uint<1> gen328_pipex_var;
	ap_uint<1> gen329_pipex_var;
	ap_uint<1> gen330_pipex_var;
	ap_uint<1> gen331_pipex_var;
	ap_uint<32> genpstage_EXEC_curinstr_addr;
	ap_uint<32> genpstage_EXEC_nextinstr_addr;
	riscv_1stage_busreq_mem_struct genpstage_EXEC_instr_busreq;
	ap_uint<32> genpstage_EXEC_instr_code;
	ap_uint<7> genpstage_EXEC_opcode;
	ap_uint<1> genpstage_EXEC_alu_unsigned;
	ap_uint<5> genpstage_EXEC_rs1_addr;
	ap_uint<5> genpstage_EXEC_rs2_addr;
	ap_uint<5> genpstage_EXEC_rd_addr;
	ap_uint<3> genpstage_EXEC_funct3;
	ap_uint<7> genpstage_EXEC_funct7;
	ap_uint<5> genpstage_EXEC_shamt;
	ap_uint<4> genpstage_EXEC_pred;
	ap_uint<4> genpstage_EXEC_succ;
	ap_uint<12> genpstage_EXEC_csrnum;
	ap_uint<5> genpstage_EXEC_zimm;
	ap_uint<32> genpstage_EXEC_immediate_I;
	ap_uint<32> genpstage_EXEC_immediate_S;
	ap_uint<32> genpstage_EXEC_immediate_B;
	ap_uint<32> genpstage_EXEC_immediate_U;
	ap_uint<32> genpstage_EXEC_immediate_J;
	ap_uint<2> genpstage_EXEC_op1_source;
	ap_uint<1> genpstage_EXEC_rd_req;
	ap_uint<3> genpstage_EXEC_rd_source;
	ap_uint<32> genpstage_EXEC_immediate;
	ap_uint<2> genpstage_EXEC_op2_source;
	ap_uint<1> genpstage_EXEC_alu_req;
	ap_uint<4> genpstage_EXEC_alu_opcode;
	ap_uint<1> genpstage_EXEC_jump_req;
	ap_uint<1> genpstage_EXEC_jump_src;
	ap_uint<1> genpstage_EXEC_rs1_req;
	ap_uint<1> genpstage_EXEC_rs2_req;
	ap_uint<1> genpstage_EXEC_jump_req_cond;
	ap_uint<1> genpstage_EXEC_mem_req;
	ap_uint<1> genpstage_EXEC_mem_cmd;
	ap_uint<1> genpstage_EXEC_fencereq;
	ap_uint<1> genpstage_EXEC_ebreakreq;
	ap_uint<1> genpstage_EXEC_ecallreq;
	ap_uint<1> genpstage_EXEC_csrreq;
	ap_uint<4> genpstage_EXEC_mem_be;
	ap_uint<1> genpstage_EXEC_mret_req;
	ap_uint<32> genpstage_EXEC_csr_rdata;
	ap_uint<32> genpstage_EXEC_alu_op1;
	ap_uint<32> genpstage_EXEC_alu_op2;
	ap_uint<33> genpstage_EXEC_alu_op1_wide;
	ap_uint<33> genpstage_EXEC_alu_op2_wide;
	ap_uint<33> genpstage_EXEC_alu_result_wide;
	ap_uint<32> genpstage_EXEC_alu_result;
	ap_uint<1> genpstage_EXEC_alu_CF;
	ap_uint<1> genpstage_EXEC_alu_SF;
	ap_uint<1> genpstage_EXEC_alu_ZF;
	ap_uint<1> genpstage_EXEC_alu_OF;
	ap_uint<1> genpstage_EXEC_alu_overflow;
	ap_uint<32> genpstage_EXEC_rd_wdata;
	ap_uint<1> genpstage_EXEC_rd_rdy;
	ap_uint<32> genpstage_EXEC_curinstraddr_imm;
	ap_uint<32> genpstage_EXEC_jump_vector;
	ap_uint<32> genpstage_EXEC_mem_addr;
	ap_uint<32> genpstage_EXEC_mem_wdata;
	riscv_1stage_busreq_mem_struct genpstage_EXEC_data_busreq;
	ap_uint<32> genpstage_EXEC_mem_rdata;
	ap_uint<32> gen332_pipex_mcopipe_rdata;
	ap_uint<32> gen333_pipex_mcopipe_rdata;
	ap_uint<1> gen334_pipex_genpstage_EXEC_mcopipe_rdreq_inprogress;
	genpmodule_riscv_1stage_genmcopipe_instr_mem_genstruct_fifo_wdata gen335_pipex_req_struct;
	genpmodule_riscv_1stage_genmcopipe_data_mem_genstruct_fifo_wdata gen336_pipex_req_struct;
	ap_uint<32> gen275_cyclix_var;
	ap_uint<32> gen276_cyclix_var;
	ap_uint<32> gen277_cyclix_var;
	ap_uint<32> gen278_cyclix_var;
	ap_uint<32> gen279_cyclix_var;
	ap_uint<32> gen280_cyclix_var;
	ap_uint<32> gen281_cyclix_var;
	ap_uint<32> gen282_cyclix_var;
	ap_uint<32> gen283_cyclix_var;
	ap_uint<32> gen284_cyclix_var;
	ap_uint<32> gen285_cyclix_var;
	ap_uint<32> gen286_cyclix_var;
	ap_uint<32> gen287_cyclix_var;
	ap_uint<32> gen288_cyclix_var;
	ap_uint<32> gen289_cyclix_var;
	ap_uint<32> gen290_cyclix_var;
	ap_uint<32> gen291_cyclix_var;
	ap_uint<32> gen292_cyclix_var;
	ap_uint<32> gen293_cyclix_var;
	ap_uint<32> gen294_cyclix_var;
	ap_uint<32> gen295_cyclix_var;
	ap_uint<32> gen296_cyclix_var;
	ap_uint<32> gen297_cyclix_var;
	ap_uint<32> gen298_cyclix_var;
	ap_uint<32> gen299_cyclix_var;
	ap_uint<32> gen300_cyclix_var;
	ap_uint<32> gen301_cyclix_var;
	ap_uint<32> gen302_cyclix_var;
	ap_uint<32> gen303_cyclix_var;
	ap_uint<32> gen304_cyclix_var;
	ap_uint<32> gen305_cyclix_var;
	ap_uint<1> gen306_cyclix_var;
	ap_uint<1> gen307_cyclix_var;
	ap_uint<1> gen308_cyclix_var;
	ap_uint<1> gen309_cyclix_var;
	ap_uint<1> gen310_cyclix_var;
	ap_uint<1> gen311_cyclix_var;
	ap_uint<1> gen312_cyclix_var;
	ap_uint<1> gen313_cyclix_var;
	ap_uint<1> gen314_cyclix_var;
	ap_uint<1> gen315_cyclix_var;
	ap_uint<1> gen316_cyclix_var;
	ap_uint<1> gen317_cyclix_var;
	ap_uint<1> gen318_cyclix_var;
	ap_uint<1> gen319_cyclix_var;
	ap_uint<1> gen320_cyclix_var;
	ap_uint<1> gen321_cyclix_var;
	ap_uint<1> gen322_cyclix_var;
	ap_uint<1> gen323_cyclix_var;
	ap_uint<1> gen324_cyclix_var;
	ap_uint<1> gen325_cyclix_var;
	ap_uint<1> gen326_cyclix_var;
	ap_uint<1> gen327_cyclix_var;
	ap_uint<1> gen328_cyclix_var;
	ap_uint<1> gen329_cyclix_var;
	ap_uint<32> gen330_cyclix_var;
	ap_uint<32> gen331_cyclix_var;
	ap_uint<32> gen332_cyclix_var;
	ap_uint<32> gen333_cyclix_var;
	ap_uint<32> gen334_cyclix_var;
	ap_uint<32> gen335_cyclix_var;
	ap_uint<32> gen336_cyclix_var;
	ap_uint<32> gen337_cyclix_var;
	ap_uint<32> gen338_cyclix_var;
	ap_uint<32> gen339_cyclix_var;
	ap_uint<32> gen340_cyclix_var;
	ap_uint<32> gen341_cyclix_var;
	ap_uint<32> gen342_cyclix_var;
	ap_uint<32> gen343_cyclix_var;
	ap_uint<32> gen344_cyclix_var;
	ap_uint<32> gen345_cyclix_var;
	ap_uint<32> gen346_cyclix_var;
	ap_uint<32> gen347_cyclix_var;
	ap_uint<32> gen348_cyclix_var;
	ap_uint<32> gen349_cyclix_var;
	ap_uint<32> gen350_cyclix_var;
	ap_uint<32> gen351_cyclix_var;
	ap_uint<32> gen352_cyclix_var;
	ap_uint<32> gen353_cyclix_var;
	ap_uint<32> gen354_cyclix_var;
	ap_uint<32> gen355_cyclix_var;
	ap_uint<32> gen356_cyclix_var;
	ap_uint<32> gen357_cyclix_var;
	ap_uint<32> gen358_cyclix_var;
	ap_uint<32> gen359_cyclix_var;
	ap_uint<32> gen360_cyclix_var;
	ap_uint<1> gen361_cyclix_var;
	ap_uint<1> gen362_cyclix_var;
	ap_uint<1> gen363_cyclix_var;
	ap_uint<1> gen364_cyclix_var;
	ap_uint<1> gen365_cyclix_var;
	ap_uint<1> gen366_cyclix_var;
	ap_uint<1> gen367_cyclix_var;
	ap_uint<1> gen368_cyclix_var;
	ap_uint<1> gen369_cyclix_var;
	ap_uint<1> gen370_cyclix_var;
	ap_uint<1> gen371_cyclix_var;
	ap_uint<1> gen372_cyclix_var;
	ap_uint<1> gen373_cyclix_var;
	ap_uint<1> gen374_cyclix_var;
	ap_uint<1> gen375_cyclix_var;
	ap_uint<1> gen376_cyclix_var;
	ap_uint<1> gen377_cyclix_var;
	ap_uint<1> gen378_cyclix_var;
	ap_uint<1> gen379_cyclix_var;
	ap_uint<1> gen380_cyclix_var;
	ap_uint<1> gen381_cyclix_var;
	ap_uint<1> gen382_cyclix_var;
	ap_uint<1> gen383_cyclix_var;
	ap_uint<1> gen384_cyclix_var;
	ap_uint<32> gen385_cyclix_var;
	ap_uint<32> gen386_cyclix_var;
	ap_uint<32> gen387_cyclix_var;
	ap_uint<32> gen388_cyclix_var;
	ap_uint<32> gen389_cyclix_var;
	ap_uint<32> gen390_cyclix_var;
	ap_uint<32> gen391_cyclix_var;
	ap_uint<32> gen392_cyclix_var;
	ap_uint<32> gen393_cyclix_var;
	ap_uint<32> gen394_cyclix_var;
	ap_uint<32> gen395_cyclix_var;
	ap_uint<32> gen396_cyclix_var;
	ap_uint<32> gen397_cyclix_var;
	ap_uint<32> gen398_cyclix_var;
	ap_uint<32> gen399_cyclix_var;
	ap_uint<32> gen400_cyclix_var;
	ap_uint<32> gen401_cyclix_var;
	ap_uint<32> gen402_cyclix_var;
	ap_uint<32> gen403_cyclix_var;
	ap_uint<32> gen404_cyclix_var;
	ap_uint<32> gen405_cyclix_var;
	ap_uint<32> gen406_cyclix_var;
	ap_uint<32> gen407_cyclix_var;
	ap_uint<32> gen408_cyclix_var;
	ap_uint<32> gen409_cyclix_var;
	ap_uint<32> gen410_cyclix_var;
	ap_uint<32> gen411_cyclix_var;
	ap_uint<32> gen412_cyclix_var;
	ap_uint<32> gen413_cyclix_var;
	ap_uint<32> gen414_cyclix_var;
	ap_uint<32> gen415_cyclix_var;
	ap_uint<32> gen416_cyclix_var;
	ap_uint<32> gen417_cyclix_var;
	ap_uint<32> gen418_cyclix_var;
	ap_uint<32> gen419_cyclix_var;
	ap_uint<32> gen420_cyclix_var;
	ap_uint<32> gen421_cyclix_var;
	ap_uint<32> gen422_cyclix_var;
	ap_uint<32> gen423_cyclix_var;
	ap_uint<32> gen424_cyclix_var;
	ap_uint<32> gen425_cyclix_var;
	ap_uint<32> gen426_cyclix_var;
	ap_uint<32> gen427_cyclix_var;
	ap_uint<32> gen428_cyclix_var;
	ap_uint<32> gen429_cyclix_var;
	ap_uint<32> gen430_cyclix_var;
	ap_uint<32> gen431_cyclix_var;
	ap_uint<32> gen432_cyclix_var;
	ap_uint<32> gen433_cyclix_var;
	ap_uint<32> gen434_cyclix_var;
	ap_uint<32> gen435_cyclix_var;
	ap_uint<32> gen436_cyclix_var;
	ap_uint<32> gen437_cyclix_var;
	ap_uint<32> gen438_cyclix_var;
	ap_uint<32> gen439_cyclix_var;
	ap_uint<32> gen440_cyclix_var;
	ap_uint<32> gen441_cyclix_var;
	ap_uint<32> gen442_cyclix_var;
	ap_uint<32> gen443_cyclix_var;
	ap_uint<32> gen444_cyclix_var;
	ap_uint<32> gen445_cyclix_var;
	ap_uint<32> gen446_cyclix_var;
	ap_uint<1> gen447_cyclix_var;
	ap_uint<1> gen448_cyclix_var;
	ap_uint<1> gen449_cyclix_var;
	ap_uint<1> gen450_cyclix_var;
	ap_uint<1> gen451_cyclix_var;
	ap_uint<1> gen452_cyclix_var;
	ap_uint<1> gen453_cyclix_var;
	ap_uint<1> gen454_cyclix_var;
	ap_uint<1> gen455_cyclix_var;
	ap_uint<1> gen456_cyclix_var;
	ap_uint<1> gen457_cyclix_var;
	ap_uint<1> gen458_cyclix_var;
	ap_uint<1> gen459_cyclix_var;
	ap_uint<1> gen460_cyclix_var;
	ap_uint<1> gen461_cyclix_var;
	ap_uint<1> gen462_cyclix_var;
	ap_uint<1> gen463_cyclix_var;
	ap_uint<1> gen464_cyclix_var;
	ap_uint<1> gen465_cyclix_var;
	ap_uint<1> gen466_cyclix_var;
	ap_uint<1> gen467_cyclix_var;
	ap_uint<1> gen468_cyclix_var;
	ap_uint<1> gen469_cyclix_var;
	ap_uint<1> gen470_cyclix_var;
	ap_uint<1> gen471_cyclix_var;
	ap_uint<1> gen472_cyclix_var;
	ap_uint<1> gen473_cyclix_var;
	ap_uint<1> gen474_cyclix_var;
	ap_uint<1> gen475_cyclix_var;
	ap_uint<1> gen476_cyclix_var;
	ap_uint<1> gen477_cyclix_var;
	ap_uint<1> gen478_cyclix_var;
	ap_uint<1> gen479_cyclix_var;
	ap_uint<1> gen480_cyclix_var;
	ap_uint<1> gen481_cyclix_var;
	ap_uint<1> gen482_cyclix_var;
	ap_uint<1> gen483_cyclix_var;
	ap_uint<1> gen484_cyclix_var;
	ap_uint<1> gen485_cyclix_var;
	ap_uint<1> gen486_cyclix_var;
	ap_uint<1> gen487_cyclix_var;
	ap_uint<1> gen488_cyclix_var;
	ap_uint<1> gen489_cyclix_var;
	ap_uint<1> gen490_cyclix_var;
	ap_uint<1> gen491_cyclix_var;
	ap_uint<1> gen492_cyclix_var;
	ap_uint<1> gen493_cyclix_var;
	ap_uint<1> gen494_cyclix_var;
	ap_uint<1> gen495_cyclix_var;
	ap_uint<1> gen496_cyclix_var;
	ap_uint<1> gen497_cyclix_var;
	ap_uint<1> gen498_cyclix_var;
	ap_uint<1> gen499_cyclix_var;
	ap_uint<1> gen500_cyclix_var;
	ap_uint<1> gen501_cyclix_var;
	ap_uint<1> gen502_cyclix_var;
	ap_uint<1> gen503_cyclix_var;
	ap_uint<1> gen504_cyclix_var;
	ap_uint<32> gen505_cyclix_var;
	ap_uint<32> gen506_cyclix_var;
	ap_uint<32> gen507_cyclix_var;
	ap_uint<32> gen508_cyclix_var;
	ap_uint<32> gen509_cyclix_var;
	ap_uint<32> gen510_cyclix_var;
	ap_uint<32> gen511_cyclix_var;
	ap_uint<32> gen512_cyclix_var;
	ap_uint<32> gen513_cyclix_var;
	ap_uint<32> gen514_cyclix_var;
	ap_uint<32> gen515_cyclix_var;
	ap_uint<32> gen516_cyclix_var;
	ap_uint<32> gen517_cyclix_var;
	ap_uint<32> gen518_cyclix_var;
	ap_uint<32> gen519_cyclix_var;
	ap_uint<32> gen520_cyclix_var;
	ap_uint<32> gen521_cyclix_var;
	ap_uint<32> gen522_cyclix_var;
	ap_uint<32> gen523_cyclix_var;
	ap_uint<32> gen524_cyclix_var;
	ap_uint<32> gen525_cyclix_var;
	ap_uint<32> gen526_cyclix_var;
	ap_uint<32> gen527_cyclix_var;
	ap_uint<32> gen528_cyclix_var;
	ap_uint<32> gen529_cyclix_var;
	ap_uint<32> gen530_cyclix_var;
	ap_uint<32> gen531_cyclix_var;
	ap_uint<32> gen532_cyclix_var;
	ap_uint<32> gen533_cyclix_var;
	ap_uint<32> gen534_cyclix_var;
	ap_uint<32> gen535_cyclix_var;
	ap_uint<1> gen536_cyclix_var;
	ap_uint<1> gen537_cyclix_var;
	ap_uint<1> gen538_cyclix_var;
	ap_uint<1> gen539_cyclix_var;
	ap_uint<1> gen540_cyclix_var;
	ap_uint<1> gen541_cyclix_var;
	ap_uint<1> gen542_cyclix_var;
	ap_uint<1> gen543_cyclix_var;
	ap_uint<1> gen544_cyclix_var;
	ap_uint<1> gen545_cyclix_var;
	ap_uint<1> gen546_cyclix_var;
	ap_uint<1> gen547_cyclix_var;
	ap_uint<1> gen548_cyclix_var;
	ap_uint<1> gen549_cyclix_var;

	if (geninit) {
		genpsticky_glbl_pc = 512;
		genpsticky_glbl_regfile[1] = 0;
		genpsticky_glbl_regfile[2] = 0;
		genpsticky_glbl_regfile[3] = 0;
		genpsticky_glbl_regfile[4] = 0;
		genpsticky_glbl_regfile[5] = 0;
		genpsticky_glbl_regfile[6] = 0;
		genpsticky_glbl_regfile[7] = 0;
		genpsticky_glbl_regfile[8] = 0;
		genpsticky_glbl_regfile[9] = 0;
		genpsticky_glbl_regfile[10] = 0;
		genpsticky_glbl_regfile[11] = 0;
		genpsticky_glbl_regfile[12] = 0;
		genpsticky_glbl_regfile[13] = 0;
		genpsticky_glbl_regfile[14] = 0;
		genpsticky_glbl_regfile[15] = 0;
		genpsticky_glbl_regfile[16] = 0;
		genpsticky_glbl_regfile[17] = 0;
		genpsticky_glbl_regfile[18] = 0;
		genpsticky_glbl_regfile[19] = 0;
		genpsticky_glbl_regfile[20] = 0;
		genpsticky_glbl_regfile[21] = 0;
		genpsticky_glbl_regfile[22] = 0;
		genpsticky_glbl_regfile[23] = 0;
		genpsticky_glbl_regfile[24] = 0;
		genpsticky_glbl_regfile[25] = 0;
		genpsticky_glbl_regfile[26] = 0;
		genpsticky_glbl_regfile[27] = 0;
		genpsticky_glbl_regfile[28] = 0;
		genpsticky_glbl_regfile[29] = 0;
		genpsticky_glbl_regfile[30] = 0;
		genpsticky_glbl_regfile[31] = 0;
		genpsticky_glbl_jump_req_cmd = 0;
		genpsticky_glbl_jump_vector_cmd = 0;
		genpsticky_glbl_CSR_MCAUSE = 0;
		genpsticky_glbl_MIRQEN = 1;
		genpsticky_glbl_MRETADDR = 0;
		genmcopipe_instr_mem_wr_done = 0;
		genmcopipe_instr_mem_rd_done = 0;
		genmcopipe_instr_mem_full_flag = 0;
		genmcopipe_instr_mem_empty_flag = 1;
		genmcopipe_instr_mem_wr_ptr = 0;
		genmcopipe_instr_mem_rd_ptr = 0;
		genmcopipe_data_mem_wr_done = 0;
		genmcopipe_data_mem_rd_done = 0;
		genmcopipe_data_mem_full_flag = 0;
		genmcopipe_data_mem_empty_flag = 1;
		genmcopipe_data_mem_wr_ptr = 0;
		genmcopipe_data_mem_rd_ptr = 0;
		genpstage_EXEC_genpctrl_active_glbl = 0;
		genpstage_EXEC_genpctrl_stalled_glbl = 0;
		genpstage_EXEC_genpctrl_killed_glbl = 0;
		genpstage_EXEC_instr_req_done = 0;
		genpstage_EXEC_rs1_rdata = 0;
		genpstage_EXEC_rs2_rdata = 0;
		genpstage_EXEC_irq_mcause = 0;
		genpstage_EXEC_irq_recv = 0;
		genpstage_EXEC_data_req_done = 0;
		genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_if_id = 0;
		genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdreq_pending = 0;
		genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_tid = 0;
		genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_resp_done = 0;
		genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdata = 0;
		genpstage_EXEC_genmcopipe_handle_data_mem_genvar_if_id = 0;
		genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdreq_pending = 0;
		genpstage_EXEC_genmcopipe_handle_data_mem_genvar_tid = 0;
		genpstage_EXEC_genmcopipe_handle_data_mem_genvar_resp_done = 0;
		genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdata = 0;

	} else {
		genmcopipe_instr_mem_wr_done = ap_uint<32>(0);
		genmcopipe_instr_mem_rd_done = ap_uint<32>(0);
		genmcopipe_instr_mem_wr_ptr_next = (genmcopipe_instr_mem_wr_ptr + ap_uint<32>(1));
		genmcopipe_instr_mem_rd_ptr_next = (genmcopipe_instr_mem_rd_ptr + ap_uint<32>(1));
		genmcopipe_data_mem_wr_done = ap_uint<32>(0);
		genmcopipe_data_mem_rd_done = ap_uint<32>(0);
		genmcopipe_data_mem_wr_ptr_next = (genmcopipe_data_mem_wr_ptr + ap_uint<32>(1));
		genmcopipe_data_mem_rd_ptr_next = (genmcopipe_data_mem_rd_ptr + ap_uint<32>(1));
		genpsticky_glbl_pc_buf = genpsticky_glbl_pc;
		gen275_cyclix_var = genpsticky_glbl_regfile[1];
		genpsticky_glbl_regfile_buf[1] = gen275_cyclix_var;
		gen276_cyclix_var = genpsticky_glbl_regfile[2];
		genpsticky_glbl_regfile_buf[2] = gen276_cyclix_var;
		gen277_cyclix_var = genpsticky_glbl_regfile[3];
		genpsticky_glbl_regfile_buf[3] = gen277_cyclix_var;
		gen278_cyclix_var = genpsticky_glbl_regfile[4];
		genpsticky_glbl_regfile_buf[4] = gen278_cyclix_var;
		gen279_cyclix_var = genpsticky_glbl_regfile[5];
		genpsticky_glbl_regfile_buf[5] = gen279_cyclix_var;
		gen280_cyclix_var = genpsticky_glbl_regfile[6];
		genpsticky_glbl_regfile_buf[6] = gen280_cyclix_var;
		gen281_cyclix_var = genpsticky_glbl_regfile[7];
		genpsticky_glbl_regfile_buf[7] = gen281_cyclix_var;
		gen282_cyclix_var = genpsticky_glbl_regfile[8];
		genpsticky_glbl_regfile_buf[8] = gen282_cyclix_var;
		gen283_cyclix_var = genpsticky_glbl_regfile[9];
		genpsticky_glbl_regfile_buf[9] = gen283_cyclix_var;
		gen284_cyclix_var = genpsticky_glbl_regfile[10];
		genpsticky_glbl_regfile_buf[10] = gen284_cyclix_var;
		gen285_cyclix_var = genpsticky_glbl_regfile[11];
		genpsticky_glbl_regfile_buf[11] = gen285_cyclix_var;
		gen286_cyclix_var = genpsticky_glbl_regfile[12];
		genpsticky_glbl_regfile_buf[12] = gen286_cyclix_var;
		gen287_cyclix_var = genpsticky_glbl_regfile[13];
		genpsticky_glbl_regfile_buf[13] = gen287_cyclix_var;
		gen288_cyclix_var = genpsticky_glbl_regfile[14];
		genpsticky_glbl_regfile_buf[14] = gen288_cyclix_var;
		gen289_cyclix_var = genpsticky_glbl_regfile[15];
		genpsticky_glbl_regfile_buf[15] = gen289_cyclix_var;
		gen290_cyclix_var = genpsticky_glbl_regfile[16];
		genpsticky_glbl_regfile_buf[16] = gen290_cyclix_var;
		gen291_cyclix_var = genpsticky_glbl_regfile[17];
		genpsticky_glbl_regfile_buf[17] = gen291_cyclix_var;
		gen292_cyclix_var = genpsticky_glbl_regfile[18];
		genpsticky_glbl_regfile_buf[18] = gen292_cyclix_var;
		gen293_cyclix_var = genpsticky_glbl_regfile[19];
		genpsticky_glbl_regfile_buf[19] = gen293_cyclix_var;
		gen294_cyclix_var = genpsticky_glbl_regfile[20];
		genpsticky_glbl_regfile_buf[20] = gen294_cyclix_var;
		gen295_cyclix_var = genpsticky_glbl_regfile[21];
		genpsticky_glbl_regfile_buf[21] = gen295_cyclix_var;
		gen296_cyclix_var = genpsticky_glbl_regfile[22];
		genpsticky_glbl_regfile_buf[22] = gen296_cyclix_var;
		gen297_cyclix_var = genpsticky_glbl_regfile[23];
		genpsticky_glbl_regfile_buf[23] = gen297_cyclix_var;
		gen298_cyclix_var = genpsticky_glbl_regfile[24];
		genpsticky_glbl_regfile_buf[24] = gen298_cyclix_var;
		gen299_cyclix_var = genpsticky_glbl_regfile[25];
		genpsticky_glbl_regfile_buf[25] = gen299_cyclix_var;
		gen300_cyclix_var = genpsticky_glbl_regfile[26];
		genpsticky_glbl_regfile_buf[26] = gen300_cyclix_var;
		gen301_cyclix_var = genpsticky_glbl_regfile[27];
		genpsticky_glbl_regfile_buf[27] = gen301_cyclix_var;
		gen302_cyclix_var = genpsticky_glbl_regfile[28];
		genpsticky_glbl_regfile_buf[28] = gen302_cyclix_var;
		gen303_cyclix_var = genpsticky_glbl_regfile[29];
		genpsticky_glbl_regfile_buf[29] = gen303_cyclix_var;
		gen304_cyclix_var = genpsticky_glbl_regfile[30];
		genpsticky_glbl_regfile_buf[30] = gen304_cyclix_var;
		gen305_cyclix_var = genpsticky_glbl_regfile[31];
		genpsticky_glbl_regfile_buf[31] = gen305_cyclix_var;
		genpsticky_glbl_jump_req_cmd_buf = genpsticky_glbl_jump_req_cmd;
		genpsticky_glbl_jump_vector_cmd_buf = genpsticky_glbl_jump_vector_cmd;
		genpsticky_glbl_CSR_MCAUSE_buf = genpsticky_glbl_CSR_MCAUSE;
		genpsticky_glbl_MIRQEN_buf = genpsticky_glbl_MIRQEN;
		genpsticky_glbl_MRETADDR_buf = genpsticky_glbl_MRETADDR;
		genpstage_EXEC_genpctrl_succ = ap_uint<32>(0);
		genpstage_EXEC_genpctrl_working = ap_uint<32>(0);
		gen306_cyclix_var = genpstage_EXEC_genpctrl_stalled_glbl;
		if (gen306_cyclix_var) {
			genpstage_EXEC_genpctrl_new = ap_uint<32>(0);
			genpstage_EXEC_genpctrl_stalled_glbl = ap_uint<32>(0);
			gen307_cyclix_var = !genpstage_EXEC_genpctrl_killed_glbl;
			genpstage_EXEC_genpctrl_active_glbl = gen307_cyclix_var;
		}
		gen308_cyclix_var = ap_uint<1>(0);
		gen308_cyclix_var = (gen308_cyclix_var || gen306_cyclix_var);
		gen308_cyclix_var = !gen308_cyclix_var;
		if (gen308_cyclix_var) {
			genpstage_EXEC_genpctrl_active_glbl = ap_uint<32>(1);
			genpstage_EXEC_genpctrl_killed_glbl = ap_uint<32>(0);
			genpstage_EXEC_genpctrl_new = (genpstage_EXEC_genpctrl_active_glbl || genpstage_EXEC_genpctrl_killed_glbl);
		}
		genpstage_EXEC_genpctrl_finish = ap_uint<32>(0);
		genpstage_EXEC_genpctrl_flushreq = ap_uint<32>(0);
		genpstage_EXEC_genpctrl_nevictable = ap_uint<32>(0);
		genpstage_EXEC_genpctrl_occupied = (genpstage_EXEC_genpctrl_active_glbl | genpstage_EXEC_genpctrl_killed_glbl);
		gen309_cyclix_var = genpstage_EXEC_genpctrl_occupied;
		if (gen309_cyclix_var) {
			gen310_cyclix_var = genpstage_EXEC_genpctrl_new;
			if (gen310_cyclix_var) {
				genpstage_EXEC_instr_req_done = ap_uint<32>(0);
				genpstage_EXEC_rs1_rdata = ap_uint<32>(0);
				genpstage_EXEC_rs2_rdata = ap_uint<32>(0);
				genpstage_EXEC_irq_mcause = ap_uint<32>(0);
				genpstage_EXEC_irq_recv = ap_uint<32>(0);
				genpstage_EXEC_data_req_done = ap_uint<32>(0);
				genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_if_id = ap_uint<32>(0);
				genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdreq_pending = ap_uint<32>(0);
				genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_tid = ap_uint<32>(0);
				genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_resp_done = ap_uint<32>(0);
				genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdata = ap_uint<32>(0);
				genpstage_EXEC_genmcopipe_handle_data_mem_genvar_if_id = ap_uint<32>(0);
				genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdreq_pending = ap_uint<32>(0);
				genpstage_EXEC_genmcopipe_handle_data_mem_genvar_tid = ap_uint<32>(0);
				genpstage_EXEC_genmcopipe_handle_data_mem_genvar_resp_done = ap_uint<32>(0);
				genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdata = ap_uint<32>(0);
			}
			gen311_cyclix_var = genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdreq_pending;
			if (gen311_cyclix_var) {
				gen312_cyclix_var = (genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_if_id == ap_uint<1>(0));
				gen313_cyclix_var = gen312_cyclix_var;
				if (gen313_cyclix_var) {
					gen314_cyclix_var = (genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_tid == genmcopipe_instr_mem_rd_ptr);
					gen315_cyclix_var = gen314_cyclix_var;
					if (gen315_cyclix_var) {
						gen316_cyclix_var = genmcopipe_instr_mem_resp.read_nb(gen332_pipex_mcopipe_rdata);
						gen317_cyclix_var = gen316_cyclix_var;
						if (gen317_cyclix_var) {
							genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdreq_pending = ap_uint<32>(0);
							genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_resp_done = ap_uint<32>(1);
							genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdata = gen332_pipex_mcopipe_rdata;
							genmcopipe_instr_mem_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			gen318_cyclix_var = genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdreq_pending;
			if (gen318_cyclix_var) {
				gen319_cyclix_var = (genpstage_EXEC_genmcopipe_handle_data_mem_genvar_if_id == ap_uint<1>(0));
				gen320_cyclix_var = gen319_cyclix_var;
				if (gen320_cyclix_var) {
					gen321_cyclix_var = (genpstage_EXEC_genmcopipe_handle_data_mem_genvar_tid == genmcopipe_data_mem_rd_ptr);
					gen322_cyclix_var = gen321_cyclix_var;
					if (gen322_cyclix_var) {
						gen323_cyclix_var = genmcopipe_data_mem_resp.read_nb(gen333_pipex_mcopipe_rdata);
						gen324_cyclix_var = gen323_cyclix_var;
						if (gen324_cyclix_var) {
							genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdreq_pending = ap_uint<32>(0);
							genpstage_EXEC_genmcopipe_handle_data_mem_genvar_resp_done = ap_uint<32>(1);
							genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdata = gen333_pipex_mcopipe_rdata;
							genmcopipe_data_mem_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			gen334_pipex_genpstage_EXEC_mcopipe_rdreq_inprogress = ap_uint<32>(0);
			gen334_pipex_genpstage_EXEC_mcopipe_rdreq_inprogress = (gen334_pipex_genpstage_EXEC_mcopipe_rdreq_inprogress || genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdreq_pending);
			gen334_pipex_genpstage_EXEC_mcopipe_rdreq_inprogress = (gen334_pipex_genpstage_EXEC_mcopipe_rdreq_inprogress || genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdreq_pending);
			gen325_cyclix_var = genpstage_EXEC_genpctrl_flushreq;
			if (gen325_cyclix_var) {
				gen326_cyclix_var = gen334_pipex_genpstage_EXEC_mcopipe_rdreq_inprogress;
				if (gen326_cyclix_var) {
					gen327_cyclix_var = genpstage_EXEC_genpctrl_active_glbl;
					if (gen327_cyclix_var) {
						genpstage_EXEC_genpctrl_active_glbl = ap_uint<32>(0);
						genpstage_EXEC_genpctrl_killed_glbl = ap_uint<32>(1);
					}
				}
				gen328_cyclix_var = ap_uint<1>(0);
				gen328_cyclix_var = (gen328_cyclix_var || gen326_cyclix_var);
				gen328_cyclix_var = !gen328_cyclix_var;
				if (gen328_cyclix_var) {
					genpstage_EXEC_instr_req_done = ap_uint<32>(0);
					genpstage_EXEC_rs1_rdata = ap_uint<32>(0);
					genpstage_EXEC_rs2_rdata = ap_uint<32>(0);
					genpstage_EXEC_irq_mcause = ap_uint<32>(0);
					genpstage_EXEC_irq_recv = ap_uint<32>(0);
					genpstage_EXEC_data_req_done = ap_uint<32>(0);
					genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_if_id = ap_uint<32>(0);
					genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdreq_pending = ap_uint<32>(0);
					genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_tid = ap_uint<32>(0);
					genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_resp_done = ap_uint<32>(0);
					genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdata = ap_uint<32>(0);
					genpstage_EXEC_genmcopipe_handle_data_mem_genvar_if_id = ap_uint<32>(0);
					genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdreq_pending = ap_uint<32>(0);
					genpstage_EXEC_genmcopipe_handle_data_mem_genvar_tid = ap_uint<32>(0);
					genpstage_EXEC_genmcopipe_handle_data_mem_genvar_resp_done = ap_uint<32>(0);
					genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdata = ap_uint<32>(0);
				}
			}
		}
		gen329_cyclix_var = ap_uint<1>(0);
		gen329_cyclix_var = (gen329_cyclix_var || gen309_cyclix_var);
		gen329_cyclix_var = !gen329_cyclix_var;
		if (gen329_cyclix_var) {
			genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_resp_done = ap_uint<32>(0);
			genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdreq_pending = ap_uint<32>(0);
			genpstage_EXEC_genmcopipe_handle_data_mem_genvar_resp_done = ap_uint<32>(0);
			genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdreq_pending = ap_uint<32>(0);
		}
		gen163_pipex_syncbuf = genpsticky_glbl_jump_req_cmd;
		gen165_pipex_syncbuf = genpsticky_glbl_pc;
		gen167_pipex_syncbuf = genpsticky_glbl_jump_vector_cmd;
		gen330_cyclix_var = genpsticky_glbl_regfile[1];
		gen169_pipex_syncbuf[1] = gen330_cyclix_var;
		gen331_cyclix_var = genpsticky_glbl_regfile[2];
		gen169_pipex_syncbuf[2] = gen331_cyclix_var;
		gen332_cyclix_var = genpsticky_glbl_regfile[3];
		gen169_pipex_syncbuf[3] = gen332_cyclix_var;
		gen333_cyclix_var = genpsticky_glbl_regfile[4];
		gen169_pipex_syncbuf[4] = gen333_cyclix_var;
		gen334_cyclix_var = genpsticky_glbl_regfile[5];
		gen169_pipex_syncbuf[5] = gen334_cyclix_var;
		gen335_cyclix_var = genpsticky_glbl_regfile[6];
		gen169_pipex_syncbuf[6] = gen335_cyclix_var;
		gen336_cyclix_var = genpsticky_glbl_regfile[7];
		gen169_pipex_syncbuf[7] = gen336_cyclix_var;
		gen337_cyclix_var = genpsticky_glbl_regfile[8];
		gen169_pipex_syncbuf[8] = gen337_cyclix_var;
		gen338_cyclix_var = genpsticky_glbl_regfile[9];
		gen169_pipex_syncbuf[9] = gen338_cyclix_var;
		gen339_cyclix_var = genpsticky_glbl_regfile[10];
		gen169_pipex_syncbuf[10] = gen339_cyclix_var;
		gen340_cyclix_var = genpsticky_glbl_regfile[11];
		gen169_pipex_syncbuf[11] = gen340_cyclix_var;
		gen341_cyclix_var = genpsticky_glbl_regfile[12];
		gen169_pipex_syncbuf[12] = gen341_cyclix_var;
		gen342_cyclix_var = genpsticky_glbl_regfile[13];
		gen169_pipex_syncbuf[13] = gen342_cyclix_var;
		gen343_cyclix_var = genpsticky_glbl_regfile[14];
		gen169_pipex_syncbuf[14] = gen343_cyclix_var;
		gen344_cyclix_var = genpsticky_glbl_regfile[15];
		gen169_pipex_syncbuf[15] = gen344_cyclix_var;
		gen345_cyclix_var = genpsticky_glbl_regfile[16];
		gen169_pipex_syncbuf[16] = gen345_cyclix_var;
		gen346_cyclix_var = genpsticky_glbl_regfile[17];
		gen169_pipex_syncbuf[17] = gen346_cyclix_var;
		gen347_cyclix_var = genpsticky_glbl_regfile[18];
		gen169_pipex_syncbuf[18] = gen347_cyclix_var;
		gen348_cyclix_var = genpsticky_glbl_regfile[19];
		gen169_pipex_syncbuf[19] = gen348_cyclix_var;
		gen349_cyclix_var = genpsticky_glbl_regfile[20];
		gen169_pipex_syncbuf[20] = gen349_cyclix_var;
		gen350_cyclix_var = genpsticky_glbl_regfile[21];
		gen169_pipex_syncbuf[21] = gen350_cyclix_var;
		gen351_cyclix_var = genpsticky_glbl_regfile[22];
		gen169_pipex_syncbuf[22] = gen351_cyclix_var;
		gen352_cyclix_var = genpsticky_glbl_regfile[23];
		gen169_pipex_syncbuf[23] = gen352_cyclix_var;
		gen353_cyclix_var = genpsticky_glbl_regfile[24];
		gen169_pipex_syncbuf[24] = gen353_cyclix_var;
		gen354_cyclix_var = genpsticky_glbl_regfile[25];
		gen169_pipex_syncbuf[25] = gen354_cyclix_var;
		gen355_cyclix_var = genpsticky_glbl_regfile[26];
		gen169_pipex_syncbuf[26] = gen355_cyclix_var;
		gen356_cyclix_var = genpsticky_glbl_regfile[27];
		gen169_pipex_syncbuf[27] = gen356_cyclix_var;
		gen357_cyclix_var = genpsticky_glbl_regfile[28];
		gen169_pipex_syncbuf[28] = gen357_cyclix_var;
		gen358_cyclix_var = genpsticky_glbl_regfile[29];
		gen169_pipex_syncbuf[29] = gen358_cyclix_var;
		gen359_cyclix_var = genpsticky_glbl_regfile[30];
		gen169_pipex_syncbuf[30] = gen359_cyclix_var;
		gen360_cyclix_var = genpsticky_glbl_regfile[31];
		gen169_pipex_syncbuf[31] = gen360_cyclix_var;
		genpstage_EXEC_curinstr_addr = genpsticky_glbl_pc;
		gen170_pipex_var = genpsticky_glbl_jump_req_cmd;
		gen361_cyclix_var = gen170_pipex_var;
		if (gen361_cyclix_var) {
			genpstage_EXEC_curinstr_addr = genpsticky_glbl_jump_vector_cmd;
		}
		gen162_pipex_syncreq = ap_uint<32>(1);
		gen163_pipex_syncbuf = ap_uint<32>(0);
		gen171_pipex_var = (genpstage_EXEC_curinstr_addr + ap_uint<32>(4));
		genpstage_EXEC_nextinstr_addr = gen171_pipex_var;
		gen164_pipex_syncreq = ap_uint<32>(1);
		gen165_pipex_syncbuf = genpstage_EXEC_nextinstr_addr;
		genpstage_EXEC_instr_busreq.addr = genpstage_EXEC_curinstr_addr;
		genpstage_EXEC_instr_busreq.be = ap_uint<32>(15);
		genpstage_EXEC_instr_busreq.wdata = ap_uint<32>(0);
		gen172_pipex_var = ~genpstage_EXEC_instr_req_done;
		gen173_pipex_var = gen172_pipex_var;
		gen362_cyclix_var = gen173_pipex_var;
		if (gen362_cyclix_var) {
			gen363_cyclix_var = genpstage_EXEC_genpctrl_active_glbl;
			if (gen363_cyclix_var) {
				gen364_cyclix_var = ~genmcopipe_instr_mem_full_flag;
				gen365_cyclix_var = gen364_cyclix_var;
				if (gen365_cyclix_var) {
					gen335_pipex_req_struct.we = ap_uint<1>(0);
					gen335_pipex_req_struct.wdata = genpstage_EXEC_instr_busreq;
					gen366_cyclix_var = genmcopipe_instr_mem_req.write_nb(gen335_pipex_req_struct);
					gen367_cyclix_var = gen366_cyclix_var;
					if (gen367_cyclix_var) {
						gen174_pipex_var = ap_uint<32>(1);
						gen368_cyclix_var = !ap_uint<1>(0);
						genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdreq_pending = gen368_cyclix_var;
						genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_tid = genmcopipe_instr_mem_wr_ptr;
						genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_if_id = ap_uint<1>(0);
						gen369_cyclix_var = genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdreq_pending;
						if (gen369_cyclix_var) {
							genmcopipe_instr_mem_wr_done = ap_uint<32>(1);
						}
					}
				}
			}
			genpstage_EXEC_instr_req_done = gen174_pipex_var;
		}
		gen175_pipex_var = ~genpstage_EXEC_instr_req_done;
		gen176_pipex_var = gen175_pipex_var;
		gen370_cyclix_var = gen176_pipex_var;
		if (gen370_cyclix_var) {
			genpstage_EXEC_genpctrl_stalled_glbl = (genpstage_EXEC_genpctrl_stalled_glbl | genpstage_EXEC_genpctrl_active_glbl);
			genpstage_EXEC_genpctrl_active_glbl = ap_uint<32>(0);
		}
		gen371_cyclix_var = genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_resp_done;
		if (gen371_cyclix_var) {
			genpstage_EXEC_instr_code = genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdata;
		}
		gen177_pipex_var = genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_resp_done;
		gen178_pipex_var = ~gen177_pipex_var;
		gen179_pipex_var = gen178_pipex_var;
		gen372_cyclix_var = gen179_pipex_var;
		if (gen372_cyclix_var) {
			genpstage_EXEC_genpctrl_stalled_glbl = (genpstage_EXEC_genpctrl_stalled_glbl | genpstage_EXEC_genpctrl_active_glbl);
			genpstage_EXEC_genpctrl_active_glbl = ap_uint<32>(0);
		}
		gen180_pipex_var = genpstage_EXEC_instr_code.range(6, 0);
		genpstage_EXEC_opcode = gen180_pipex_var;
		genpstage_EXEC_alu_unsigned = ap_uint<32>(0);
		gen181_pipex_var = genpstage_EXEC_instr_code.range(19, 15);
		genpstage_EXEC_rs1_addr = gen181_pipex_var;
		gen182_pipex_var = genpstage_EXEC_instr_code.range(24, 20);
		genpstage_EXEC_rs2_addr = gen182_pipex_var;
		gen183_pipex_var = genpstage_EXEC_instr_code.range(11, 7);
		genpstage_EXEC_rd_addr = gen183_pipex_var;
		gen184_pipex_var = genpstage_EXEC_instr_code.range(14, 12);
		genpstage_EXEC_funct3 = gen184_pipex_var;
		gen185_pipex_var = genpstage_EXEC_instr_code.range(31, 25);
		genpstage_EXEC_funct7 = gen185_pipex_var;
		gen186_pipex_var = genpstage_EXEC_instr_code.range(24, 20);
		genpstage_EXEC_shamt = gen186_pipex_var;
		gen187_pipex_var = genpstage_EXEC_instr_code.range(27, 24);
		genpstage_EXEC_pred = gen187_pipex_var;
		gen188_pipex_var = genpstage_EXEC_instr_code.range(23, 20);
		genpstage_EXEC_succ = gen188_pipex_var;
		gen189_pipex_var = genpstage_EXEC_instr_code.range(31, 20);
		genpstage_EXEC_csrnum = gen189_pipex_var;
		gen190_pipex_var = genpstage_EXEC_instr_code.range(19, 15);
		genpstage_EXEC_zimm = gen190_pipex_var;
		gen191_pipex_var = genpstage_EXEC_instr_code.range(31, 20);
		gen192_pipex_var = gen191_pipex_var[31];
		gen193_pipex_var = gen192_pipex_var.concat((ap_uint<31>)gen192_pipex_var.concat((ap_uint<30>)gen192_pipex_var.concat((ap_uint<29>)gen192_pipex_var.concat((ap_uint<28>)gen192_pipex_var.concat((ap_uint<27>)gen192_pipex_var.concat((ap_uint<26>)gen192_pipex_var.concat((ap_uint<25>)gen192_pipex_var.concat((ap_uint<24>)gen192_pipex_var.concat((ap_uint<23>)gen192_pipex_var.concat((ap_uint<22>)gen192_pipex_var.concat((ap_uint<21>)gen192_pipex_var.concat((ap_uint<20>)gen192_pipex_var.concat((ap_uint<19>)gen192_pipex_var.concat((ap_uint<18>)gen192_pipex_var.concat((ap_uint<17>)gen192_pipex_var.concat((ap_uint<16>)gen192_pipex_var.concat((ap_uint<15>)gen192_pipex_var.concat((ap_uint<14>)gen192_pipex_var.concat((ap_uint<13>)gen192_pipex_var.concat((ap_uint<12>)gen191_pipex_var))))))))))))))))))));
		genpstage_EXEC_immediate_I = gen193_pipex_var;
		gen194_pipex_var = genpstage_EXEC_instr_code.range(31, 25);
		gen195_pipex_var = genpstage_EXEC_instr_code.range(11, 7);
		gen196_pipex_var = gen194_pipex_var.concat((ap_uint<5>)gen195_pipex_var);
		gen197_pipex_var = gen196_pipex_var[11];
		gen198_pipex_var = gen197_pipex_var.concat((ap_uint<31>)gen197_pipex_var.concat((ap_uint<30>)gen197_pipex_var.concat((ap_uint<29>)gen197_pipex_var.concat((ap_uint<28>)gen197_pipex_var.concat((ap_uint<27>)gen197_pipex_var.concat((ap_uint<26>)gen197_pipex_var.concat((ap_uint<25>)gen197_pipex_var.concat((ap_uint<24>)gen197_pipex_var.concat((ap_uint<23>)gen197_pipex_var.concat((ap_uint<22>)gen197_pipex_var.concat((ap_uint<21>)gen197_pipex_var.concat((ap_uint<20>)gen197_pipex_var.concat((ap_uint<19>)gen197_pipex_var.concat((ap_uint<18>)gen197_pipex_var.concat((ap_uint<17>)gen197_pipex_var.concat((ap_uint<16>)gen197_pipex_var.concat((ap_uint<15>)gen197_pipex_var.concat((ap_uint<14>)gen197_pipex_var.concat((ap_uint<13>)gen197_pipex_var.concat((ap_uint<12>)gen196_pipex_var))))))))))))))))))));
		genpstage_EXEC_immediate_S = gen198_pipex_var;
		gen199_pipex_var = genpstage_EXEC_instr_code[31];
		gen200_pipex_var = genpstage_EXEC_instr_code[7];
		gen201_pipex_var = genpstage_EXEC_instr_code.range(30, 25);
		gen202_pipex_var = genpstage_EXEC_instr_code.range(11, 8);
		gen203_pipex_var = gen199_pipex_var.concat((ap_uint<12>)gen200_pipex_var.concat((ap_uint<11>)gen201_pipex_var.concat((ap_uint<5>)gen202_pipex_var.concat((ap_uint<1>)ap_uint<1>(0)))));
		gen204_pipex_var = gen203_pipex_var[12];
		gen205_pipex_var = gen204_pipex_var.concat((ap_uint<31>)gen204_pipex_var.concat((ap_uint<30>)gen204_pipex_var.concat((ap_uint<29>)gen204_pipex_var.concat((ap_uint<28>)gen204_pipex_var.concat((ap_uint<27>)gen204_pipex_var.concat((ap_uint<26>)gen204_pipex_var.concat((ap_uint<25>)gen204_pipex_var.concat((ap_uint<24>)gen204_pipex_var.concat((ap_uint<23>)gen204_pipex_var.concat((ap_uint<22>)gen204_pipex_var.concat((ap_uint<21>)gen204_pipex_var.concat((ap_uint<20>)gen204_pipex_var.concat((ap_uint<19>)gen204_pipex_var.concat((ap_uint<18>)gen204_pipex_var.concat((ap_uint<17>)gen204_pipex_var.concat((ap_uint<16>)gen204_pipex_var.concat((ap_uint<15>)gen204_pipex_var.concat((ap_uint<14>)gen204_pipex_var.concat((ap_uint<13>)gen203_pipex_var)))))))))))))))))));
		genpstage_EXEC_immediate_B = gen205_pipex_var;
		gen206_pipex_var = genpstage_EXEC_instr_code.range(31, 12);
		gen207_pipex_var = gen206_pipex_var.concat((ap_uint<12>)ap_uint<12>(0));
		genpstage_EXEC_immediate_U = gen207_pipex_var;
		gen208_pipex_var = genpstage_EXEC_instr_code[31];
		gen209_pipex_var = genpstage_EXEC_instr_code.range(19, 12);
		gen210_pipex_var = genpstage_EXEC_instr_code[20];
		gen211_pipex_var = genpstage_EXEC_instr_code.range(30, 21);
		gen212_pipex_var = gen208_pipex_var.concat((ap_uint<20>)gen209_pipex_var.concat((ap_uint<12>)gen210_pipex_var.concat((ap_uint<11>)gen211_pipex_var.concat((ap_uint<1>)ap_uint<1>(0)))));
		gen213_pipex_var = gen212_pipex_var[20];
		gen214_pipex_var = gen213_pipex_var.concat((ap_uint<31>)gen213_pipex_var.concat((ap_uint<30>)gen213_pipex_var.concat((ap_uint<29>)gen213_pipex_var.concat((ap_uint<28>)gen213_pipex_var.concat((ap_uint<27>)gen213_pipex_var.concat((ap_uint<26>)gen213_pipex_var.concat((ap_uint<25>)gen213_pipex_var.concat((ap_uint<24>)gen213_pipex_var.concat((ap_uint<23>)gen213_pipex_var.concat((ap_uint<22>)gen213_pipex_var.concat((ap_uint<21>)gen212_pipex_var)))))))))));
		genpstage_EXEC_immediate_J = gen214_pipex_var;
		switch (genpstage_EXEC_opcode) {
			case 55:
				genpstage_EXEC_op1_source = ap_uint<32>(1);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(0);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_U;
				break;
			case 23:
				genpstage_EXEC_op1_source = ap_uint<32>(2);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_alu_opcode = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_U;
				break;
			case 111:
				genpstage_EXEC_op1_source = ap_uint<32>(2);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_alu_opcode = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(4);
				genpstage_EXEC_jump_req = ap_uint<32>(1);
				genpstage_EXEC_jump_src = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_J;
				break;
			case 103:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_alu_opcode = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(4);
				genpstage_EXEC_jump_req = ap_uint<32>(1);
				genpstage_EXEC_jump_src = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_I;
				break;
			case 99:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_rs2_req = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_alu_opcode = ap_uint<32>(1);
				genpstage_EXEC_jump_req_cond = ap_uint<32>(1);
				genpstage_EXEC_jump_src = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_B;
				gen215_pipex_var = (genpstage_EXEC_funct3 == ap_uint<32>(6));
				gen216_pipex_var = (genpstage_EXEC_funct3 == ap_uint<32>(7));
				gen217_pipex_var = (gen215_pipex_var | gen216_pipex_var);
				gen218_pipex_var = gen217_pipex_var;
				gen373_cyclix_var = gen218_pipex_var;
				if (gen373_cyclix_var) {
					genpstage_EXEC_alu_unsigned = ap_uint<32>(1);
				}
				break;
			case 3:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(5);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_mem_req = ap_uint<32>(1);
				genpstage_EXEC_mem_cmd = ap_uint<32>(0);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_I;
				break;
			case 35:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_rs2_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				genpstage_EXEC_mem_req = ap_uint<32>(1);
				genpstage_EXEC_mem_cmd = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_S;
				break;
			case 19:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(1);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_immediate = genpstage_EXEC_immediate_I;
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				switch (genpstage_EXEC_funct3) {
					case 0:
						genpstage_EXEC_alu_opcode = ap_uint<32>(0);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 1:
						genpstage_EXEC_alu_opcode = ap_uint<32>(4);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						gen219_pipex_var = genpstage_EXEC_instr_code.range(24, 20);
						gen220_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)gen219_pipex_var);
						genpstage_EXEC_immediate = gen220_pipex_var;
						break;
					case 2:
						genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						genpstage_EXEC_alu_unsigned = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(2);
						break;
					case 4:
						genpstage_EXEC_alu_opcode = ap_uint<32>(7);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 5:
						gen221_pipex_var = genpstage_EXEC_instr_code[30];
						gen222_pipex_var = gen221_pipex_var;
						gen374_cyclix_var = gen222_pipex_var;
						if (gen374_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(6);
						}
						gen223_pipex_var = ap_uint<1>(0);
						gen223_pipex_var = (gen223_pipex_var || gen222_pipex_var);
						gen223_pipex_var = !gen223_pipex_var;
						gen375_cyclix_var = gen223_pipex_var;
						if (gen375_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(5);
						}
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						gen224_pipex_var = genpstage_EXEC_instr_code.range(24, 20);
						gen225_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)gen224_pipex_var);
						genpstage_EXEC_immediate = gen225_pipex_var;
						break;
					case 6:
						genpstage_EXEC_alu_opcode = ap_uint<32>(3);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 7:
						genpstage_EXEC_alu_opcode = ap_uint<32>(2);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
				}
				break;
			case 51:
				genpstage_EXEC_rs1_req = ap_uint<32>(1);
				genpstage_EXEC_rs2_req = ap_uint<32>(1);
				genpstage_EXEC_op1_source = ap_uint<32>(0);
				genpstage_EXEC_op2_source = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(1);
				genpstage_EXEC_rd_source = ap_uint<32>(1);
				genpstage_EXEC_alu_req = ap_uint<32>(1);
				switch (genpstage_EXEC_funct3) {
					case 0:
						gen226_pipex_var = genpstage_EXEC_instr_code[30];
						gen227_pipex_var = gen226_pipex_var;
						gen376_cyclix_var = gen227_pipex_var;
						if (gen376_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						}
						gen228_pipex_var = ap_uint<1>(0);
						gen228_pipex_var = (gen228_pipex_var || gen227_pipex_var);
						gen228_pipex_var = !gen228_pipex_var;
						gen377_cyclix_var = gen228_pipex_var;
						if (gen377_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(0);
						}
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 1:
						genpstage_EXEC_alu_opcode = ap_uint<32>(4);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 2:
						genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_alu_opcode = ap_uint<32>(1);
						genpstage_EXEC_alu_unsigned = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(2);
						break;
					case 4:
						genpstage_EXEC_alu_opcode = ap_uint<32>(7);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 5:
						gen229_pipex_var = genpstage_EXEC_instr_code[30];
						gen230_pipex_var = gen229_pipex_var;
						gen378_cyclix_var = gen230_pipex_var;
						if (gen378_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(6);
						}
						gen231_pipex_var = ap_uint<1>(0);
						gen231_pipex_var = (gen231_pipex_var || gen230_pipex_var);
						gen231_pipex_var = !gen231_pipex_var;
						gen379_cyclix_var = gen231_pipex_var;
						if (gen379_cyclix_var) {
							genpstage_EXEC_alu_opcode = ap_uint<32>(5);
						}
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 6:
						genpstage_EXEC_alu_opcode = ap_uint<32>(3);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
					case 7:
						genpstage_EXEC_alu_opcode = ap_uint<32>(2);
						genpstage_EXEC_rd_source = ap_uint<32>(1);
						break;
				}
				break;
			case 15:
				genpstage_EXEC_fencereq = ap_uint<32>(1);
				break;
			case 115:
				switch (genpstage_EXEC_funct3) {
					case 0:
						gen232_pipex_var = genpstage_EXEC_instr_code[20];
						gen233_pipex_var = gen232_pipex_var;
						gen380_cyclix_var = gen233_pipex_var;
						if (gen380_cyclix_var) {
							genpstage_EXEC_ebreakreq = ap_uint<32>(1);
						}
						gen234_pipex_var = ap_uint<1>(0);
						gen234_pipex_var = (gen234_pipex_var || gen233_pipex_var);
						gen234_pipex_var = !gen234_pipex_var;
						gen381_cyclix_var = gen234_pipex_var;
						if (gen381_cyclix_var) {
							genpstage_EXEC_ecallreq = ap_uint<32>(1);
						}
						break;
					case 1:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rs1_req = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_op1_source = ap_uint<32>(0);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						break;
					case 2:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rs1_req = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_alu_req = ap_uint<32>(1);
						genpstage_EXEC_alu_opcode = ap_uint<32>(3);
						genpstage_EXEC_op1_source = ap_uint<32>(0);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rs1_req = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_alu_req = ap_uint<32>(1);
						genpstage_EXEC_alu_opcode = ap_uint<32>(8);
						genpstage_EXEC_op1_source = ap_uint<32>(0);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						break;
					case 5:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_op1_source = ap_uint<32>(1);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						gen235_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_zimm);
						genpstage_EXEC_immediate = gen235_pipex_var;
						break;
					case 6:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_alu_req = ap_uint<32>(1);
						genpstage_EXEC_alu_opcode = ap_uint<32>(8);
						genpstage_EXEC_op1_source = ap_uint<32>(1);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						gen236_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_zimm);
						genpstage_EXEC_immediate = gen236_pipex_var;
						break;
					case 7:
						genpstage_EXEC_csrreq = ap_uint<32>(1);
						genpstage_EXEC_rd_req = ap_uint<32>(1);
						genpstage_EXEC_rd_source = ap_uint<32>(6);
						genpstage_EXEC_alu_req = ap_uint<32>(1);
						genpstage_EXEC_alu_opcode = ap_uint<32>(8);
						genpstage_EXEC_op1_source = ap_uint<32>(1);
						genpstage_EXEC_op2_source = ap_uint<32>(2);
						gen237_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_zimm);
						genpstage_EXEC_immediate = gen237_pipex_var;
						break;
				}
				break;
		}
		gen238_pipex_var = genpstage_EXEC_mem_req;
		gen382_cyclix_var = gen238_pipex_var;
		if (gen382_cyclix_var) {
			switch (genpstage_EXEC_funct3) {
				case 0:
					genpstage_EXEC_mem_be = ap_uint<32>(1);
					break;
				case 1:
					genpstage_EXEC_mem_be = ap_uint<32>(3);
					break;
				case 2:
					genpstage_EXEC_mem_be = ap_uint<32>(15);
					break;
				case 4:
					genpstage_EXEC_mem_be = ap_uint<32>(1);
					break;
				case 5:
					genpstage_EXEC_mem_be = ap_uint<32>(3);
					break;
			}
		}
		gen239_pipex_var = (genpstage_EXEC_instr_code == ap_uint<32>(807403635));
		gen240_pipex_var = gen239_pipex_var;
		gen383_cyclix_var = gen240_pipex_var;
		if (gen383_cyclix_var) {
			genpstage_EXEC_mret_req = ap_uint<32>(1);
			genpstage_EXEC_jump_req = ap_uint<32>(1);
			genpstage_EXEC_jump_req_cond = ap_uint<32>(0);
			genpstage_EXEC_jump_src = ap_uint<32>(0);
			genpstage_EXEC_immediate = genpsticky_glbl_MRETADDR;
		}
		gen241_pipex_var = (genpstage_EXEC_rd_addr == ap_uint<32>(0));
		gen242_pipex_var = gen241_pipex_var;
		gen384_cyclix_var = gen242_pipex_var;
		if (gen384_cyclix_var) {
			genpstage_EXEC_rd_req = ap_uint<32>(0);
		}
		gen385_cyclix_var = genpsticky_glbl_regfile_buf[1];
		gen243_pipex_var[1] = gen385_cyclix_var;
		gen386_cyclix_var = genpsticky_glbl_regfile_buf[2];
		gen243_pipex_var[2] = gen386_cyclix_var;
		gen387_cyclix_var = genpsticky_glbl_regfile_buf[3];
		gen243_pipex_var[3] = gen387_cyclix_var;
		gen388_cyclix_var = genpsticky_glbl_regfile_buf[4];
		gen243_pipex_var[4] = gen388_cyclix_var;
		gen389_cyclix_var = genpsticky_glbl_regfile_buf[5];
		gen243_pipex_var[5] = gen389_cyclix_var;
		gen390_cyclix_var = genpsticky_glbl_regfile_buf[6];
		gen243_pipex_var[6] = gen390_cyclix_var;
		gen391_cyclix_var = genpsticky_glbl_regfile_buf[7];
		gen243_pipex_var[7] = gen391_cyclix_var;
		gen392_cyclix_var = genpsticky_glbl_regfile_buf[8];
		gen243_pipex_var[8] = gen392_cyclix_var;
		gen393_cyclix_var = genpsticky_glbl_regfile_buf[9];
		gen243_pipex_var[9] = gen393_cyclix_var;
		gen394_cyclix_var = genpsticky_glbl_regfile_buf[10];
		gen243_pipex_var[10] = gen394_cyclix_var;
		gen395_cyclix_var = genpsticky_glbl_regfile_buf[11];
		gen243_pipex_var[11] = gen395_cyclix_var;
		gen396_cyclix_var = genpsticky_glbl_regfile_buf[12];
		gen243_pipex_var[12] = gen396_cyclix_var;
		gen397_cyclix_var = genpsticky_glbl_regfile_buf[13];
		gen243_pipex_var[13] = gen397_cyclix_var;
		gen398_cyclix_var = genpsticky_glbl_regfile_buf[14];
		gen243_pipex_var[14] = gen398_cyclix_var;
		gen399_cyclix_var = genpsticky_glbl_regfile_buf[15];
		gen243_pipex_var[15] = gen399_cyclix_var;
		gen400_cyclix_var = genpsticky_glbl_regfile_buf[16];
		gen243_pipex_var[16] = gen400_cyclix_var;
		gen401_cyclix_var = genpsticky_glbl_regfile_buf[17];
		gen243_pipex_var[17] = gen401_cyclix_var;
		gen402_cyclix_var = genpsticky_glbl_regfile_buf[18];
		gen243_pipex_var[18] = gen402_cyclix_var;
		gen403_cyclix_var = genpsticky_glbl_regfile_buf[19];
		gen243_pipex_var[19] = gen403_cyclix_var;
		gen404_cyclix_var = genpsticky_glbl_regfile_buf[20];
		gen243_pipex_var[20] = gen404_cyclix_var;
		gen405_cyclix_var = genpsticky_glbl_regfile_buf[21];
		gen243_pipex_var[21] = gen405_cyclix_var;
		gen406_cyclix_var = genpsticky_glbl_regfile_buf[22];
		gen243_pipex_var[22] = gen406_cyclix_var;
		gen407_cyclix_var = genpsticky_glbl_regfile_buf[23];
		gen243_pipex_var[23] = gen407_cyclix_var;
		gen408_cyclix_var = genpsticky_glbl_regfile_buf[24];
		gen243_pipex_var[24] = gen408_cyclix_var;
		gen409_cyclix_var = genpsticky_glbl_regfile_buf[25];
		gen243_pipex_var[25] = gen409_cyclix_var;
		gen410_cyclix_var = genpsticky_glbl_regfile_buf[26];
		gen243_pipex_var[26] = gen410_cyclix_var;
		gen411_cyclix_var = genpsticky_glbl_regfile_buf[27];
		gen243_pipex_var[27] = gen411_cyclix_var;
		gen412_cyclix_var = genpsticky_glbl_regfile_buf[28];
		gen243_pipex_var[28] = gen412_cyclix_var;
		gen413_cyclix_var = genpsticky_glbl_regfile_buf[29];
		gen243_pipex_var[29] = gen413_cyclix_var;
		gen414_cyclix_var = genpsticky_glbl_regfile_buf[30];
		gen243_pipex_var[30] = gen414_cyclix_var;
		gen415_cyclix_var = genpsticky_glbl_regfile_buf[31];
		gen243_pipex_var[31] = gen415_cyclix_var;
		gen244_pipex_var = gen243_pipex_var[genpstage_EXEC_rs1_addr];
		genpstage_EXEC_rs1_rdata = gen244_pipex_var;
		gen416_cyclix_var = genpsticky_glbl_regfile_buf[1];
		gen245_pipex_var[1] = gen416_cyclix_var;
		gen417_cyclix_var = genpsticky_glbl_regfile_buf[2];
		gen245_pipex_var[2] = gen417_cyclix_var;
		gen418_cyclix_var = genpsticky_glbl_regfile_buf[3];
		gen245_pipex_var[3] = gen418_cyclix_var;
		gen419_cyclix_var = genpsticky_glbl_regfile_buf[4];
		gen245_pipex_var[4] = gen419_cyclix_var;
		gen420_cyclix_var = genpsticky_glbl_regfile_buf[5];
		gen245_pipex_var[5] = gen420_cyclix_var;
		gen421_cyclix_var = genpsticky_glbl_regfile_buf[6];
		gen245_pipex_var[6] = gen421_cyclix_var;
		gen422_cyclix_var = genpsticky_glbl_regfile_buf[7];
		gen245_pipex_var[7] = gen422_cyclix_var;
		gen423_cyclix_var = genpsticky_glbl_regfile_buf[8];
		gen245_pipex_var[8] = gen423_cyclix_var;
		gen424_cyclix_var = genpsticky_glbl_regfile_buf[9];
		gen245_pipex_var[9] = gen424_cyclix_var;
		gen425_cyclix_var = genpsticky_glbl_regfile_buf[10];
		gen245_pipex_var[10] = gen425_cyclix_var;
		gen426_cyclix_var = genpsticky_glbl_regfile_buf[11];
		gen245_pipex_var[11] = gen426_cyclix_var;
		gen427_cyclix_var = genpsticky_glbl_regfile_buf[12];
		gen245_pipex_var[12] = gen427_cyclix_var;
		gen428_cyclix_var = genpsticky_glbl_regfile_buf[13];
		gen245_pipex_var[13] = gen428_cyclix_var;
		gen429_cyclix_var = genpsticky_glbl_regfile_buf[14];
		gen245_pipex_var[14] = gen429_cyclix_var;
		gen430_cyclix_var = genpsticky_glbl_regfile_buf[15];
		gen245_pipex_var[15] = gen430_cyclix_var;
		gen431_cyclix_var = genpsticky_glbl_regfile_buf[16];
		gen245_pipex_var[16] = gen431_cyclix_var;
		gen432_cyclix_var = genpsticky_glbl_regfile_buf[17];
		gen245_pipex_var[17] = gen432_cyclix_var;
		gen433_cyclix_var = genpsticky_glbl_regfile_buf[18];
		gen245_pipex_var[18] = gen433_cyclix_var;
		gen434_cyclix_var = genpsticky_glbl_regfile_buf[19];
		gen245_pipex_var[19] = gen434_cyclix_var;
		gen435_cyclix_var = genpsticky_glbl_regfile_buf[20];
		gen245_pipex_var[20] = gen435_cyclix_var;
		gen436_cyclix_var = genpsticky_glbl_regfile_buf[21];
		gen245_pipex_var[21] = gen436_cyclix_var;
		gen437_cyclix_var = genpsticky_glbl_regfile_buf[22];
		gen245_pipex_var[22] = gen437_cyclix_var;
		gen438_cyclix_var = genpsticky_glbl_regfile_buf[23];
		gen245_pipex_var[23] = gen438_cyclix_var;
		gen439_cyclix_var = genpsticky_glbl_regfile_buf[24];
		gen245_pipex_var[24] = gen439_cyclix_var;
		gen440_cyclix_var = genpsticky_glbl_regfile_buf[25];
		gen245_pipex_var[25] = gen440_cyclix_var;
		gen441_cyclix_var = genpsticky_glbl_regfile_buf[26];
		gen245_pipex_var[26] = gen441_cyclix_var;
		gen442_cyclix_var = genpsticky_glbl_regfile_buf[27];
		gen245_pipex_var[27] = gen442_cyclix_var;
		gen443_cyclix_var = genpsticky_glbl_regfile_buf[28];
		gen245_pipex_var[28] = gen443_cyclix_var;
		gen444_cyclix_var = genpsticky_glbl_regfile_buf[29];
		gen245_pipex_var[29] = gen444_cyclix_var;
		gen445_cyclix_var = genpsticky_glbl_regfile_buf[30];
		gen245_pipex_var[30] = gen445_cyclix_var;
		gen446_cyclix_var = genpsticky_glbl_regfile_buf[31];
		gen245_pipex_var[31] = gen446_cyclix_var;
		gen246_pipex_var = gen245_pipex_var[genpstage_EXEC_rs2_addr];
		genpstage_EXEC_rs2_rdata = gen246_pipex_var;
		gen247_pipex_var = (genpstage_EXEC_rs1_addr == ap_uint<32>(0));
		gen248_pipex_var = gen247_pipex_var;
		gen447_cyclix_var = gen248_pipex_var;
		if (gen447_cyclix_var) {
			genpstage_EXEC_rs1_rdata = ap_uint<32>(0);
		}
		gen249_pipex_var = (genpstage_EXEC_rs2_addr == ap_uint<32>(0));
		gen250_pipex_var = gen249_pipex_var;
		gen448_cyclix_var = gen250_pipex_var;
		if (gen448_cyclix_var) {
			genpstage_EXEC_rs2_rdata = ap_uint<32>(0);
		}
		gen251_pipex_var = genpstage_EXEC_csrreq;
		gen449_cyclix_var = gen251_pipex_var;
		if (gen449_cyclix_var) {
			genpstage_EXEC_csr_rdata = genpsticky_glbl_CSR_MCAUSE;
		}
		genpstage_EXEC_alu_op1 = genpstage_EXEC_rs1_rdata;
		switch (genpstage_EXEC_op1_source) {
			case 1:
				genpstage_EXEC_alu_op1 = genpstage_EXEC_immediate;
				break;
			case 2:
				genpstage_EXEC_alu_op1 = genpstage_EXEC_curinstr_addr;
				break;
		}
		genpstage_EXEC_alu_op2 = genpstage_EXEC_rs2_rdata;
		switch (genpstage_EXEC_op2_source) {
			case 1:
				genpstage_EXEC_alu_op2 = genpstage_EXEC_immediate;
				break;
			case 2:
				genpstage_EXEC_alu_op2 = genpstage_EXEC_csr_rdata;
				break;
		}
		gen252_pipex_var = genpstage_EXEC_alu_unsigned;
		gen450_cyclix_var = gen252_pipex_var;
		if (gen450_cyclix_var) {
			gen253_pipex_var = ap_uint<1>(0).concat((ap_uint<32>)genpstage_EXEC_alu_op1);
			genpstage_EXEC_alu_op1_wide = gen253_pipex_var;
			gen254_pipex_var = ap_uint<1>(0).concat((ap_uint<32>)genpstage_EXEC_alu_op2);
			genpstage_EXEC_alu_op2_wide = gen254_pipex_var;
		}
		gen255_pipex_var = ap_uint<1>(0);
		gen255_pipex_var = (gen255_pipex_var || gen252_pipex_var);
		gen255_pipex_var = !gen255_pipex_var;
		gen451_cyclix_var = gen255_pipex_var;
		if (gen451_cyclix_var) {
			gen256_pipex_var = genpstage_EXEC_alu_op1[31];
			gen257_pipex_var = gen256_pipex_var.concat((ap_uint<32>)genpstage_EXEC_alu_op1);
			genpstage_EXEC_alu_op1_wide = gen257_pipex_var;
			gen258_pipex_var = genpstage_EXEC_alu_op2[31];
			gen259_pipex_var = gen258_pipex_var.concat((ap_uint<32>)genpstage_EXEC_alu_op2);
			genpstage_EXEC_alu_op2_wide = gen259_pipex_var;
		}
		gen260_pipex_var = genpsticky_glbl_MIRQEN;
		gen452_cyclix_var = gen260_pipex_var;
		if (gen452_cyclix_var) {
			gen261_pipex_var = ~genpstage_EXEC_irq_recv;
			gen262_pipex_var = gen261_pipex_var;
			gen453_cyclix_var = gen262_pipex_var;
			if (gen453_cyclix_var) {
				gen454_cyclix_var = genpstage_EXEC_genpctrl_active_glbl;
				if (gen454_cyclix_var) {
					gen455_cyclix_var = irq_fifo.read_nb(genpstage_EXEC_irq_mcause);
					gen263_pipex_var = gen455_cyclix_var;
				}
				genpstage_EXEC_irq_recv = gen263_pipex_var;
			}
			gen264_pipex_var = genpstage_EXEC_irq_recv;
			gen456_cyclix_var = gen264_pipex_var;
			if (gen456_cyclix_var) {
				genpstage_EXEC_jump_req = ap_uint<32>(1);
				genpstage_EXEC_jump_req_cond = ap_uint<32>(0);
				genpstage_EXEC_jump_src = ap_uint<32>(0);
				genpstage_EXEC_rs1_req = ap_uint<32>(0);
				genpstage_EXEC_rs2_req = ap_uint<32>(0);
				genpstage_EXEC_rd_req = ap_uint<32>(0);
				genpstage_EXEC_immediate = ap_uint<32>(128);
				genpstage_EXEC_fencereq = ap_uint<32>(0);
				genpstage_EXEC_ecallreq = ap_uint<32>(0);
				genpstage_EXEC_ebreakreq = ap_uint<32>(0);
				genpstage_EXEC_csrreq = ap_uint<32>(0);
				genpstage_EXEC_alu_req = ap_uint<32>(0);
				genpstage_EXEC_mem_req = ap_uint<32>(0);
				gen457_cyclix_var = ~genpstage_EXEC_genpctrl_stalled_glbl;
				gen458_cyclix_var = gen457_cyclix_var;
				if (gen458_cyclix_var) {
					gen459_cyclix_var = genpstage_EXEC_genpctrl_active_glbl;
					if (gen459_cyclix_var) {
						genpsticky_glbl_MIRQEN = ap_uint<32>(0);
					}
				}
				gen460_cyclix_var = ~genpstage_EXEC_genpctrl_stalled_glbl;
				gen461_cyclix_var = gen460_cyclix_var;
				if (gen461_cyclix_var) {
					gen462_cyclix_var = genpstage_EXEC_genpctrl_active_glbl;
					if (gen462_cyclix_var) {
						genpsticky_glbl_CSR_MCAUSE = genpstage_EXEC_irq_mcause;
					}
				}
				gen463_cyclix_var = ~genpstage_EXEC_genpctrl_stalled_glbl;
				gen464_cyclix_var = gen463_cyclix_var;
				if (gen464_cyclix_var) {
					gen465_cyclix_var = genpstage_EXEC_genpctrl_active_glbl;
					if (gen465_cyclix_var) {
						genpsticky_glbl_MRETADDR = genpstage_EXEC_curinstr_addr;
					}
				}
			}
		}
		gen265_pipex_var = genpstage_EXEC_mret_req;
		gen466_cyclix_var = gen265_pipex_var;
		if (gen466_cyclix_var) {
			gen467_cyclix_var = ~genpstage_EXEC_genpctrl_stalled_glbl;
			gen468_cyclix_var = gen467_cyclix_var;
			if (gen468_cyclix_var) {
				gen469_cyclix_var = genpstage_EXEC_genpctrl_active_glbl;
				if (gen469_cyclix_var) {
					genpsticky_glbl_MIRQEN = ap_uint<32>(1);
				}
			}
		}
		genpstage_EXEC_alu_result_wide = genpstage_EXEC_alu_op1_wide;
		gen266_pipex_var = genpstage_EXEC_alu_req;
		gen470_cyclix_var = gen266_pipex_var;
		if (gen470_cyclix_var) {
			switch (genpstage_EXEC_alu_opcode) {
				case 0:
					gen267_pipex_var = (genpstage_EXEC_alu_op1_wide + genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen267_pipex_var;
					break;
				case 1:
					gen268_pipex_var = (genpstage_EXEC_alu_op1_wide - genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen268_pipex_var;
					break;
				case 2:
					gen269_pipex_var = (genpstage_EXEC_alu_op1_wide & genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen269_pipex_var;
					break;
				case 3:
					gen270_pipex_var = (genpstage_EXEC_alu_op1_wide | genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen270_pipex_var;
					break;
				case 4:
					gen271_pipex_var = (genpstage_EXEC_alu_op1_wide << genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen271_pipex_var;
					break;
				case 5:
					gen272_pipex_var = genpstage_EXEC_alu_op1_wide.range(31, 0);
					gen273_pipex_var = ap_uint<32>(0).concat((ap_uint<32>)gen272_pipex_var);
					gen274_pipex_var = genpstage_EXEC_alu_op2_wide.range(4, 0);
					gen275_pipex_var = (gen273_pipex_var >> gen274_pipex_var);
					genpstage_EXEC_alu_result_wide = gen275_pipex_var;
					break;
				case 6:
					gen276_pipex_var = genpstage_EXEC_alu_op1_wide.range(31, 0);
					gen277_pipex_var = gen276_pipex_var[31];
					gen278_pipex_var = gen277_pipex_var.concat((ap_uint<63>)gen277_pipex_var.concat((ap_uint<62>)gen277_pipex_var.concat((ap_uint<61>)gen277_pipex_var.concat((ap_uint<60>)gen277_pipex_var.concat((ap_uint<59>)gen277_pipex_var.concat((ap_uint<58>)gen277_pipex_var.concat((ap_uint<57>)gen277_pipex_var.concat((ap_uint<56>)gen277_pipex_var.concat((ap_uint<55>)gen277_pipex_var.concat((ap_uint<54>)gen277_pipex_var.concat((ap_uint<53>)gen277_pipex_var.concat((ap_uint<52>)gen277_pipex_var.concat((ap_uint<51>)gen277_pipex_var.concat((ap_uint<50>)gen277_pipex_var.concat((ap_uint<49>)gen277_pipex_var.concat((ap_uint<48>)gen277_pipex_var.concat((ap_uint<47>)gen277_pipex_var.concat((ap_uint<46>)gen277_pipex_var.concat((ap_uint<45>)gen277_pipex_var.concat((ap_uint<44>)gen277_pipex_var.concat((ap_uint<43>)gen277_pipex_var.concat((ap_uint<42>)gen277_pipex_var.concat((ap_uint<41>)gen277_pipex_var.concat((ap_uint<40>)gen277_pipex_var.concat((ap_uint<39>)gen277_pipex_var.concat((ap_uint<38>)gen277_pipex_var.concat((ap_uint<37>)gen277_pipex_var.concat((ap_uint<36>)gen277_pipex_var.concat((ap_uint<35>)gen277_pipex_var.concat((ap_uint<34>)gen277_pipex_var.concat((ap_uint<33>)gen277_pipex_var.concat((ap_uint<32>)gen276_pipex_var))))))))))))))))))))))))))))))));
					gen279_pipex_var = genpstage_EXEC_alu_op2_wide.range(4, 0);
					gen280_pipex_var = (gen278_pipex_var >> gen279_pipex_var);
					genpstage_EXEC_alu_result_wide = gen280_pipex_var;
					break;
				case 7:
					gen281_pipex_var = (genpstage_EXEC_alu_op1_wide ^ genpstage_EXEC_alu_op2_wide);
					genpstage_EXEC_alu_result_wide = gen281_pipex_var;
					break;
				case 8:
					gen282_pipex_var = ~genpstage_EXEC_alu_op2_wide;
					gen283_pipex_var = (genpstage_EXEC_alu_op1_wide & gen282_pipex_var);
					genpstage_EXEC_alu_result_wide = gen283_pipex_var;
					break;
			}
			gen284_pipex_var = genpstage_EXEC_alu_result_wide.range(31, 0);
			genpstage_EXEC_alu_result = gen284_pipex_var;
			gen285_pipex_var = genpstage_EXEC_alu_result_wide[32];
			genpstage_EXEC_alu_CF = gen285_pipex_var;
			gen286_pipex_var = genpstage_EXEC_alu_result_wide[31];
			genpstage_EXEC_alu_SF = gen286_pipex_var;
			gen287_pipex_var = |genpstage_EXEC_alu_result;
			gen288_pipex_var = ~gen287_pipex_var;
			genpstage_EXEC_alu_ZF = gen288_pipex_var;
			gen289_pipex_var = genpstage_EXEC_alu_op1[31];
			gen290_pipex_var = ~gen289_pipex_var;
			gen291_pipex_var = genpstage_EXEC_alu_op2[31];
			gen292_pipex_var = ~gen291_pipex_var;
			gen293_pipex_var = genpstage_EXEC_alu_result[31];
			gen294_pipex_var = (gen292_pipex_var & gen293_pipex_var);
			gen295_pipex_var = (gen290_pipex_var & gen294_pipex_var);
			gen296_pipex_var = genpstage_EXEC_alu_op1[31];
			gen297_pipex_var = genpstage_EXEC_alu_op2[31];
			gen298_pipex_var = genpstage_EXEC_alu_result[31];
			gen299_pipex_var = ~gen298_pipex_var;
			gen300_pipex_var = (gen297_pipex_var & gen299_pipex_var);
			gen301_pipex_var = (gen296_pipex_var & gen300_pipex_var);
			gen302_pipex_var = (gen295_pipex_var | gen301_pipex_var);
			genpstage_EXEC_alu_OF = gen302_pipex_var;
			gen303_pipex_var = genpstage_EXEC_alu_unsigned;
			gen471_cyclix_var = gen303_pipex_var;
			if (gen471_cyclix_var) {
				genpstage_EXEC_alu_overflow = genpstage_EXEC_alu_CF;
			}
			gen304_pipex_var = ap_uint<1>(0);
			gen304_pipex_var = (gen304_pipex_var || gen303_pipex_var);
			gen304_pipex_var = !gen304_pipex_var;
			gen472_cyclix_var = gen304_pipex_var;
			if (gen472_cyclix_var) {
				genpstage_EXEC_alu_overflow = genpstage_EXEC_alu_OF;
			}
		}
		switch (genpstage_EXEC_rd_source) {
			case 0:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_immediate;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 1:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_alu_result;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 2:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_alu_CF;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 3:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_alu_OF;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 4:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_nextinstr_addr;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
			case 6:
				genpstage_EXEC_rd_wdata = genpstage_EXEC_csr_rdata;
				genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				break;
		}
		gen305_pipex_var = (genpstage_EXEC_curinstr_addr + genpstage_EXEC_immediate);
		genpstage_EXEC_curinstraddr_imm = gen305_pipex_var;
		switch (genpstage_EXEC_jump_src) {
			case 0:
				genpstage_EXEC_jump_vector = genpstage_EXEC_immediate;
				break;
			case 1:
				genpstage_EXEC_jump_vector = genpstage_EXEC_alu_result;
				break;
		}
		gen306_pipex_var = genpstage_EXEC_jump_req_cond;
		gen473_cyclix_var = gen306_pipex_var;
		if (gen473_cyclix_var) {
			switch (genpstage_EXEC_funct3) {
				case 0:
					gen307_pipex_var = genpstage_EXEC_alu_ZF;
					gen474_cyclix_var = gen307_pipex_var;
					if (gen474_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 1:
					gen308_pipex_var = ~genpstage_EXEC_alu_ZF;
					gen309_pipex_var = gen308_pipex_var;
					gen475_cyclix_var = gen309_pipex_var;
					if (gen475_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 4:
					gen310_pipex_var = genpstage_EXEC_alu_CF;
					gen476_cyclix_var = gen310_pipex_var;
					if (gen476_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 5:
					gen311_pipex_var = ~genpstage_EXEC_alu_CF;
					gen312_pipex_var = gen311_pipex_var;
					gen477_cyclix_var = gen312_pipex_var;
					if (gen477_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 6:
					gen313_pipex_var = genpstage_EXEC_alu_CF;
					gen478_cyclix_var = gen313_pipex_var;
					if (gen478_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
				case 7:
					gen314_pipex_var = ~genpstage_EXEC_alu_CF;
					gen315_pipex_var = gen314_pipex_var;
					gen479_cyclix_var = gen315_pipex_var;
					if (gen479_cyclix_var) {
						genpstage_EXEC_jump_req = ap_uint<32>(1);
						genpstage_EXEC_jump_vector = genpstage_EXEC_curinstraddr_imm;
					}
					break;
			}
		}
		genpstage_EXEC_mem_addr = genpstage_EXEC_alu_result;
		genpstage_EXEC_mem_wdata = genpstage_EXEC_rs2_rdata;
		gen162_pipex_syncreq = ap_uint<32>(1);
		gen163_pipex_syncbuf = genpstage_EXEC_jump_req;
		gen166_pipex_syncreq = ap_uint<32>(1);
		gen167_pipex_syncbuf = genpstage_EXEC_jump_vector;
		gen316_pipex_var = genpstage_EXEC_jump_req;
		gen480_cyclix_var = gen316_pipex_var;
		if (gen480_cyclix_var) {
			genpstage_EXEC_genpctrl_flushreq = (genpstage_EXEC_genpctrl_flushreq | genpstage_EXEC_genpctrl_active_glbl);
		}
		gen317_pipex_var = genpstage_EXEC_mem_req;
		gen481_cyclix_var = gen317_pipex_var;
		if (gen481_cyclix_var) {
			gen318_pipex_var = ~genpstage_EXEC_data_req_done;
			gen319_pipex_var = gen318_pipex_var;
			gen482_cyclix_var = gen319_pipex_var;
			if (gen482_cyclix_var) {
				genpstage_EXEC_data_busreq.addr = genpstage_EXEC_mem_addr;
				genpstage_EXEC_data_busreq.be = ap_uint<32>(15);
				genpstage_EXEC_data_busreq.wdata = genpstage_EXEC_mem_wdata;
				gen483_cyclix_var = genpstage_EXEC_genpctrl_active_glbl;
				if (gen483_cyclix_var) {
					gen484_cyclix_var = ~genmcopipe_data_mem_full_flag;
					gen485_cyclix_var = gen484_cyclix_var;
					if (gen485_cyclix_var) {
						gen336_pipex_req_struct.we = genpstage_EXEC_mem_cmd;
						gen336_pipex_req_struct.wdata = genpstage_EXEC_data_busreq;
						gen486_cyclix_var = genmcopipe_data_mem_req.write_nb(gen336_pipex_req_struct);
						gen487_cyclix_var = gen486_cyclix_var;
						if (gen487_cyclix_var) {
							gen320_pipex_var = ap_uint<32>(1);
							gen488_cyclix_var = !genpstage_EXEC_mem_cmd;
							genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdreq_pending = gen488_cyclix_var;
							genpstage_EXEC_genmcopipe_handle_data_mem_genvar_tid = genmcopipe_data_mem_wr_ptr;
							genpstage_EXEC_genmcopipe_handle_data_mem_genvar_if_id = ap_uint<1>(0);
							gen489_cyclix_var = genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdreq_pending;
							if (gen489_cyclix_var) {
								genmcopipe_data_mem_wr_done = ap_uint<32>(1);
							}
						}
					}
				}
				genpstage_EXEC_data_req_done = gen320_pipex_var;
			}
			gen321_pipex_var = ~genpstage_EXEC_data_req_done;
			gen322_pipex_var = gen321_pipex_var;
			gen490_cyclix_var = gen322_pipex_var;
			if (gen490_cyclix_var) {
				genpstage_EXEC_genpctrl_stalled_glbl = (genpstage_EXEC_genpctrl_stalled_glbl | genpstage_EXEC_genpctrl_active_glbl);
				genpstage_EXEC_genpctrl_active_glbl = ap_uint<32>(0);
			}
		}
		gen323_pipex_var = genpstage_EXEC_mem_req;
		gen491_cyclix_var = gen323_pipex_var;
		if (gen491_cyclix_var) {
			gen324_pipex_var = ~genpstage_EXEC_mem_cmd;
			gen325_pipex_var = gen324_pipex_var;
			gen492_cyclix_var = gen325_pipex_var;
			if (gen492_cyclix_var) {
				gen493_cyclix_var = genpstage_EXEC_genmcopipe_handle_data_mem_genvar_resp_done;
				if (gen493_cyclix_var) {
					genpstage_EXEC_mem_rdata = genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdata;
				}
				gen326_pipex_var = genpstage_EXEC_genmcopipe_handle_data_mem_genvar_resp_done;
				gen327_pipex_var = gen326_pipex_var;
				gen494_cyclix_var = gen327_pipex_var;
				if (gen494_cyclix_var) {
					genpstage_EXEC_rd_rdy = ap_uint<32>(1);
				}
				gen328_pipex_var = ap_uint<1>(0);
				gen328_pipex_var = (gen328_pipex_var || gen327_pipex_var);
				gen328_pipex_var = !gen328_pipex_var;
				gen495_cyclix_var = gen328_pipex_var;
				if (gen495_cyclix_var) {
					genpstage_EXEC_genpctrl_stalled_glbl = (genpstage_EXEC_genpctrl_stalled_glbl | genpstage_EXEC_genpctrl_active_glbl);
					genpstage_EXEC_genpctrl_active_glbl = ap_uint<32>(0);
				}
			}
		}
		gen329_pipex_var = (genpstage_EXEC_rd_source == ap_uint<32>(5));
		gen330_pipex_var = gen329_pipex_var;
		gen496_cyclix_var = gen330_pipex_var;
		if (gen496_cyclix_var) {
			genpstage_EXEC_rd_wdata = genpstage_EXEC_mem_rdata;
		}
		gen331_pipex_var = genpstage_EXEC_rd_req;
		gen497_cyclix_var = gen331_pipex_var;
		if (gen497_cyclix_var) {
			gen168_pipex_syncreq = ap_uint<32>(1);
			gen169_pipex_syncbuf[genpstage_EXEC_rd_addr] = genpstage_EXEC_rd_wdata;
		}
		genpstage_EXEC_genpctrl_nevictable = (genpstage_EXEC_genpctrl_nevictable || genpstage_EXEC_genmcopipe_handle_instr_mem_genvar_rdreq_pending);
		genpstage_EXEC_genpctrl_nevictable = (genpstage_EXEC_genpctrl_nevictable || genpstage_EXEC_genmcopipe_handle_data_mem_genvar_rdreq_pending);
		gen498_cyclix_var = genpstage_EXEC_genpctrl_stalled_glbl;
		if (gen498_cyclix_var) {
			genpstage_EXEC_genpctrl_finish = ap_uint<32>(0);
			genpstage_EXEC_genpctrl_succ = ap_uint<32>(0);
		}
		gen499_cyclix_var = ap_uint<1>(0);
		gen499_cyclix_var = (gen499_cyclix_var || gen498_cyclix_var);
		gen499_cyclix_var = !gen499_cyclix_var;
		if (gen499_cyclix_var) {
			genpstage_EXEC_genpctrl_finish = genpstage_EXEC_genpctrl_occupied;
			genpstage_EXEC_genpctrl_succ = genpstage_EXEC_genpctrl_active_glbl;
		}
		gen500_cyclix_var = genpstage_EXEC_genpctrl_succ;
		if (gen500_cyclix_var) {
			gen501_cyclix_var = gen162_pipex_syncreq;
			if (gen501_cyclix_var) {
				genpsticky_glbl_jump_req_cmd = gen163_pipex_syncbuf;
			}
			gen502_cyclix_var = gen164_pipex_syncreq;
			if (gen502_cyclix_var) {
				genpsticky_glbl_pc = gen165_pipex_syncbuf;
			}
			gen503_cyclix_var = gen166_pipex_syncreq;
			if (gen503_cyclix_var) {
				genpsticky_glbl_jump_vector_cmd = gen167_pipex_syncbuf;
			}
			gen504_cyclix_var = gen168_pipex_syncreq;
			if (gen504_cyclix_var) {
				gen505_cyclix_var = gen169_pipex_syncbuf[1];
				genpsticky_glbl_regfile[1] = gen505_cyclix_var;
				gen506_cyclix_var = gen169_pipex_syncbuf[2];
				genpsticky_glbl_regfile[2] = gen506_cyclix_var;
				gen507_cyclix_var = gen169_pipex_syncbuf[3];
				genpsticky_glbl_regfile[3] = gen507_cyclix_var;
				gen508_cyclix_var = gen169_pipex_syncbuf[4];
				genpsticky_glbl_regfile[4] = gen508_cyclix_var;
				gen509_cyclix_var = gen169_pipex_syncbuf[5];
				genpsticky_glbl_regfile[5] = gen509_cyclix_var;
				gen510_cyclix_var = gen169_pipex_syncbuf[6];
				genpsticky_glbl_regfile[6] = gen510_cyclix_var;
				gen511_cyclix_var = gen169_pipex_syncbuf[7];
				genpsticky_glbl_regfile[7] = gen511_cyclix_var;
				gen512_cyclix_var = gen169_pipex_syncbuf[8];
				genpsticky_glbl_regfile[8] = gen512_cyclix_var;
				gen513_cyclix_var = gen169_pipex_syncbuf[9];
				genpsticky_glbl_regfile[9] = gen513_cyclix_var;
				gen514_cyclix_var = gen169_pipex_syncbuf[10];
				genpsticky_glbl_regfile[10] = gen514_cyclix_var;
				gen515_cyclix_var = gen169_pipex_syncbuf[11];
				genpsticky_glbl_regfile[11] = gen515_cyclix_var;
				gen516_cyclix_var = gen169_pipex_syncbuf[12];
				genpsticky_glbl_regfile[12] = gen516_cyclix_var;
				gen517_cyclix_var = gen169_pipex_syncbuf[13];
				genpsticky_glbl_regfile[13] = gen517_cyclix_var;
				gen518_cyclix_var = gen169_pipex_syncbuf[14];
				genpsticky_glbl_regfile[14] = gen518_cyclix_var;
				gen519_cyclix_var = gen169_pipex_syncbuf[15];
				genpsticky_glbl_regfile[15] = gen519_cyclix_var;
				gen520_cyclix_var = gen169_pipex_syncbuf[16];
				genpsticky_glbl_regfile[16] = gen520_cyclix_var;
				gen521_cyclix_var = gen169_pipex_syncbuf[17];
				genpsticky_glbl_regfile[17] = gen521_cyclix_var;
				gen522_cyclix_var = gen169_pipex_syncbuf[18];
				genpsticky_glbl_regfile[18] = gen522_cyclix_var;
				gen523_cyclix_var = gen169_pipex_syncbuf[19];
				genpsticky_glbl_regfile[19] = gen523_cyclix_var;
				gen524_cyclix_var = gen169_pipex_syncbuf[20];
				genpsticky_glbl_regfile[20] = gen524_cyclix_var;
				gen525_cyclix_var = gen169_pipex_syncbuf[21];
				genpsticky_glbl_regfile[21] = gen525_cyclix_var;
				gen526_cyclix_var = gen169_pipex_syncbuf[22];
				genpsticky_glbl_regfile[22] = gen526_cyclix_var;
				gen527_cyclix_var = gen169_pipex_syncbuf[23];
				genpsticky_glbl_regfile[23] = gen527_cyclix_var;
				gen528_cyclix_var = gen169_pipex_syncbuf[24];
				genpsticky_glbl_regfile[24] = gen528_cyclix_var;
				gen529_cyclix_var = gen169_pipex_syncbuf[25];
				genpsticky_glbl_regfile[25] = gen529_cyclix_var;
				gen530_cyclix_var = gen169_pipex_syncbuf[26];
				genpsticky_glbl_regfile[26] = gen530_cyclix_var;
				gen531_cyclix_var = gen169_pipex_syncbuf[27];
				genpsticky_glbl_regfile[27] = gen531_cyclix_var;
				gen532_cyclix_var = gen169_pipex_syncbuf[28];
				genpsticky_glbl_regfile[28] = gen532_cyclix_var;
				gen533_cyclix_var = gen169_pipex_syncbuf[29];
				genpsticky_glbl_regfile[29] = gen533_cyclix_var;
				gen534_cyclix_var = gen169_pipex_syncbuf[30];
				genpsticky_glbl_regfile[30] = gen534_cyclix_var;
				gen535_cyclix_var = gen169_pipex_syncbuf[31];
				genpsticky_glbl_regfile[31] = gen535_cyclix_var;
			}
		}
		gen536_cyclix_var = genpstage_EXEC_genpctrl_finish;
		if (gen536_cyclix_var) {
			genpstage_EXEC_genpctrl_active_glbl = ap_uint<32>(0);
			genpstage_EXEC_genpctrl_killed_glbl = ap_uint<32>(0);
			genpstage_EXEC_genpctrl_stalled_glbl = ap_uint<32>(0);
		}
		gen537_cyclix_var = ~genpstage_EXEC_genpctrl_stalled_glbl;
		genpstage_EXEC_genpctrl_rdy = gen537_cyclix_var;
		genpstage_EXEC_genpctrl_working = (genpstage_EXEC_genpctrl_succ | genpstage_EXEC_genpctrl_stalled_glbl);
		gen538_cyclix_var = genmcopipe_instr_mem_rd_done;
		if (gen538_cyclix_var) {
			genmcopipe_instr_mem_rd_ptr = genmcopipe_instr_mem_rd_ptr_next;
			genmcopipe_instr_mem_full_flag = ap_uint<32>(0);
			gen539_cyclix_var = (genmcopipe_instr_mem_rd_ptr == genmcopipe_instr_mem_wr_ptr);
			gen540_cyclix_var = gen539_cyclix_var;
			if (gen540_cyclix_var) {
				genmcopipe_instr_mem_empty_flag = ap_uint<32>(1);
			}
		}
		gen541_cyclix_var = genmcopipe_instr_mem_wr_done;
		if (gen541_cyclix_var) {
			genmcopipe_instr_mem_wr_ptr = genmcopipe_instr_mem_wr_ptr_next;
			genmcopipe_instr_mem_empty_flag = ap_uint<32>(0);
			gen542_cyclix_var = (genmcopipe_instr_mem_rd_ptr == genmcopipe_instr_mem_wr_ptr);
			gen543_cyclix_var = gen542_cyclix_var;
			if (gen543_cyclix_var) {
				genmcopipe_instr_mem_full_flag = ap_uint<32>(1);
			}
		}
		gen544_cyclix_var = genmcopipe_data_mem_rd_done;
		if (gen544_cyclix_var) {
			genmcopipe_data_mem_rd_ptr = genmcopipe_data_mem_rd_ptr_next;
			genmcopipe_data_mem_full_flag = ap_uint<32>(0);
			gen545_cyclix_var = (genmcopipe_data_mem_rd_ptr == genmcopipe_data_mem_wr_ptr);
			gen546_cyclix_var = gen545_cyclix_var;
			if (gen546_cyclix_var) {
				genmcopipe_data_mem_empty_flag = ap_uint<32>(1);
			}
		}
		gen547_cyclix_var = genmcopipe_data_mem_wr_done;
		if (gen547_cyclix_var) {
			genmcopipe_data_mem_wr_ptr = genmcopipe_data_mem_wr_ptr_next;
			genmcopipe_data_mem_empty_flag = ap_uint<32>(0);
			gen548_cyclix_var = (genmcopipe_data_mem_rd_ptr == genmcopipe_data_mem_wr_ptr);
			gen549_cyclix_var = gen548_cyclix_var;
			if (gen549_cyclix_var) {
				genmcopipe_data_mem_full_flag = ap_uint<32>(1);
			}
		}
	}
}
